# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-04-24 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0059_auto_20210330_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipitemtransdetail',
            name='transtype',
            field=models.CharField(blank=True, choices=[('G', '购入'), ('S', '服务'), ('ZT', '自提'), ('M', '快递'), ('U', '在店使用')], max_length=16, null=True, verbose_name='项目交易类型'),
        ),
        migrations.AlterField(
            model_name='vipitemtranshead',
            name='transtype',
            field=models.CharField(blank=True, choices=[('G', '购入'), ('S', '服务'), ('ZT', '自提'), ('M', '快递'), ('U', '在店使用')], max_length=16, null=True, verbose_name='项目交易类型'),
        ),
        migrations.AlterField(
            model_name='vipitemtranslog',
            name='transtype',
            field=models.CharField(blank=True, choices=[('G', '购入'), ('S', '服务'), ('ZT', '自提'), ('M', '快递'), ('U', '在店使用')], max_length=16, null=True, verbose_name='项目交易类型'),
        ),
    ]
