# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-05-04 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0060_auto_20210424_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardhistory',
            name='adjuestamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='调整金额'),
        ),
        migrations.AddField(
            model_name='cardhistory',
            name='adjuesttype',
            field=models.CharField(blank=True, choices=[('10', 'oldtonew'), ('20', 'void card')], max_length=8, null=True, verbose_name='金额调整类型'),
        ),
        migrations.AddField(
            model_name='cardhistory',
            name='oldcardtonew',
            field=models.ForeignKey(blank=True, db_column='oldcardtonewuuid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cashier.Oldcardtonew'),
        ),
    ]
