# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-05-05 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0061_auto_20210504_2203'),
    ]

    operations = [

        migrations.AlterField(
            model_name='toll',
            name='bankaccount',
            field=models.CharField(blank=True, db_column='bankaccount', max_length=32, null=True, verbose_name='银行账号'),
        ),
        migrations.AlterField(
            model_name='toll',
            name='confirm_ecode',
            field=models.CharField(blank=True, db_column='confirm_ecode', max_length=32, null=True, verbose_name='财务确认人'),
        ),
    ]
