# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-05-11 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0062_auto_20210505_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpvstollCash',
            fields=[
            ],
            options={
                'verbose_name_plural': '现金类交易',
                'verbose_name': '现金类交易',
                'proxy': True,
                'indexes': [],
            },
            bases=('cashier.expvstoll',),
        ),
        migrations.CreateModel(
            name='TollCash',
            fields=[
            ],
            options={
                'verbose_name_plural': '现金类收款',
                'verbose_name': '现金类收款',
                'proxy': True,
                'indexes': [],
            },
            bases=('cashier.toll',),
        ),
    ]
