# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2022-06-06 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0064_auto_20210711_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardhistory',
            name='suptype',
            field=models.CharField(blank=True, choices=[('10', '储值卡'), ('14', '产品卡'), ('20', '疗程卡'), ('25', '月卡/季卡'), ('30', '赠送储值'), ('40', '赠送疗程')], max_length=8, null=True, verbose_name='卡大类'),
        ),
    ]
