# Generated by Django 3.2.18 on 2026-05-01 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0046_auto_20260501_0846'),
        ('baseinfo', '0167_auto_20260501_0846'),
        ('cashier', '0065_auto_20220606_2313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sequence',
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='suptype',
            field=models.CharField(blank=True, choices=[('10', '储值卡'), ('14', '产品卡'), ('20', '疗程卡'), ('25', '月卡/季卡'), ('30', '赠送储值'), ('40', '赠送疗程'), ('50', '时效卡')], max_length=8, null=True, verbose_name='卡大类'),
        ),
        migrations.AlterField(
            model_name='discic',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='earnestmoney',
            name='hunguuid',
            field=models.ForeignKey(blank=True, db_column='hungsuuid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adviser.expvstollhung', verbose_name='开单记录'),
        ),
        migrations.AlterField(
            model_name='earnestmoney',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='earnestmoney',
            name='transuuid',
            field=models.ForeignKey(blank=True, db_column='transuuid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cashier.expvstoll', verbose_name='交易记录'),
        ),
        migrations.AlterField(
            model_name='earnestmoney',
            name='vipuuid',
            field=models.ForeignKey(blank=True, db_column='vipuuid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.vip', verbose_name='客人'),
        ),
        migrations.AlterField(
            model_name='emplarchivementdetail',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='emplarchivementdetail',
            name='trans',
            field=models.ForeignKey(blank=True, db_column='transuuid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cashier.expvstoll', verbose_name='交易'),
        ),
        migrations.AlterField(
            model_name='empldailydata',
            name='empl',
            field=models.ForeignKey(blank=True, db_column='empl', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.empl', verbose_name='员工'),
        ),
        migrations.AlterField(
            model_name='empldailydata',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='expvstoll',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='forfeit',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='oldcardtonew',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='toll',
            name='bankaccount',
            field=models.CharField(blank=True, choices=[], db_column='bankaccount', max_length=32, null=True, verbose_name='银行账号'),
        ),
        migrations.AlterField(
            model_name='toll',
            name='confirm_ecode',
            field=models.CharField(blank=True, choices=[], db_column='confirm_ecode', max_length=32, null=True, verbose_name='财务确认人'),
        ),
        migrations.AlterField(
            model_name='toll',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='vipiteminfo',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='vipiteminfo',
            name='vip',
            field=models.ForeignKey(blank=True, db_column='vipuuid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.vip', verbose_name='客人'),
        ),
        migrations.AlterField(
            model_name='vipitemtransdetail',
            name='itemuuid',
            field=models.ForeignKey(blank=True, db_column='itemuuid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.item', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='vipitemtransdetail',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='vipitemtransdetail',
            name='vipiteminfo',
            field=models.ForeignKey(blank=True, db_column='vipiteminfouuid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cashier.vipiteminfo', verbose_name='会员项目'),
        ),
        migrations.AlterField(
            model_name='vipitemtransdetail',
            name='vipitemtrans',
            field=models.ForeignKey(blank=True, db_column='vipitemtransuuid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cashier.vipitemtranshead', verbose_name='会员项目交易'),
        ),
        migrations.AlterField(
            model_name='vipitemtranshead',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
    ]
