# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-22 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldcardtypeitemdetail',
            name='cardname',
            field=models.CharField(blank=True, db_column='cardname', max_length=32, null=True, verbose_name='卡类名称'),
        ),
        migrations.AlterField(
            model_name='oldcardtypeitemdetail',
            name='cardtype',
            field=models.CharField(blank=True, db_column='cardtype', max_length=16, null=True, verbose_name='卡类'),
        ),
    ]
