# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-25 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanage', '0002_auto_20190522_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldcardtypeitemdetail',
            name='newitemcode',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='新项目编号'),
        ),
    ]
