#coding = utf-8
# ""
# Django settings for shgv project.
#
# Generated by 'django-admin startproject' using Django 1.10.5.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/1.10/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/1.10/ref/settings/
# """

import os
import datetime

from dotenv import load_dotenv

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
load_dotenv(os.path.join(BASE_DIR, ".env"))
# PROJECT_PATH='c:/python35/genesis/'

# print(BASE_DIR,PROJECT_PATH)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY", "django-insecure-set-DJANGO_SECRET_KEY-in-.env"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in ("1", "true", "yes")

_ah = os.environ.get("DJANGO_ALLOWED_HOSTS", "*").strip()
ALLOWED_HOSTS = ["*"] if _ah == "*" else [h.strip() for h in _ah.split(",") if h.strip()]
#ALLOWED_HOSTS = ['192.168.2.52',]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'common',
    'baseinfo',
    'adviser',
    'cashier',
    'goods',
    'crm',
    'jmj',
    'report',
    'datamanage',
    'wechat',
    'mall',
#    'sysoption',
    'rest_framework',
    'django_filters',
    'menus',
    'assistant',
    # 'xadmin',
    'crispy_forms',
    'reversion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'genesis.urls'

# django.contrib.sites：固定站点，避免按 Host 查表失败（如本地 127.0.0.1:8030 无匹配域名）
SITE_ID = int(os.environ.get("DJANGO_SITE_ID", "1"))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
        # 'builtins': ['django.templatetags.static'],
    },
]

WSGI_APPLICATION = 'genesis.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("DB_NAME", "youlan"),
        "USER": os.environ.get("DB_USER", "sa"),
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
        "PORT": os.environ.get("DB_PORT", "3306"),
        "OPTIONS": {"charset": "utf8mb4"},
    }
}

DATA_UPLOAD_MAX_NUMBER_FIELDS=None

import pymysql
pymysql.install_as_MySQLdb()

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-cn'

TIME_ZONE = 'Asia/Shanghai'   #'UTC'

USE_I18N = True

USE_L10N = True

# USE_TZ = True
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR,'static')
#
# #upload path
# MEDIA_URL = '/images/'
# MEDIA_ROOT = os.path.join(BASE_DIR,'images')

#MEDIA_ROOT = os.path.join(PROJECT_PATH,'media')

# print(STATICFILES_DIRS)
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
IMAGE_ROOT = os.path.join(STATIC_ROOT, 'images/')
#
STATIC_URL = '/static/'
IMAGE_URL ='/images/'

STATICFILES_DIRS = (
    ('css', os.path.join(STATIC_ROOT, 'css')),
    ('images', os.path.join(STATIC_ROOT, 'images')),
    ('fonts', os.path.join(STATIC_ROOT, 'fonts')),
    ('js', os.path.join(STATIC_ROOT, 'js')),
    ('pdf', os.path.join(STATIC_ROOT, 'pdf')),
)




MENU_SELECT_PARENTS = False
MENU_HIDE_EMPTY = False

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    'PAGE_SIZE': 20

    # 'DEFAULT_PERMISSION_CLASSES':(
    #     'rest_framework.permissions.IsAuthenticated',
    # ),
    # 'DEFAULT_AUTHENTICATION_CLASSES': (
    #     # drf的这一阶段主要是做验证,middleware的auth主要是设置session和user到request对象
    #     # 默认的验证是按照验证列表从上到下的验证
    #     'rest_framework.authentication.BasicAuthentication',
    #     'rest_framework.authentication.SessionAuthentication',
    #     "rest_framework_jwt.authentication.JSONWebTokenAuthentication",
    # )
}

# JWT_AUTH = {
#     # 指明token的有效期
#     'JWT_EXPIRATION_DELTA': datetime.timedelta(days=7),
#     # token前缀
#     'JWT_AUTH_HEADER_PREFIX': 'JWT',
# }

# setting中添加BANCENDS
# AUTHENTICATION_BACKENDS = (
#     # 将bancends添加进setting
#     'wechat.views.WechatBackend',
# )

# APPEND_SLASH=False
#
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'loggers': {
#         'django.db.backends': {
#             'handlers': ['console'],
#             'level': 'DEBUG' if DEBUG else 'INFO',
#         },
#     },
# }

DEPLOY_ROOT_LOCAL = '/'
MY_DOMAIN_URL_LOCAL = '/'
MY_DOMAIN_URL='/'

DEPLOY_ROOT_PRO = 'HTTPS://www.softweb.net.cn/genesis/'
MY_DOMAIN_URL_PRO = 'https://www.softweb.net.cn/genesis/'

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# 测试库：GENESIS_USE_TEST_DB=1 时使用 test_<DB_NAME>（须先 bash scripts/setup-test-db.sh）
if os.environ.get("GENESIS_USE_TEST_DB") == "1":
    _db_name = DATABASES["default"]["NAME"]
    if not str(_db_name).startswith("test_"):
        DATABASES["default"]["NAME"] = "test_" + str(_db_name)
    DATABASES["default"]["TEST"] = {"NAME": DATABASES["default"]["NAME"]}