# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-04-24 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0073_auto_20210405_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstransdetail',
            name='gcode',
            field=models.CharField(blank=True, choices=[('2030701000', '育肌酶'), ('2030702001', '还氧蛋白精华液'), ('2030702002', '细胞复活乳Ⅱ'), ('2030702003', '还氧肽白精华啫喱'), ('2030703001', '还氧蛋白精华液'), ('2030703002', '细胞复活乳Ⅱ'), ('2030703003', '还氧肽白精华啫喱'), ('2030803078', '原液-抗皱紧致霜'), ('2030810079', '原液-MSR-H身体滋养霜'), ('2041200002', '细胞1号')], db_column='gcode', max_length=16, null=True, verbose_name='商品'),
        ),
    ]
