# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2022-01-24 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0164_auto_20220124_1515'),
        ('goods', '0077_auto_20220124_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstranslog',
            name='goodsuuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Goods', verbose_name='商品uuid'),
        ),
    ]
