# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2022-01-24 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0078_goodstranslog_goodsuuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstranslog',
            name='goodsuuid',
            field=models.ForeignKey(blank=True, db_column='goodsuuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Goods', verbose_name='商品uuid'),
        ),
    ]
