# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-02 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineshowitem',
            name='large_showimage',
        ),
    ]
