# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-05 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_auto_20200505_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineshowitem',
            name='orderno',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='onlineshowitem',
            name='company',
            field=models.CharField(blank=True, default='yiren', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='onlineshowtype',
            name='company',
            field=models.CharField(blank=True, default='yiren', max_length=8, null=True, verbose_name='公司'),
        ),
    ]
