# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-05 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_auto_20200505_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlineshowitem',
            options={'managed': True, 'verbose_name': '线上项目', 'verbose_name_plural': '线上项目'},
        ),
        migrations.AlterModelOptions(
            name='onlineshowtype',
            options={'managed': True, 'verbose_name': '线上显示分类', 'verbose_name_plural': '线上显示分类'},
        ),
        migrations.RenameField(
            model_name='onlineshowtype',
            old_name='showcode',
            new_name='showtypecode',
        ),
        migrations.RenameField(
            model_name='onlineshowtype',
            old_name='showimage',
            new_name='showtypeimage',
        ),
        migrations.RenameField(
            model_name='onlineshowtype',
            old_name='showname',
            new_name='showtypename',
        ),
        migrations.RenameField(
            model_name='onlineshowtype',
            old_name='showurl',
            new_name='showtypeurl',
        ),
    ]
