# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-16 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0005_auto_20200505_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('creater', models.CharField(blank=True, default='anonymous', max_length=16, null=True, verbose_name='创建者')),
                ('flag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除')),
                ('company', models.CharField(blank=True, default='yiren', max_length=8, null=True, verbose_name='公司')),
                ('appcode', models.CharField(blank=True, max_length=16, null=True, verbose_name='小程序编号')),
                ('pages', models.CharField(blank=True, max_length=128, null=True, verbose_name='页面')),
                ('linkURL', models.URLField(blank=True, max_length=128, null=True, verbose_name='链接')),
                ('bannerimage', models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='展示图片')),
            ],
            options={
                'db_table': 'banner',
                'managed': True,
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
            },
        ),
    ]
