# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-17 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0007_auto_20200517_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='orderno',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=8, null=True, verbose_name='序号'),
        ),
    ]
