# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-03-19 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0013_auto_20210308_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='company',
            field=models.CharField(blank=True, default='yfy', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='onlineitemimage',
            name='company',
            field=models.CharField(blank=True, default='yfy', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='onlineshowitem',
            name='company',
            field=models.CharField(blank=True, default='yfy', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='onlineshowtype',
            name='company',
            field=models.CharField(blank=True, default='yfy', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='onlineshowtype',
            name='showtypecode',
            field=models.CharField(blank=True, choices=[('PMJG', '皮秒激光'), ('YP', '药品'), ('KB', '开背'), ('300', '仪器'), ('XFL', '欣菲聆'), ('EB', 'EB'), ('GZ', '光子'), ('XM', '禧满'), ('FZC', '法姿纯'), ('GXRZ', '光纤溶脂'), ('BNS', '玻尿酸'), ('YDM', '伊蒂美'), ('JSM', '简诗美'), ('FML', '菲蜜丽'), ('HJWZ', '黄金微针'), ('JGYQ', '激光仪器'), ('ADMD', '3DEEP射频'), ('RCYP', '日常用品'), ('CC', '痤疮'), ('BNSLT', '丽瑅'), ('YBS', '俞博士'), ('TBZSW', '体表赘生物'), ('HXM', '海皙曼'), ('LX001', '立秀'), ('SMYQ', '私密仪器'), ('Legacy', 'Legacy射频仪'), ('RMJ', '热玛吉'), ('TYL', '童颜龄'), ('LFL', '罗肤籣'), ('MRYQ', '美容仪器'), ('MLY', '魔力仪'), ('QJYQ', '清洁仪器'), ('MBDB', '美白淡斑'), ('FLX', '富勒烯'), ('MSDK', '美斯帝克'), ('QZ', '奇致'), ('SFS', '奢菲斯'), ('SS', '手术'), ('BNJSL', '伯纳佳诗丽'), ('SY', '舒颜'), ('SR', '丝柔'), ('YHP', '易耗品'), ('KS', '酷塑'), ('ACWE', '爱驰维尔'), ('JBJS', '吉备酵素'), ('MLTS', '美丽天使'), ('MFMY', '美芾美源'), ('XBYZ', '细胞因子'), ('YDN', '伊杜娜'), ('CD', 'PCD'), ('BOSS', 'BOSS'), ('PCL', 'PCL'), ('GL', '刚伦'), ('PLD', '普拉朵'), ('QSN', '轻奢尼'), ('SH', '赛涵'), ('NM', '南明'), ('SL', '丝丽'), ('XBE', '旭贝尔-精油'), ('ANS', '安娜苏'), ('AEB', '奥尔滨（奥戴尔、奥比虹、FX、傲之美）'), ('BLQ', '贝丽清'), ('BLY', '博兰雅'), ('FEM', '法儿曼'), ('KYY', '科优研'), ('CPQT', '产品其他'), ('XSC', '芯丝翠'), ('LD', '朗顿'), ('BIO', 'BIO'), ('ZP', '赠品'), ('BOTOX', 'BOTOX'), ('NB', 'NB悦碧施'), ('ALW', '艾莉薇'), ('ANBS', '爱努碧斯'), ('ARD', '爱芮达'), ('AGAQ', '安格安晴'), ('AT', '奥肽'), ('BLLBY', '宝龄丽碧雅'), ('RL', '瑞蓝'), ('FSL', '法思丽'), ('FLJ', '菲洛嘉'), ('HW', '海薇'), ('KHT', '坤和堂（和坤堂）'), ('HT', '嗨体'), ('HL', '衡力'), ('JN', '珈纳'), ('JL', '姣兰'), ('JSY', '今生缘（金生缘）'), ('JB', '巨邦'), ('LJ', '朗健'), ('ZCWZX', '乔雅登'), ('RES', '瑞恩诗'), ('RJA', '瑞嘉奥'), ('RSM', '瑞诗美'), ('RBY', '润百颜（润白颜）'), ('RZ', '润致'), ('SM', '双美'), ('SD', '思蒂'), ('TNTL', '肽能天露'), ('WG', '维观'), ('XLK', '修丽可'), ('YMY', '研美颜'), ('YFQ', '伊肤泉'), ('YW', '伊婉'), ('YZQ', '益之泉'), ('YN', '英诺'), ('SMTH', '圣美天合-俞博士'), ('KQ', '口腔'), ('XZY', '雪之莹'), ('XYWX', '行云纹绣'), ('RLSM', '蕊丽'), ('PLLS', '帕莉丽丝'), ('BNSWT', '唯瑅'), ('LA', 'LA'), ('MRS', '美瑞诗'), ('HSPOW', '韩式POW'), ('SB', '思贝'), ('MSY', '美塑优'), ('ZFX', '泽芙雪'), ('SLSP', '深蓝射频'), ('YLYQ', '医疗仪器'), ('TJ', '胎记'), ('SG', '水光'), ('PNY', '普诺亚'), ('QT', '其他'), ('TM', '脱毛'), ('CSD', '极限音波拉皮'), ('AEFL', '爱尔菲林'), ('YKM', '易可美'), ('JX', '金炫'), ('MGXF', '敏感修复')], max_length=32, null=True, verbose_name='代码'),
        ),
    ]
