# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-03-19 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0014_auto_20210319_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='company',
            field=models.CharField(blank=True, default='dsdemo', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='onlineitemimage',
            name='company',
            field=models.CharField(blank=True, default='dsdemo', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='onlineshowitem',
            name='company',
            field=models.CharField(blank=True, default='dsdemo', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='onlineshowtype',
            name='company',
            field=models.CharField(blank=True, default='dsdemo', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='onlineshowtype',
            name='showtypecode',
            field=models.CharField(blank=True, choices=[('001', '元馔'), ('003', '原液之谜'), ('001', '操作'), ('001', '即时副卡'), ('002', '养生')], max_length=32, null=True, verbose_name='代码'),
        ),
    ]
