# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-10 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('last_modified', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间')),
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('creater', models.CharField(blank=True, default='anonymous', max_length=16, null=True, verbose_name='创建者')),
                ('flag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除')),
                ('company', models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司')),
                ('storecode', models.CharField(blank=True, max_length=16, null=True, verbose_name='门店')),
                ('sequence', models.DecimalField(blank=True, db_column='SEQUENCE', decimal_places=0, default=1, max_digits=20, null=True)),
                ('tablecode', models.CharField(db_column='TABLECODE', max_length=40,  serialize=False)),
            ],
            options={
                'db_table': 'sequence',
                'managed': True,
            },
        ),
    ]
