# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-10 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='sequence',
        #     name='tablecode',
        #     field=models.CharField(db_column='TABLECODE', max_length=40),
        # ),
    ]
