# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-12 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190410_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='WifiList',
            fields=[
                ('last_modified', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间')),
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('creater', models.CharField(blank=True, default='anonymous', max_length=16, null=True, verbose_name='创建者')),
                ('flag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除')),
                ('company', models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司')),
                ('storecode', models.CharField(blank=True, max_length=16, null=True, verbose_name='门店')),
                ('SSID', models.CharField(max_length=32, verbose_name='SSID')),
                ('BSSID', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='BSSID')),
                ('valiflag', models.CharField(blank=True, default='Y', max_length=8, null=True, verbose_name='是否允许')),
            ],
            options={
                'db_table': 'wifilist',
                'managed': True,
            },
        ),
    ]
