# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-04 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20190602_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='tablecode',
            field=models.CharField(db_column='TABLECODE', max_length=40),
        ),
    ]
