# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-01 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0012_auto_20191221_0036'),
        ('common', '0012_auto_20191221_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_item_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='收费项目编号')),
                ('company_item_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='收费项目名称')),
                ('company_item_desc', models.CharField(blank=True, max_length=512, null=True, verbose_name='收费项目描述')),
                ('company_item_qty', models.IntegerField(blank=True, default=1, null=True, verbose_name='数量')),
                ('company_pay_period', models.CharField(blank=True, max_length=16, null=True, verbose_name='单位')),
                ('company_item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='价格')),
                ('companylist', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('00', '总部'), ('01', '赛特店'), ('02', '安立店'), ('03', '长安店'), ('04', '马奈店'), ('88', '练习店')], max_length=17, null=True, verbose_name='适用公司')),
                ('storelist', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('00', '总部'), ('01', '赛特店'), ('02', '安立店'), ('03', '长安店'), ('04', '马奈店'), ('88', '练习店')], max_length=17, null=True, verbose_name='适用门店')),
            ],
            options={
                'managed': True,
                'verbose_name_plural': '商户项目',
                'verbose_name': '商户项目',
                'db_table': 'CompanyItem',
            },
        ),
        migrations.CreateModel(
            name='CompanyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(blank=True, max_length=128, null=True, verbose_name='openid')),
                ('unionid', models.CharField(blank=True, max_length=128, null=True, verbose_name='unionid')),
                ('order_no', models.CharField(blank=True, max_length=128, null=True, verbose_name='订单号')),
                ('order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='支付金额')),
                ('order_status', models.CharField(blank=True, max_length=8, null=True, verbose_name='订单状态')),
                ('payed_datetime', models.DateTimeField(verbose_name='订单支付时间')),
                ('wechatuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat.WechatUser', verbose_name='微信用户')),
            ],
            options={
                'managed': True,
                'verbose_name_plural': '商户订单',
                'verbose_name': '商户订单',
                'db_table': 'CompanyOrder',
            },
        ),
        migrations.CreateModel(
            name='CompanyOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, max_length=128, null=True, verbose_name='订单号')),
                ('order_item', models.CharField(blank=True, max_length=32, null=True, verbose_name='订单项目')),
                ('companylist', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('00', '总部'), ('01', '赛特店'), ('02', '安立店'), ('03', '长安店'), ('04', '马奈店'), ('88', '练习店')], max_length=17, null=True, verbose_name='续费公司')),
                ('storelist', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('00', '总部'), ('01', '赛特店'), ('02', '安立店'), ('03', '长安店'), ('04', '马奈店'), ('88', '练习店')], max_length=17, null=True, verbose_name='续费门店')),
                ('payed_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='支付店月数')),
                ('company_pay_period', models.CharField(blank=True, max_length=16, null=True, verbose_name='单位')),
                ('payed_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='店月单价')),
                ('payed_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='付款金额')),
                ('order_fromdate', models.DateField(blank=True, null=True, verbose_name='付款生效开始日期')),
                ('order_todate', models.DateField(blank=True, null=True, verbose_name='付款生效截止日期')),
                ('company_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.CompanyOrder', verbose_name='订单')),
            ],
            options={
                'managed': True,
                'verbose_name_plural': '商户订单内容',
                'verbose_name': '商户订单内容',
                'db_table': 'CompanyOrderItem',
            },
        ),
        migrations.CreateModel(
            name='CompanyOrderPayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, max_length=128, null=True, verbose_name='订单号')),
                ('payed_method', models.CharField(blank=True, max_length=32, null=True, verbose_name='付款方式')),
                ('payed_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='付款金额')),
                ('company_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.CompanyOrder', verbose_name='订单')),
            ],
            options={
                'managed': True,
                'verbose_name_plural': '商户订单付款信息',
                'verbose_name': '商户订单付款信息',
                'db_table': 'CompanyOrderPayInfo',
            },
        ),
    ]
