# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-03 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_companyitem_companyorder_companyorderitem_companyorderpayinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyitem',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='建立时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyitem',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='companyitem',
            name='flag',
            field=models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='companyitem',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间'),
        ),
        migrations.AddField(
            model_name='companyorder',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='建立时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyorder',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='companyorder',
            name='flag',
            field=models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='companyorder',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间'),
        ),
        migrations.AddField(
            model_name='companyorderitem',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='建立时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyorderitem',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='companyorderitem',
            name='flag',
            field=models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='companyorderitem',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间'),
        ),
        migrations.AddField(
            model_name='companyorderpayinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='建立时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyorderpayinfo',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='companyorderpayinfo',
            name='flag',
            field=models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='companyorderpayinfo',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='companyitem',
            name='company_pay_period',
            field=models.CharField(blank=True, choices=[('5', '年'), ('4', '季'), ('1', '日'), ('2', '周'), ('3', '月')], max_length=16, null=True, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='companyitem',
            name='companylist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('salon', None), ('yfy', '石家庄雅芳亚'), ('yiren', '北京伊人'), ('JMJ', '居明居')], max_length=19, null=True, verbose_name='适用公司'),
        ),
        migrations.AlterField(
            model_name='companyorderitem',
            name='company_pay_period',
            field=models.CharField(blank=True, choices=[('5', '年'), ('4', '季'), ('1', '日'), ('2', '周'), ('3', '月')], max_length=16, null=True, verbose_name='单位'),
        ),
    ]
