# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-05 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20200203_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyorderitem',
            name='companylist',
        ),
        migrations.AddField(
            model_name='companyitem',
            name='company_item_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='金额'),
        ),
        migrations.AddField(
            model_name='companyorder',
            name='order_company',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='订单公司'),
        ),
        migrations.AddField(
            model_name='companyorderitem',
            name='company_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.CompanyItem', verbose_name='订单项目'),
        ),
    ]
