# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-06 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20200205_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyorder',
            name='wx_prepay_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='微信预付订单号'),
        ),
        migrations.AddField(
            model_name='companyorder',
            name='wx_transaction_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='微信订单号'),
        ),
    ]
