# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-07 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20200206_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyorder',
            name='wx_prepay_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='微信预付订单号'),
        ),
    ]
