# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-09-03 22:14
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20200207_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyitem',
            name='storelist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05')], max_length=14, null=True, verbose_name='适用门店'),
        ),
        migrations.AlterField(
            model_name='companyorderitem',
            name='storelist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05')], max_length=14, null=True, verbose_name='续费门店'),
        ),
    ]
