# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-02-02 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_auto_20200903_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyorder',
            name='wechatuser',
        ),
        migrations.RemoveField(
            model_name='companyorderitem',
            name='company_item',
        ),
        migrations.RemoveField(
            model_name='companyorderitem',
            name='company_order',
        ),
        migrations.RemoveField(
            model_name='companyorderpayinfo',
            name='company_order',
        ),
        migrations.DeleteModel(
            name='CompanyItem',
        ),
        migrations.DeleteModel(
            name='CompanyOrder',
        ),
        migrations.DeleteModel(
            name='CompanyOrderItem',
        ),
        migrations.DeleteModel(
            name='CompanyOrderPayInfo',
        ),
    ]
