# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-03 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_cardpayout_cpayatout'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='transuuid',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
