# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-04 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_expense_transuuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='toll',
            name='transuuid',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
