# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-04 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0004_toll_transuuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='exptxserno',
            field=models.CharField(blank=True, db_column='EXPTXSERNO', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='toll',
            name='exptxserno',
            field=models.CharField(blank=True, db_column='EXPTXSERNO', max_length=40, null=True),
        ),
    ]
