# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-16 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0007_auto_20190216_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='transuuid',
        ),
        migrations.RemoveField(
            model_name='toll',
            name='transuuid',
        ),
    ]
