# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-14 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0014_auto_20190426_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardhistory',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='discic',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='discic',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='empldailydata',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='empldailydata',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='expvstoll',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='forfeit',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='forfeit',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='oldcardtonew',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='toll',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='toll',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
    ]
