# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-14 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0015_auto_20190514_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardhistory',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='discic',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='empldailydata',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='expvstoll',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='forfeit',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='oldcardtonew',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='toll',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
    ]
