# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-12 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0017_auto_20190602_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmplArchivementDetail',
            fields=[
                ('last_modified', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间')),
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('creater', models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者')),
                ('flag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除')),
                ('company', models.CharField(blank=True, default='yfy', editable=False, max_length=8, null=True, verbose_name='公司')),
                ('storecode', models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店')),
                ('exptxserno', models.CharField(blank=True, db_column='exptxserno', max_length=40, null=True)),
                ('ecode', models.CharField(blank=True, db_column='员工', max_length=16, null=True)),
                ('sale_archivement', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='销售业绩')),
                ('consume_archivement', models.DecimalField(blank=True, decimal_places=2, default=2, max_digits=16, null=True, verbose_name='消耗业绩')),
                ('trans', models.ForeignKey(blank=True, db_column='transuuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.Expvstoll', verbose_name='交易')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
