# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-02 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0018_emplarchivementdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empldailydata',
            name='empl',
            field=models.ForeignKey(blank=True, db_column='empl', null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Empl', verbose_name='员工'),
        ),
    ]
