# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-02 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0091_auto_20190902_2036'),
        ('cashier', '0019_auto_20190802_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldcardtonew',
            name='vipuuid',
            field=models.ForeignKey(blank=True, db_column='vipuuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Vip', verbose_name='客户唯一号'),
        ),
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together=set([('company', 'storecode', 'exptxserno', 'ditem')]),
        ),
        migrations.AlterUniqueTogether(
            name='toll',
            unique_together=set([('company', 'storecode', 'expvssvern', 'exptxserno')]),
        ),
    ]
