# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-11 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0024_earnestmoenylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cardratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='cashratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='otherratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='sendratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
