# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-15 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0026_auto_20191115_1434'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EarnestMoeny',
            new_name='EarnestMoney',
        ),
        migrations.AlterModelTable(
            name='earnestmoney',
            table='earnestmoney',
        ),
    ]
