# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-19 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0027_auto_20191115_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earnestmoney',
            old_name='hungsuuid',
            new_name='hunguuid',
        ),
    ]
