# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-20 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0028_auto_20191119_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earnestmoney',
            name='oweleftmoeny',
        ),
        migrations.RemoveField(
            model_name='earnestmoney',
            name='oweqty',
        ),
        migrations.RemoveField(
            model_name='earnestmoney',
            name='payedleftmeony',
        ),
        migrations.RemoveField(
            model_name='earnestmoney',
            name='payedqty',
        ),
    ]
