# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-20 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0029_auto_20191120_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnestmoney',
            name='itemcode',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='项目编号'),
        ),
        migrations.AlterField(
            model_name='earnestmoney',
            name='oweamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='欠款金额'),
        ),
        migrations.AlterField(
            model_name='earnestmoney',
            name='payedamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='已付金额'),
        ),
        migrations.AlterField(
            model_name='earnestmoney',
            name='planamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='计划支付金额'),
        ),
        migrations.AlterField(
            model_name='earnestmoney',
            name='planqty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='计划购买数量'),
        ),
        migrations.AlterField(
            model_name='earnestmoney',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='单价'),
        ),
    ]
