# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-25 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0030_auto_20191120_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='toll',
            name='ccode',
            field=models.CharField(blank=True, db_column='ccode', max_length=40, null=True),
        ),
    ]
