# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-30 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0031_toll_ccode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnestmoney',
            name='status',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='当前状态'),
        ),
        migrations.AlterField(
            model_name='expvstoll',
            name='oldcustflag',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
