# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-14 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0032_auto_20191130_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnestmoney',
            name='status',
            field=models.CharField(blank=True, choices=[('10', '定金开单')], max_length=8, null=True, verbose_name='当前状态'),
        ),
    ]
