# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-15 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0033_auto_20191214_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='ctype',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='项次类型'),
        ),
    ]
