# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-16 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0035_auto_20191221_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='sendamount',
        ),
    ]
