# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-09-08 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0040_auto_20200220_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardhistory',
            name='inamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='充值金额'),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='leftmoney',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='oriamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='outamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='消费金额'),
        ),
    ]
