# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-09-19 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0140_auto_20200919_2213'),
        ('adviser', '0038_auto_20200516_2330'),
        ('cashier', '0041_auto_20200908_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardhistory',
            name='cardinfouuid',
            field=models.ForeignKey(blank=True, db_column='cardinfouuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adviser.Cardinfo', verbose_name='卡号uuid'),
        ),
        migrations.AddField(
            model_name='cardhistory',
            name='cardtypeuuid',
            field=models.ForeignKey(blank=True, db_column='cardtypeuuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Cardtype', verbose_name='卡类'),
        ),
        migrations.AddField(
            model_name='cardhistory',
            name='comptype',
            field=models.CharField(blank=True, choices=[('amount', '计费'), ('times', '计次')], default='amount', max_length=8, null=True, verbose_name='消费模式'),
        ),
        migrations.AddField(
            model_name='cardhistory',
            name='suptype',
            field=models.CharField(blank=True, choices=[('20', '疗程卡'), ('40', '赠送疗程'), ('10', '储值卡'), ('30', '赠送储值'), ('14', '产品卡'), ('25', '月卡/季卡')], max_length=8, null=True, verbose_name='卡大类'),
        ),
        migrations.AddField(
            model_name='cardhistory',
            name='transuuid',
            field=models.ForeignKey(blank=True, db_column='transuuid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cashier.Expvstoll'),
        ),
        migrations.AddField(
            model_name='cardhistory',
            name='vipuuid',
            field=models.ForeignKey(blank=True, db_column='vipuuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Vip', verbose_name='客户唯一号'),
        ),
    ]
