# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-03-01 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0144_auto_20210301_2246'),
        ('cashier', '0042_auto_20200919_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipItemInfo',
            fields=[
                ('last_modified', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间')),
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('creater', models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者')),
                ('flag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除')),
                ('company', models.CharField(blank=True, default='yfy', editable=False, max_length=8, null=True, verbose_name='公司')),
                ('storecode', models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店')),
                ('vcode', models.CharField(blank=True, max_length=32, null=True, verbose_name='会员号')),
                ('ttype', models.CharField(blank=True, choices=[('G', '商品'), ('S', '服务'), ('C', '售卡'), ('I', '充值')], max_length=16, null=True, verbose_name='项目类型')),
                ('itemcode', models.CharField(blank=True, max_length=32, null=True, verbose_name='项目编号')),
                ('stype', models.CharField(blank=True, choices=[('正常', '正常'), ('赠送', '赠送')], max_length=8, null=True, verbose_name='是否赠送')),
                ('comptype', models.CharField(blank=True, choices=[('amount', '计费'), ('times', '计次')], max_length=8, null=True, verbose_name='计算方法')),
                ('leftqty', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='剩余数量')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='单价')),
                ('leftmoney', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='剩余金额')),
                ('valdate', models.DateTimeField(verbose_name='有效期')),
                ('status', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], max_length=8, null=True, verbose_name='状态')),
                ('valiflag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], max_length=8, null=True, verbose_name='是否有效')),
                ('description', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], max_length=128, null=True, verbose_name='备注')),
                ('goodsuuid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Goods', verbose_name='商品')),
                ('srvuuid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Serviece', verbose_name='服务项目')),
                ('vipuuid', models.ForeignKey(blank=True, db_column='vipuuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Vip', verbose_name='客人')),
            ],
            options={
                'verbose_name': '会员项目结存信息',
                'verbose_name_plural': '会员项目结存信息',
                'db_table': 'vipiteminfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VipItemTransDetail',
            fields=[
                ('last_modified', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间')),
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('creater', models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者')),
                ('flag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除')),
                ('company', models.CharField(blank=True, default='yfy', editable=False, max_length=8, null=True, verbose_name='公司')),
                ('storecode', models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店')),
                ('sukid', models.CharField(blank=True, max_length=32, null=True, verbose_name='系统单号')),
                ('transtype', models.CharField(blank=True, choices=[('G', '购入'), ('S', '服务'), ('ZT', '自提'), ('KD', '快递')], max_length=16, null=True, verbose_name='项目交易类型')),
                ('itemcode', models.CharField(blank=True, max_length=32, null=True, verbose_name='项目编号')),
                ('goodsvaldate', models.CharField(blank=True, max_length=8, null=True, verbose_name='商品有效期')),
                ('transqty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='交易数量')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='单价')),
                ('transamount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True, verbose_name='交易金额')),
                ('leftqty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='交易后数量')),
                ('leftamount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True, verbose_name='交易后金额')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述')),
                ('applycode', models.CharField(blank=True, max_length=16, null=True, verbose_name='申请员工')),
                ('vipitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.VipItemInfo', verbose_name='会员项目')),
            ],
            options={
                'verbose_name': '会员项目交易信息明细',
                'verbose_name_plural': '会员项目交易信息明细',
                'db_table': 'vipitemtransdetail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VipItemTransHead',
            fields=[
                ('last_modified', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间')),
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('creater', models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者')),
                ('flag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除')),
                ('company', models.CharField(blank=True, default='yfy', editable=False, max_length=8, null=True, verbose_name='公司')),
                ('storecode', models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店')),
                ('sukid', models.CharField(blank=True, max_length=32, null=True, verbose_name='系统单号')),
                ('outwhcode', models.CharField(blank=True, max_length=32, null=True, verbose_name='发货仓库')),
                ('doccode', models.CharField(blank=True, max_length=32, null=True, verbose_name='手工单号')),
                ('transdata', models.DateField(blank=True, null=True, verbose_name='申请日期')),
                ('transtype', models.CharField(blank=True, choices=[('G', '购入'), ('S', '服务'), ('ZT', '自提'), ('KD', '快递')], max_length=16, null=True, verbose_name='项目交易类型')),
                ('expresscompany', models.CharField(blank=True, max_length=16, null=True, verbose_name='快递公司')),
                ('expressdoccode', models.CharField(blank=True, max_length=24, null=True, verbose_name='快递单号')),
                ('expressdate', models.DateField(blank=True, null=True, verbose_name='快递日期')),
                ('applyecode', models.CharField(blank=True, max_length=16, null=True, verbose_name='申请人')),
                ('confirmecode', models.CharField(blank=True, max_length=16, null=True, verbose_name='发货人')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述')),
                ('status', models.CharField(blank=True, max_length=16, null=True, verbose_name='单号状态')),
                ('expressaddress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.VipAddress', verbose_name='快递地址')),
                ('vip', models.ForeignKey(blank=True, db_column='vipuuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Vip', verbose_name='客人')),
            ],
            options={
                'verbose_name': '会员项目交易信息',
                'verbose_name_plural': '会员项目交易信息',
                'db_table': 'vipitemtranshead',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VipItemTranslog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('creater', models.CharField(blank=True, default='anonymous', max_length=16, null=True, verbose_name='创建者')),
                ('flag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除')),
                ('company', models.CharField(blank=True, default='yfy', max_length=8, null=True, verbose_name='公司')),
                ('storecode', models.CharField(blank=True, max_length=16, null=True, verbose_name='门店')),
                ('vcode', models.CharField(blank=True, max_length=32, null=True, verbose_name='会员号')),
                ('ttype', models.CharField(blank=True, choices=[('G', '商品'), ('S', '服务'), ('C', '售卡'), ('I', '充值')], default='G', max_length=16, null=True, verbose_name='项目类型')),
                ('exptxserno', models.CharField(blank=True, max_length=32, null=True, verbose_name='购入交易流水号')),
                ('ditem', models.CharField(blank=True, max_length=8, null=True, verbose_name='项次')),
                ('itemcode', models.CharField(blank=True, max_length=32, null=True, verbose_name='项目编号')),
                ('stype', models.CharField(blank=True, choices=[('正常', '正常'), ('赠送', '赠送')], max_length=8, null=True, verbose_name='是否赠送')),
                ('comptype', models.CharField(blank=True, choices=[('amount', '计费'), ('times', '计次')], max_length=8, null=True, verbose_name='计算方法')),
                ('transqty', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='交易数量')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='单价')),
                ('transamount', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='金额')),
                ('status', models.CharField(blank=True, max_length=8, null=True, verbose_name='当前状态')),
                ('valifalg', models.CharField(blank=True, max_length=8, null=True, verbose_name='是否有效')),
                ('goodsuuid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Goods', verbose_name='商品')),
                ('srvuuid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Serviece', verbose_name='服务项目')),
            ],
            options={
                'verbose_name': '会员项目交易信息日志',
                'verbose_name_plural': '会员项目交易信息日志',
                'db_table': 'vipitemtranslog',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='company',
            field=models.CharField(blank=True, default='yfy', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='suptype',
            field=models.CharField(blank=True, choices=[('10', '储值卡'), ('20', '疗程卡'), ('30', '赠送储值卡'), ('15', '产品卡')], max_length=8, null=True, verbose_name='卡大类'),
        ),
        migrations.AlterField(
            model_name='discic',
            name='company',
            field=models.CharField(blank=True, default='yfy', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='earnestmoney',
            name='company',
            field=models.CharField(blank=True, default='yfy', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='emplarchivementdetail',
            name='company',
            field=models.CharField(blank=True, default='yfy', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='empldailydata',
            name='company',
            field=models.CharField(blank=True, default='yfy', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='company',
            field=models.CharField(blank=True, default='yfy', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='expvstoll',
            name='company',
            field=models.CharField(blank=True, default='yfy', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='forfeit',
            name='company',
            field=models.CharField(blank=True, default='yfy', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='oldcardtonew',
            name='company',
            field=models.CharField(blank=True, default='yfy', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='company',
            field=models.CharField(blank=True, default='yfy', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='company',
            field=models.CharField(blank=True, default='yfy', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='toll',
            name='company',
            field=models.CharField(blank=True, default='yfy', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='vipitemtranslog',
            name='transitemuuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashier.Expense', verbose_name='购入交易单'),
        ),
        migrations.AddField(
            model_name='vipitemtranslog',
            name='vip',
            field=models.ForeignKey(blank=True, db_column='vipuuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Vip', verbose_name='客人'),
        ),
        migrations.AddField(
            model_name='vipitemtranslog',
            name='vipitemtrans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashier.VipItemTransHead', verbose_name='提货交易单'),
        ),
        migrations.AddField(
            model_name='vipitemtransdetail',
            name='vipitemtrans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.VipItemTransHead', verbose_name='会员项目交易'),
        ),
    ]
