# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-03-04 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0043_auto_20210301_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vipiteminfo',
            old_name='vipuuid',
            new_name='vip',
        ),
        migrations.RenameField(
            model_name='vipitemtranslog',
            old_name='valifalg',
            new_name='valiflag',
        ),
    ]
