# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-03-04 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0044_auto_20210304_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipiteminfo',
            name='valdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='有效期'),
        ),
    ]
