# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-03-06 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0047_auto_20210304_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expvstoll',
            name='passedby',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='审核人'),
        ),
        migrations.AlterField(
            model_name='expvstoll',
            name='status',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='单据状态'),
        ),
        migrations.AlterField(
            model_name='vipiteminfo',
            name='goodsuuid',
            field=models.ForeignKey(blank=True, db_column='goodsuuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Goods', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='vipiteminfo',
            name='srvuuid',
            field=models.ForeignKey(blank=True, db_column='srvuuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Serviece', verbose_name='服务项目'),
        ),
        migrations.AlterField(
            model_name='vipitemtransdetail',
            name='vipitem',
            field=models.ForeignKey(blank=True, db_column='vipitemuuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.VipItemInfo', verbose_name='会员项目'),
        ),
        migrations.AlterField(
            model_name='vipitemtransdetail',
            name='vipitemtrans',
            field=models.ForeignKey(blank=True, db_column='vipitemtransuuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.VipItemTransHead', verbose_name='会员项目交易'),
        ),
        migrations.AlterField(
            model_name='vipitemtranshead',
            name='expressaddress',
            field=models.ForeignKey(blank=True, db_column='expressaddress', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.VipAddress', verbose_name='快递地址'),
        ),
        migrations.AlterField(
            model_name='vipitemtranslog',
            name='goodsuuid',
            field=models.ForeignKey(blank=True, db_column='goodsuuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Goods', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='vipitemtranslog',
            name='srvuuid',
            field=models.ForeignKey(blank=True, db_column='srvuuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Serviece', verbose_name='服务项目'),
        ),
        migrations.AlterField(
            model_name='vipitemtranslog',
            name='transitemuuid',
            field=models.ForeignKey(blank=True, db_column='expenseuuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashier.Expense', verbose_name='购入交易单'),
        ),
        migrations.AlterField(
            model_name='vipitemtranslog',
            name='vipitemtrans',
            field=models.ForeignKey(blank=True, db_column='vipitemtransuuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashier.VipItemTransHead', verbose_name='提货交易单'),
        ),
    ]
