# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-03-07 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0146_auto_20210306_2036'),
        ('cashier', '0048_auto_20210306_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipiteminfo',
            name='itemuuid',
            field=models.ForeignKey(blank=True, db_column='itemuuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Item', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='vipitemtransdetail',
            name='itemuuid',
            field=models.ForeignKey(blank=True, db_column='itemuuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Item', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='vipitemtranslog',
            name='itemuuid',
            field=models.ForeignKey(blank=True, db_column='itemuuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Item', verbose_name='项目'),
        ),
    ]
