# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-03-08 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0148_auto_20210308_2047'),
        ('cashier', '0050_auto_20210308_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='toll',
            name='bankaccount',
            field=models.ForeignKey(blank=True, db_column='bankaccount', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.BankAccount', verbose_name='银行账号'),
        ),
        migrations.AddField(
            model_name='toll',
            name='confirm_ecode',
            field=models.ForeignKey(blank=True, db_column='confirm_ecode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.Empl', verbose_name='财务确认人'),
        ),
    ]
