# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-03-23 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0053_auto_20210319_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipitemtranslog',
            name='leftqty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='剩余数量'),
        ),
        migrations.AddField(
            model_name='vipitemtranslog',
            name='transtype',
            field=models.CharField(blank=True, choices=[('G', '购入'), ('S', '服务'), ('ZT', '自提'), ('MAIL', '快递')], max_length=16, null=True, verbose_name='项目交易类型'),
        ),
        migrations.AddField(
            model_name='vipitemtranslog',
            name='vipiteminfo',
            field=models.ForeignKey(blank=True, db_column='vipiteminfouuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashier.VipItemInfo', verbose_name='会员项目'),
        ),
        migrations.AlterField(
            model_name='vipitemtransdetail',
            name='transtype',
            field=models.CharField(blank=True, choices=[('G', '购入'), ('S', '服务'), ('ZT', '自提'), ('MAIL', '快递')], max_length=16, null=True, verbose_name='项目交易类型'),
        ),
        migrations.AlterField(
            model_name='vipitemtranshead',
            name='transtype',
            field=models.CharField(blank=True, choices=[('G', '购入'), ('S', '服务'), ('ZT', '自提'), ('MAIL', '快递')], max_length=16, null=True, verbose_name='项目交易类型'),
        ),
    ]
