# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-03-23 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0054_auto_20210323_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vipitemtranslog',
            name='comptype',
        ),
        migrations.RemoveField(
            model_name='vipitemtranslog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vipitemtranslog',
            name='valiflag',
        ),
    ]
