# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-03-25 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0055_auto_20210323_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vipitemtransdetail',
            name='leftamount',
        ),
        migrations.RemoveField(
            model_name='vipitemtransdetail',
            name='leftqty',
        ),
        migrations.RemoveField(
            model_name='vipitemtransdetail',
            name='vipitem',
        ),
        migrations.RemoveField(
            model_name='vipitemtranslog',
            name='exptxserno',
        ),
        migrations.AddField(
            model_name='vipitemtransdetail',
            name='ditem',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='项次'),
        ),
        migrations.AddField(
            model_name='vipitemtransdetail',
            name='vipiteminfo',
            field=models.ForeignKey(blank=True, db_column='vipiteminfouuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.VipItemInfo', verbose_name='会员项目'),
        ),
        migrations.AddField(
            model_name='vipitemtranslog',
            name='sukid',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='系统流水号'),
        ),
    ]
