# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-03-28 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0056_auto_20210325_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipitemtranslog',
            name='transdate',
            field=models.DateField(blank=True, null=True, verbose_name='提货日期'),
        ),
    ]
