# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-03-30 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0057_vipitemtranslog_transdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='depositeflag',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='是否存院'),
        ),
    ]
