# Generated by Django 3.2.18 on 2026-05-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmj', '0023_auto_20191016_2112'),
    ]

    # operations = [
    #     migrations.AlterModelTable(
    #         name='olddata2',
    #         table='olddata2',
    #     ),
    # ]
