# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-10 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseinfo', '0007_auto_20181210_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=16, null=True, verbose_name='公司')),
                ('storecode', models.CharField(blank=True, max_length=16, null=True, verbose_name='门店')),
                ('gcode', models.CharField(blank=True, max_length=16, null=True, verbose_name='商品')),
                ('listflag', models.CharField(blank=True, default='Y', max_length=8, null=True, verbose_name='报表是否显示')),
                ('costprice', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='进价')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='售价')),
                ('iqty', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='当期进货数')),
                ('tiqty', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='转入数')),
                ('toqty', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='转出数')),
                ('thisperiodsalesqty', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='当期销售数')),
                ('thisperiodsalesamount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='当期销售金额')),
                ('totalsalesqty', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='当年累计销售数')),
                ('totalsalesamount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='当年累计销售金额')),
                ('goodsuuid', models.ForeignKey(blank=True, db_column='goodsuuid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.Goods', verbose_name='商品唯一码')),
            ],
            options={
                'verbose_name': '当期数据',
                'verbose_name_plural': '当期数据',
                'managed': True,
                'db_table': 'perioddata',
            },
        ),
        migrations.CreateModel(
            name='ReportPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportyear', models.CharField(blank=True, max_length=8, null=True, verbose_name='报表年份')),
                ('reportname', models.CharField(blank=True, max_length=16, null=True, verbose_name='报表名称')),
                ('period', models.CharField(blank=True, max_length=32, null=True, verbose_name='报表分期')),
                ('fromdate', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('todate', models.DateField(blank=True, null=True, verbose_name='介绍日期')),
            ],
            options={
                'verbose_name': '报表分期设置',
                'verbose_name_plural': '报表分期设置',
                'managed': True,
                'db_table': 'reportperiod',
            },
        ),
        migrations.AddField(
            model_name='perioddata',
            name='reportperiod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jmj.ReportPeriod', verbose_name='报表分期'),
        ),
    ]
