# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-11 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jmj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perioddata',
            name='storecode',
            field=models.ForeignKey(blank=True, db_column='storecode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.Storeinfo', verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='reportperiod',
            name='todate',
            field=models.DateField(blank=True, null=True, verbose_name='结束日期'),
        ),
    ]
