# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-14 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmj', '0002_auto_20181211_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='olddata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storecode', models.CharField(blank=True, max_length=8, null=True, verbose_name='店铺')),
                ('vsdate', models.CharField(blank=True, max_length=8, null=True, verbose_name='日期')),
                ('gcode', models.CharField(blank=True, max_length=16, null=True, verbose_name='商品')),
                ('salesqty', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='销售数量')),
                ('salesamount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='销售金额')),
            ],
            options={
                'verbose_name': '报表分期设置',
                'db_table': 'olddata',
                'verbose_name_plural': '报表分期设置',
                'managed': True,
            },
        ),
    ]
