# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-15 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmj', '0003_olddata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perioddata',
            name='goodsuuid',
        ),
    ]
