# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-16 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmj', '0008_perioddata_stockqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perioddata',
            name='salespercent',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True, verbose_name='销售进度'),
        ),
        migrations.AlterField(
            model_name='perioddata',
            name='stockqty',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True, verbose_name='库存数'),
        ),
    ]
