# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-16 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmj', '0010_auto_20181216_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportperiod',
            name='period',
            field=models.CharField(blank=True, choices=[('01', '01期'), ('02', '02期'), ('03', '03期'), ('04', '04期'), ('05', '05期'), ('06', '06期'), ('07', '07期'), ('08', '08期'), ('09', '09期'), ('10', '10期'), ('11', '11期'), ('12', '12期'), ('13', '13期'), ('14', '14期'), ('15', '15期'), ('16', '16期'), ('17', '17期'), ('18', '18期'), ('19', '19期'), ('20', '20期'), ('21', '21期'), ('22', '22期'), ('23', '23期'), ('24', '24期'), ('25', '25期'), ('26', '26期'), ('27', '27期'), ('28', '28期'), ('29', '29期'), ('30', '30期')], max_length=16, null=True, verbose_name='分期'),
        ),
        migrations.AlterField(
            model_name='reportperiod',
            name='perioddesc',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='分期名称'),
        ),
    ]
