# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-16 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmj', '0011_auto_20181216_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='perioddata',
            name='rptcode2',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='分类2'),
        ),
        migrations.AddField(
            model_name='perioddata',
            name='rptcode3',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='功能'),
        ),
    ]
