# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-17 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmj', '0012_auto_20181216_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='GcodeMirror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcode', models.CharField(blank=True, max_length=16, null=True, verbose_name='系统商品编号')),
                ('gname', models.CharField(blank=True, max_length=32, null=True, verbose_name='商品名称')),
                ('gcode2018', models.CharField(blank=True, max_length=16, null=True, verbose_name='2018年对应编号')),
                ('gcode2017', models.CharField(blank=True, max_length=16, null=True, verbose_name='2017年对应编号')),
                ('gcode2016', models.CharField(blank=True, max_length=16, null=True, verbose_name='2016年对应编号')),
                ('gcode2015', models.CharField(blank=True, max_length=16, null=True, verbose_name='2015年对应编号')),
                ('gcode2014', models.CharField(blank=True, max_length=16, null=True, verbose_name='2014年对应编号')),
                ('gcode2013', models.CharField(blank=True, max_length=16, null=True, verbose_name='2013年对应编号')),
                ('gcode2012', models.CharField(blank=True, max_length=16, null=True, verbose_name='2012年对应编号')),
                ('gcode2011', models.CharField(blank=True, max_length=16, null=True, verbose_name='2011年对应编号')),
                ('gcode2010', models.CharField(blank=True, max_length=16, null=True, verbose_name='2010年对应编号')),
                ('gcode2009', models.CharField(blank=True, max_length=16, null=True, verbose_name='2009年对应编号')),
                ('gcode2008', models.CharField(blank=True, max_length=16, null=True, verbose_name='2008年对应编号')),
                ('gcode2007', models.CharField(blank=True, max_length=16, null=True, verbose_name='2007年对应编号')),
                ('gcode2006', models.CharField(blank=True, max_length=16, null=True, verbose_name='2006年对应编号')),
                ('gcode2005', models.CharField(blank=True, max_length=16, null=True, verbose_name='2005年对应编号')),
            ],
            options={
                'db_table': 'GcodeMirror',
                'verbose_name': '商品编码对照表',
                'managed': True,
                'verbose_name_plural': '商品编码对照表',
            },
        ),
    ]
