# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-27 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmj', '0016_olddata2'),
    ]

    operations = [
        migrations.AddField(
            model_name='perioddata',
            name='rativesalesqtypercent',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True, verbose_name='相关销售数量占比'),
        ),
        migrations.AddField(
            model_name='perioddata',
            name='retiveiqtypercent',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True, verbose_name='相关进货占比'),
        ),
    ]
