# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-27 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmj', '0017_auto_20181227_1158'),
    ]

    operations = [
        # migrations.AlterModelTable(
        #     name='olddata2',
        #     table='olddata4',
        # ),
    ]
