# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-02 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmj', '0018_auto_20181227_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='perioddata',
            name='orderqty',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True, verbose_name='订货未到货数'),
        ),
    ]
