# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-02 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmj', '0020_auto_20190505_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olddata',
            name='storecode',
            field=models.CharField(blank=True, choices=[('000', '总部'), ('001', '杭州大厦店'), ('002', '万象城店')], max_length=8, null=True, verbose_name='店铺'),
        ),
        migrations.AlterField(
            model_name='olddata2',
            name='storecode',
            field=models.CharField(blank=True, choices=[('000', '总部'), ('001', '杭州大厦店'), ('002', '万象城店')], max_length=8, null=True, verbose_name='店铺'),
        ),
        migrations.AlterField(
            model_name='olddata4',
            name='storecode',
            field=models.CharField(blank=True, choices=[('000', '总部'), ('001', '杭州大厦店'), ('002', '万象城店')], max_length=8, null=True, verbose_name='店铺'),
        ),
        migrations.AlterModelTable(
            name='olddata2',
            table='olddata4',
        ),
    ]
