# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-08 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensehung',
            name='hunguuid',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
