# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-24 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0006_auto_20190324_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingevent',
            name='vcode',
        ),
        migrations.RemoveField(
            model_name='bookingevent',
            name='vname',
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='bookingendtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='bookingstartdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='bookingstarttime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='instrumentid',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='roomid',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
