# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-24 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0008_auto_20190324_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingevent',
            name='qrcode',
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='billingendtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='callcleantime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='canceltime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='cleanendtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='cleanstarttime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='comeintime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='confirmempl',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='confirmtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='emplendtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='emplstarttime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='instrumentbookingendtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='instrumentbookingstarttime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='instrumentendtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='instrumentstarttime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='kaidanlasttime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='leavetime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='peiliaoconfirmtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='peiliaolasttime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='pregoodsendtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='roomendtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='roomstarttime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='vipconfirmtime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
