# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-25 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0009_auto_20190324_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardinfo',
            old_name='cardtypuuid',
            new_name='cardtypeuuid',
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='vipuuid',
            field=models.ForeignKey(blank=True, db_column='vipuuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vip', to='baseinfo.Vip', verbose_name='客户唯一号'),
        ),
    ]
