# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-10 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0010_auto_20190325_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expvstollhung',
            name='enddate_hung',
        ),
        migrations.RemoveField(
            model_name='expvstollhung',
            name='endtime_hung',
        ),
        migrations.RemoveField(
            model_name='expvstollhung',
            name='startdate_hung',
        ),
        migrations.RemoveField(
            model_name='expvstollhung',
            name='starttime_hung',
        ),
        migrations.RemoveField(
            model_name='expvstollhung',
            name='totalmins_hung',
        ),
        migrations.RemoveField(
            model_name='expvstollhung',
            name='ttype1',
        ),
        migrations.AddField(
            model_name='instrument',
            name='instrumentid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='billingendtime',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='bookingendtime',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='bookingstarttime',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='callcleantime',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='canceltime',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='cleanendtime',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='cleanstarttime',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='comeintime',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='emplendtime',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='emplstarttime',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='instrumentbookingstarttime',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='instrumentendtime',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='instrumentstarttime',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='kaidanlasttime',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='leavetime',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='peiliaoconfirmtime',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='peiliaolasttime',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='pregoodsendtime',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='roomendtime',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='roomstarttime',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='vipconfirmtime',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='cardtypeuuid',
            field=models.ForeignKey(blank=True, db_column='cardtypeuuid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardtypeuuid', to='baseinfo.Cardtype', verbose_name='卡类'),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='leftqty',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expvstollhung',
            name='mondisc_hung',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='expvstollhung',
            name='sumdisc_hung',
            field=models.DecimalField(blank=True, decimal_places=5, default=1, max_digits=6, null=True),
        ),
    ]
