# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-10 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0011_auto_20190410_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingevent',
            name='company',
        ),
        migrations.RemoveField(
            model_name='bookingevent',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='bookingevent',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='bookingevent',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='bookingevent',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='bookingevent',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='instrumentid',
        ),
        migrations.AddField(
            model_name='bookingevent',
            name='bookingeventid',
            field=models.BigAutoField( primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
