# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-10 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0012_auto_20190410_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='instrumentid',
            field=models.IntegerField(default=0),
        ),
    ]
