# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-10 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0013_instrument_instrumentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingevent',
            name='bookingstartdate',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
