# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-10 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0014_auto_20190410_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingevent',
            name='uuid',
            field=models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='bookingflag',
            field=models.CharField(blank=True, default='Y', max_length=8, null=True),
        ),
    ]
