# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-12 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0015_auto_20190410_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingevent',
            name='uuid',
            field=models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
