# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-14 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0019_auto_20190514_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardblacklist',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='emplschedule',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='expensehung',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='expvstollhung',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='room',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='vipinfogroup1',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
    ]
