# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-12 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0021_auto_20190602_1926'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cardinfo',
            index=models.Index(fields=['company', 'storecode', 'ccode'], name='company_store_ccode_idx'),
        ),
    ]
