# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-24 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0077_auto_20190724_1047'),
        ('adviser', '0022_auto_20190712_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('last_modified', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间')),
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('creater', models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者')),
                ('flag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除')),
                ('company', models.CharField(blank=True, default='yfy', editable=False, max_length=8, null=True, verbose_name='公司')),
                ('storecode', models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店')),
                ('vcode', models.CharField(blank=True, db_column='vcode', max_length=32, null=True, verbose_name='会员号')),
                ('payccode', models.CharField(blank=True, db_column='ccode', max_length=32, null=True, verbose_name='付款卡卡号')),
                ('vsdate', models.CharField(blank=True, db_column='vsdate', max_length=8, null=True, verbose_name='日期')),
                ('ttype', models.CharField(db_column='ttype', max_length=8, verbose_name='交易类别')),
                ('stype', models.CharField(blank=True, db_column='stype', default='N', max_length=8, null=True, verbose_name='是否赠送')),
                ('itemcode', models.CharField(blank=True, db_column='itemcode', max_length=32, null=True, verbose_name='项目编号')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='原价')),
                ('secdisc', models.DecimalField(blank=True, decimal_places=4, default=1, max_digits=8, null=True, verbose_name='折扣')),
                ('mondisc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='免单金额')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='实收金额')),
                ('pmcode', models.CharField(blank=True, max_length=16, null=True, verbose_name='顾问')),
                ('seccode', models.CharField(blank=True, max_length=16, null=True, verbose_name='美疗师')),
                ('thrcode', models.CharField(blank=True, max_length=16, null=True, verbose_name='美疗师')),
                ('pmratio', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='顾问拆分比例')),
                ('secratio', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='美容师拆分比例')),
                ('thrratio', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='美容师拆分比例')),
                ('promotionsid', models.CharField(blank=True, default='0', max_length=32, null=True, verbose_name='活动编号')),
                ('valiflag', models.CharField(blank=True, default='Y', max_length=8, null=True, verbose_name='是否有效')),
                ('vipuuid', models.ForeignKey(blank=True, db_column='vipuuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Vip', verbose_name='客户唯一号')),
            ],
            options={
                'db_table': 'shoppingcart',
                'verbose_name_plural': '购物车',
                'managed': True,
                'verbose_name': '购物车',
            },
        ),
    ]
