# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-24 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0024_shoppingcart_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='itemname',
            field=models.CharField(blank=True, db_column='itemname', max_length=128, null=True, verbose_name='名称'),
        ),
    ]
