# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-28 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0025_shoppingcart_itemname'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='status',
            field=models.CharField(blank=True, default='10', max_length=8, null=True, verbose_name='当期状态'),
        ),
    ]
