# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-10 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0027_auto_20190810_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipinfogroup1',
            name='storecode',
            field=models.CharField(blank=True, db_column='StoreCode', default='0', max_length=16, verbose_name='店铺编号'),
        ),
    ]
