# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-11 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0028_auto_20190810_2126'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='cardblacklist',
        #     name='company',
        #     field=models.CharField(blank=True, default='yiren', editable=False, max_length=8, null=True, verbose_name='公司'),
        # ),
        # migrations.AlterField(
        #     model_name='cardinfo',
        #     name='company',
        #     field=models.CharField(blank=True, default='yiren', editable=False, max_length=8, null=True, verbose_name='公司'),
        # ),
        migrations.AlterField(
            model_name='cardinfo',
            name='issuedate',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='销售日期'),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='opendate',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='开始使用日期'),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='valdate',
            field=models.CharField(blank=True, db_column='VALDATE', max_length=8, null=True, verbose_name='有效期截止日期'),
        ),
        migrations.AlterField(
            model_name='emplschedule',
            name='company',
            field=models.CharField(blank=True, default='yiren', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='expensehung',
            name='company',
            field=models.CharField(blank=True, default='yiren', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='expvstollhung',
            name='company',
            field=models.CharField(blank=True, default='yiren', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='company',
            field=models.CharField(blank=True, default='yiren', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='room',
            name='company',
            field=models.CharField(blank=True, default='yiren', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='company',
            field=models.CharField(blank=True, default='yiren', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='vipinfogroup1',
            name='company',
            field=models.CharField(blank=True, default='yiren', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterUniqueTogether(
            name='emplschedule',
            unique_together=set([('company', 'storecode', 'vsdate', 'ecode'),]),
        ),
    ]
