# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-19 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0033_auto_20191119_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='playqty',
            new_name='planqty',
        ),
    ]
