# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-20 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0034_auto_20191119_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='planqty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='预订数量'),
        ),
    ]
