# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-03-30 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0042_auto_20210319_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expvstollhung',
            name='cardtype_hung',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='expvstollhung',
            name='cashposition_hung',
            field=models.CharField(blank=True, max_length=168, null=True),
        ),
        migrations.AlterField(
            model_name='expvstollhung',
            name='ecode_hung',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='expvstollhung',
            name='goodssaletype_hung',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='expvstollhung',
            name='storecode_hung',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='expvstollhung',
            name='vipcode',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
