# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-18 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyItemClass1Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=16, null=True, verbose_name='公司')),
                ('stoorecode', models.CharField(blank=True, max_length=16, null=True, verbose_name='门店')),
                ('financeyear', models.CharField(blank=True, max_length=8, null=True, verbose_name='财年')),
                ('financemonth', models.CharField(blank=True, max_length=8, null=True, verbose_name='财月')),
                ('financedate', models.CharField(blank=True, max_length=8, null=True, verbose_name='记账日期')),
                ('itemclass1', models.CharField(blank=True, choices=[('10', '拓客项目'), ('20', '留客项目'), ('30', '升客项目'), ('40', '挖客项目'), ('50', '深挖项目')], max_length=16, null=True, verbose_name='项目分类1')),
                ('itemqty', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=16, null=True, verbose_name='数量')),
                ('itemamount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='金额')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyItemClass2Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=16, null=True, verbose_name='公司')),
                ('stoorecode', models.CharField(blank=True, max_length=16, null=True, verbose_name='门店')),
                ('financeyear', models.CharField(blank=True, max_length=8, null=True, verbose_name='财年')),
                ('financemonth', models.CharField(blank=True, max_length=8, null=True, verbose_name='财月')),
                ('financedate', models.CharField(blank=True, max_length=8, null=True, verbose_name='记账日期')),
                ('itemclass2', models.CharField(blank=True, choices=[('10', '基础项目'), ('20', '大项目'), ('30', '循环类项目'), ('40', '其他')], max_length=16, null=True, verbose_name='项目分类2')),
                ('itemqty', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=16, null=True, verbose_name='数量')),
                ('itemamount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='金额')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyItemClass3Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=16, null=True, verbose_name='公司')),
                ('stoorecode', models.CharField(blank=True, max_length=16, null=True, verbose_name='门店')),
                ('financeyear', models.CharField(blank=True, max_length=8, null=True, verbose_name='财年')),
                ('financemonth', models.CharField(blank=True, max_length=8, null=True, verbose_name='财月')),
                ('financedate', models.CharField(blank=True, max_length=8, null=True, verbose_name='记账日期')),
                ('itemclass1', models.CharField(blank=True, choices=[('10', '无差别类项目'), ('20', '必备类项目'), ('30', '一维类项目'), ('40', '魅力类项目')], max_length=16, null=True, verbose_name='项目分类3')),
                ('itemqty', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=16, null=True, verbose_name='数量')),
                ('itemamount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='金额')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyItemClass4Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=16, null=True, verbose_name='公司')),
                ('stoorecode', models.CharField(blank=True, max_length=16, null=True, verbose_name='门店')),
                ('financeyear', models.CharField(blank=True, max_length=8, null=True, verbose_name='财年')),
                ('financemonth', models.CharField(blank=True, max_length=8, null=True, verbose_name='财月')),
                ('financedate', models.CharField(blank=True, max_length=8, null=True, verbose_name='记账日期')),
                ('itemclass1', models.CharField(blank=True, choices=[('', ''), ('', '')], max_length=16, null=True, verbose_name='项目分类4')),
                ('itemqty', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=16, null=True, verbose_name='数量')),
                ('itemamount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='金额')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyReportNo1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=16, null=True, verbose_name='公司')),
                ('stoorecode', models.CharField(blank=True, max_length=16, null=True, verbose_name='门店')),
                ('financeyear', models.CharField(blank=True, max_length=8, null=True, verbose_name='财年')),
                ('financemonth', models.CharField(blank=True, max_length=8, null=True, verbose_name='财月')),
                ('financedate', models.CharField(blank=True, max_length=8, null=True, verbose_name='记账日期')),
                ('vipcnt', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='到店客数')),
                ('newvipcnt', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='新客数')),
                ('newvipwithcardcnt', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='新客入会数')),
                ('vipcnt_s', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='服务客数')),
                ('vipcnt_g', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='商品客数')),
                ('vipcnt_c', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='购卡客数')),
                ('vipcnt_i', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='充值客数')),
                ('shouru_samount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='服务收入')),
                ('shouru_gamount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='商品收入')),
                ('shouru_camount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='卡收入')),
                ('shihao_samount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='服务实耗')),
                ('shihao_gamount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='商品实耗')),
                ('xianjin_samount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='服务现金')),
                ('xianjin_gamount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='商品现金')),
                ('xianjin_camount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='卡现金')),
            ],
            options={
                'managed': True,
                'db_table': 'dailyreportno1',
                'verbose_name': '1号日报表',
                'verbose_name_plural': '1号日报表',
            },
        ),
    ]
