# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-18 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyitemclass1report',
            name='itemclass1',
            field=models.CharField(blank=True, choices=[('10', '拓客项目'), ('20', '留客项目'), ('30', '升客项目'), ('40', '挖客项目'), ('50', '深挖项目'), ('90', '其他')], max_length=16, null=True, verbose_name='项目分类1'),
        ),
        migrations.AlterField(
            model_name='dailyitemclass2report',
            name='itemclass2',
            field=models.CharField(blank=True, choices=[('10', '拓客项目'), ('20', '留客项目'), ('30', '升客项目'), ('40', '挖客项目'), ('50', '深挖项目'), ('90', '其他')], max_length=16, null=True, verbose_name='项目分类2'),
        ),
        migrations.AlterField(
            model_name='dailyitemclass3report',
            name='itemclass1',
            field=models.CharField(blank=True, choices=[('10', '拓客项目'), ('20', '留客项目'), ('30', '升客项目'), ('40', '挖客项目'), ('50', '深挖项目'), ('90', '其他')], max_length=16, null=True, verbose_name='项目分类3'),
        ),
    ]
