# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-19 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20190218_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMarketClass1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=16, null=True, verbose_name='公司')),
                ('stoorecode', models.CharField(blank=True, max_length=16, null=True, verbose_name='门店')),
                ('financeyear', models.CharField(blank=True, max_length=8, null=True, verbose_name='财年')),
                ('financemonth', models.CharField(blank=True, max_length=8, null=True, verbose_name='财月')),
                ('financedate', models.CharField(blank=True, max_length=8, null=True, verbose_name='记账日期')),
                ('itemclass1', models.CharField(blank=True, choices=[('10', '拓客项目'), ('20', '留客项目'), ('30', '升客项目'), ('40', '挖客项目'), ('50', '深挖项目'), ('90', '其他')], max_length=16, null=True, verbose_name='营销分类1')),
                ('vipcnt', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=16, null=True, verbose_name='人数')),
                ('itemqty', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=16, null=True, verbose_name='数量')),
                ('itemamount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='金额')),
            ],
            options={
                'verbose_name_plural': '项目管理2号报表',
                'verbose_name': '项目管理1号报表',
                'db_table': 'dailymarketclass1',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='DailyItemClass1Report',
        ),
        migrations.AddField(
            model_name='dailyitemclass2report',
            name='vipcnt',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=16, null=True, verbose_name='人数'),
        ),
    ]
