# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-19 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20190219_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyitemclass2report',
            old_name='stoorecode',
            new_name='storecode',
        ),
        migrations.RenameField(
            model_name='dailyitemclass3report',
            old_name='stoorecode',
            new_name='storecode',
        ),
        migrations.RenameField(
            model_name='dailyitemclass4report',
            old_name='stoorecode',
            new_name='storecode',
        ),
        migrations.RenameField(
            model_name='dailymarketclass1',
            old_name='stoorecode',
            new_name='storecode',
        ),
        migrations.RenameField(
            model_name='dailyreportno1',
            old_name='stoorecode',
            new_name='storecode',
        ),
    ]
