# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-11 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20190514_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyitemclass2report',
            name='itemclass2',
            field=models.CharField(blank=True, choices=[('1001', '拓客项目'), ('1002', '留客项目'), ('1003', '升客项目'), ('1004', '挖客项目'), ('1090', '其他')], max_length=16, null=True, verbose_name='项目分类2'),
        ),
        migrations.AlterField(
            model_name='dailyitemclass3report',
            name='itemclass1',
            field=models.CharField(blank=True, choices=[('1001', '拓客项目'), ('1002', '留客项目'), ('1003', '升客项目'), ('1004', '挖客项目'), ('1090', '其他')], max_length=16, null=True, verbose_name='项目分类3'),
        ),
        migrations.AlterField(
            model_name='dailymarketclass1',
            name='itemclass1',
            field=models.CharField(blank=True, choices=[('1001', '拓客项目'), ('1002', '留客项目'), ('1003', '升客项目'), ('1004', '挖客项目'), ('1090', '其他')], max_length=16, null=True, verbose_name='营销分类1'),
        ),
    ]
