# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-21 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0105_auto_20191012_2341'),
        ('report', '0006_auto_20190911_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportVip',
            fields=[
                ('last_modified', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间')),
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('creater', models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者')),
                ('flag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除')),
                ('company', models.CharField(blank=True, default='yfy', editable=False, max_length=8, null=True, verbose_name='公司')),
                ('storecode', models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店')),
                ('vsdate', models.DateField(auto_now=True, null=True, verbose_name='日期')),
                ('newvipflag', models.CharField(blank=True, max_length=8, null=True, verbose_name='是否新客')),
                ('friendqty', models.IntegerField(blank=True, default=0, null=True, verbose_name='同行朋友数量')),
                ('friendsuuid', models.CharField(blank=True, max_length=32, null=True, verbose_name='同行朋友')),
                ('vipuuid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Vip', verbose_name='会员')),
            ],
            options={
                'verbose_name': '会员到店数量报表',
                'verbose_name_plural': '会员到店数量报表',
                'db_table': 'dailyreportvip',
                'managed': True,
            },
        ),
    ]
