# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-21 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_dailyreportvip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportvip',
            name='vsdate',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='日期'),
        ),
    ]
