# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-21 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20191021_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreportvip',
            name='vipqty',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='客户数量'),
        ),
    ]
