# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-14 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_dailyreportvip_vipqty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyitemclass2report',
            name='financedate',
        ),
        migrations.RemoveField(
            model_name='dailyitemclass2report',
            name='financemonth',
        ),
        migrations.RemoveField(
            model_name='dailyitemclass2report',
            name='financeyear',
        ),
        migrations.RemoveField(
            model_name='dailyitemclass3report',
            name='financedate',
        ),
        migrations.RemoveField(
            model_name='dailyitemclass3report',
            name='financemonth',
        ),
        migrations.RemoveField(
            model_name='dailyitemclass3report',
            name='financeyear',
        ),
        migrations.RemoveField(
            model_name='dailyitemclass4report',
            name='financedate',
        ),
        migrations.RemoveField(
            model_name='dailyitemclass4report',
            name='financemonth',
        ),
        migrations.RemoveField(
            model_name='dailyitemclass4report',
            name='financeyear',
        ),
        migrations.RemoveField(
            model_name='dailymarketclass1',
            name='financedate',
        ),
        migrations.RemoveField(
            model_name='dailymarketclass1',
            name='financemonth',
        ),
        migrations.RemoveField(
            model_name='dailymarketclass1',
            name='financeyear',
        ),
        migrations.RemoveField(
            model_name='dailyreportno1',
            name='financedate',
        ),
        migrations.RemoveField(
            model_name='dailyreportno1',
            name='financemonth',
        ),
        migrations.RemoveField(
            model_name='dailyreportno1',
            name='financeyear',
        ),
        migrations.AddField(
            model_name='dailyitemclass2report',
            name='reportdate',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='日期'),
        ),
        migrations.AddField(
            model_name='dailyitemclass2report',
            name='reportmonth',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='月'),
        ),
        migrations.AddField(
            model_name='dailyitemclass2report',
            name='reportyear',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='年'),
        ),
        migrations.AddField(
            model_name='dailyitemclass3report',
            name='reportdate',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='日期'),
        ),
        migrations.AddField(
            model_name='dailyitemclass3report',
            name='reportmonth',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='月'),
        ),
        migrations.AddField(
            model_name='dailyitemclass3report',
            name='reportyear',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='年'),
        ),
        migrations.AddField(
            model_name='dailyitemclass4report',
            name='reportdate',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='日期'),
        ),
        migrations.AddField(
            model_name='dailyitemclass4report',
            name='reportmonth',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='月'),
        ),
        migrations.AddField(
            model_name='dailyitemclass4report',
            name='reportyear',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='年'),
        ),
        migrations.AddField(
            model_name='dailymarketclass1',
            name='reportdate',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='日期'),
        ),
        migrations.AddField(
            model_name='dailymarketclass1',
            name='reportmonth',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='月'),
        ),
        migrations.AddField(
            model_name='dailymarketclass1',
            name='reportyear',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='年'),
        ),
        migrations.AddField(
            model_name='dailyreportno1',
            name='reportdate',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='日期'),
        ),
        migrations.AddField(
            model_name='dailyreportno1',
            name='reportmonth',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='月'),
        ),
        migrations.AddField(
            model_name='dailyreportno1',
            name='reportyear',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='年'),
        ),
    ]
