# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-14 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0116_auto_20191214_2205'),
        ('report', '0011_auto_20191214_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassReportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=16, null=True, verbose_name='公司')),
                ('storecode', models.CharField(blank=True, max_length=16, null=True, verbose_name='门店')),
                ('reportyear', models.CharField(blank=True, max_length=8, null=True, verbose_name='年')),
                ('reportmonth', models.CharField(blank=True, max_length=8, null=True, verbose_name='月')),
                ('reportdate', models.CharField(blank=True, max_length=8, null=True, verbose_name='日期')),
                ('datarang', models.CharField(blank=True, max_length=16, null=True, verbose_name='数据类型')),
                ('classtype', models.CharField(blank=True, max_length=16, null=True, verbose_name='分类')),
                ('classcode', models.CharField(blank=True, max_length=16, null=True, verbose_name='分类')),
                ('itemqty', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=16, null=True, verbose_name='数量')),
                ('itemamount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='金额')),
                ('storeuuid', models.ForeignKey(blank=True, db_column='storeuuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Storeinfo', verbose_name='店铺')),
            ],
            options={
                'db_table': 'classreportdata',
                'verbose_name': '每日数据',
                'verbose_name_plural': '每日数据',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='DailyItemClass2Report',
        ),
        migrations.DeleteModel(
            name='DailyItemClass3Report',
        ),
        migrations.DeleteModel(
            name='DailyItemClass4Report',
        ),
        migrations.DeleteModel(
            name='DailyMarketClass1',
        ),
        migrations.RemoveField(
            model_name='dailyreportno1',
            name='xianjin_camount',
        ),
        migrations.RemoveField(
            model_name='dailyreportno1',
            name='xianjin_gamount',
        ),
        migrations.RemoveField(
            model_name='dailyreportno1',
            name='xianjin_samount',
        ),
        migrations.AddField(
            model_name='dailyreportno1',
            name='card_camount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='卡付售卡/充值'),
        ),
        migrations.AddField(
            model_name='dailyreportno1',
            name='card_gamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='卡付商品'),
        ),
        migrations.AddField(
            model_name='dailyreportno1',
            name='card_samount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='卡付服务'),
        ),
        migrations.AddField(
            model_name='dailyreportno1',
            name='cash_camount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='现金售卡/充值'),
        ),
        migrations.AddField(
            model_name='dailyreportno1',
            name='cash_gamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='现金商品'),
        ),
        migrations.AddField(
            model_name='dailyreportno1',
            name='cash_samount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='现金服务'),
        ),
        migrations.AddField(
            model_name='dailyreportno1',
            name='newvipamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='新客现金'),
        ),
        migrations.AddField(
            model_name='dailyreportno1',
            name='send_camount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='赠送售卡/充值'),
        ),
        migrations.AddField(
            model_name='dailyreportno1',
            name='send_gamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='赠送商品'),
        ),
        migrations.AddField(
            model_name='dailyreportno1',
            name='send_samount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='赠送服务'),
        ),
        migrations.AddField(
            model_name='dailyreportno1',
            name='storeuuid',
            field=models.ForeignKey(blank=True, db_column='storeuuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Storeinfo', verbose_name='店铺'),
        ),
    ]
