# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-15 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_report_item_ruler_reportclassdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportitem',
            name='report_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.Report', verbose_name='报表'),
        ),
    ]
