# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-21 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_auto_20191216_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportvip',
            name='company',
            field=models.CharField(blank=True, default='yiren', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='report',
            name='company',
            field=models.CharField(blank=True, default='yiren', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='report_item_ruler',
            name='company',
            field=models.CharField(blank=True, default='yiren', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='reportclassdata',
            name='report_class_type',
            field=models.CharField(blank=True, choices=[('80', '储值卡'), ('40', '懒虫美睫'), ('50', '无妆感丰眉'), ('C', 'C:合作项目'), ('C', 'C:瘦狗项目'), ('B', 'B:金牛项目'), ('60', '造型'), ('A', 'A:基础项目'), ('15', '面部单加'), ('D', 'D:医美'), ('100', '店内项目'), ('D', 'D:问题项目'), ('60', '无妆感厘睫'), ('70', '懒虫美发'), ('106', '12C'), ('110', 'Amala雅蔓兰'), ('108', '奥丽肤'), ('196', '彩护'), ('124', '戴安娜/凝肌'), ('131', '蒂克'), ('154', '店内消耗品'), ('163', '丁航尧'), ('203', '法儿曼'), ('212', '芳疗个性方案'), ('193', '富丽活'), ('137', '谷胱甘肽'), ('117', '光学'), ('133', '肌肤丽琦 GEMOLOGY'), ('189', '基纳'), ('128', '吉备'), ('109', '珈纳'), ('218', '酒水'), ('198', '抗旨君'), ('147', '懒虫'), ('207', '礼品'), ('164', '李泽晨'), ('209', '罗正杰'), ('138', '美齿口'), ('210', '美芾美源'), ('200', '普洱茶'), ('105', '其他'), ('111', '瑞妍'), ('215', '诗泽'), ('195', '市场采购'), ('202', '水岸渔歌'), ('179', '丝维诗兰 swiss line'), ('123', '托尼盖'), ('197', '托宁'), ('190', '外包项目'), ('129', '晓酵素'), ('145', '胸部'), ('127', '药拓'), ('183', '仪器辅料'), ('126', '雍卡'), ('181', '云南特色'), ('216', '资生堂'), ('107', '自研品牌'), ('10', '面部全套'), ('90', '其它'), ('15', '面部单加项'), ('B', 'B:大项目'), ('30', '懒虫美甲'), ('82', '疗程卡'), ('500', '外包'), ('20', '身体全套'), ('A', 'A:明星项目'), ('10', '面部'), ('83', '时效卡'), ('81', '产品卡'), ('20', '身体'), ('25', '身体单加项')], max_length=32, null=True, verbose_name='分类'),
        ),
    ]
