# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-11-07 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0141_auto_20201107_2133'),
        ('report', '0022_auto_20200919_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReportNo1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=16, null=True, verbose_name='公司')),
                ('storecode', models.CharField(blank=True, max_length=16, null=True, verbose_name='门店')),
                ('reportyear', models.CharField(blank=True, max_length=8, null=True, verbose_name='年')),
                ('reportmonth', models.CharField(blank=True, max_length=8, null=True, verbose_name='月')),
                ('initial_leftmoney', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='期初卡余额')),
                ('cashpay_c', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='本期入卡先进')),
                ('cashpay_s', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='本期现金服务')),
                ('cashpay_g', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='本期现金商品')),
                ('cardpay_s', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='本期卡付服务')),
                ('cardpay_g', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='本期卡付商品')),
                ('last_leftmoney', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='本期卡付服务')),
                ('storeuuid', models.ForeignKey(blank=True, db_column='storeuuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Storeinfo', verbose_name='店铺')),
            ],
            options={
                'db_table': 'monthlyreportno1',
                'verbose_name': '月度报表一',
                'managed': True,
                'verbose_name_plural': '月度报表一',
            },
        ),
    ]
