[GENERAL]
Version=1.3.15
displaylast=NO
displaymenu=1
unmarked=1

[DATABASE]
DBMS=ODBC
Database=
UserId=sa
DatabasePassword=sql
LogPassword=
ServerName=
LogId=
Lock=
Prompt=0
dsn=jmj-product
//dsn=mysql-aliyun
dsn2=fake
AutoCommit=0
;CardType=M1


// com1: comport=0 
// com2: comport=1
// ....
// USB : comprot=100
[ICCARD]
;CardType=M1
ComPort=100
rfcomport=100
ReadCard=A

commcardtype=' "A", "B" '

[application]
;autologon=YES
;LastUser=SUPERVISOR
;ISHDOFFICE=Y
docpath=c:\program files\atd\hdms\data
LastUser=SYJMJ

[library]
Extname=pbd


[SqlRemote]
dbexecute=dbremote.exe -m 12M -l 400000  -o yiren01.log -c "dsn=hdms1;uid=dba;pwd=

[dbbackup]
dbbackupexec=bin\dbbackup.exe -y -c "dsn=hdms;uid=dba;pwd=ihavefun
isexecdbbackup=1


[BACKUP]
dir=H:\HDMSBAKX
logfile=H:\HDMSBAKX\040718135550.log
dbfile=H:\HDMSBAKX\040718135550.db

[basenum_num]
expense_serviece_basenum=0
expense_goods_basenum=1
expense_cards_basenum=0

[basenum_visible]
expense_serviece_basenum=0
expense_goods_basenum=1
expense_cards_basenum=0

[Report]
adminreport=Y
userreport=N
changedate=6	
intervalmonth=1 



[Others]
cardmoneyequit=N
checkservicecode=N
companyid=JMJ
invoicepaper=0
invoicetype=xhz
clear_date1=365
clear_date2=180
objectvalueway=0
;youareadog=9999
//数据窗口刷新间隔秒数
intervalseconds=600

S1=S1店
S2=S2店
S2=S2店

no1=Y
no2=Y
controlrptdays=N
rptprint=Y


[Report]
adminreport=Y
userreport=N
changedate=6	
intervalmonth=1 
printflag=Y

[Custdisp]
custdisp=N
comport=1

[invoice]
invoicetype=58
width=58

[moneybox]
moneybox=Y
porttype=C


[cost]
/* C:取固定金额　DEFAULT Ｐ:按照百分比率取
srvcost=C

[salary]
/* 计算员工提成是否扣除成本　Y:扣除成本 DEFAULT  	N:　不扣除成本
discountcost=Y
/＊扣除成本按照何种方式扣除　:C:按固定成本金额扣除　DEFAULT　P:按成本百分比率扣除
costtype=C

[multicash]
multicash=N
multistore=N
storecode=2


[cost]
/* C:取固定金额　DEFAULT Ｐ:按照百分比率取
srvcost=C

[salary]
/* 计算员工提成是否扣除成本　Y:扣除成本 DEFAULT  	N:　不扣除成本
discountcost=Y
/＊扣除成本按照何种方式扣除　:C:按固定成本金额扣除　DEFAULT　P:按成本百分比率扣除
costtype=C

[ftp]
server=www.softweb.net.cn
parmfile=-n -s:d:\aa.txt

[finger]
usefinger=N

[SSID]
usessid=N
linecount=1


[SMS]
SMS=Y
url= http://n.020sms.com/MSMSEND.ewing?ECODE=YTWO
parm1=&USERNAME=
parm2=&PASSWORD=
parm3=&CONTENT=
parm4=&MOBILE=
parm5=&seq=1000
parm6=
//parm6=&extno=
user=
password=

emplsms=
storesms=
transmsflag=Y
transmscontent="尊敬的MIC.VIP您好,你的卡号为@ccode，在@vsdate有消费@amount，现有余额@icleftmoney,请查核。如有疑问，请和0574-63933555联系。谢谢，欢迎再次光临!"

transmscontent_amount="尊贵的顾客：您好，您于北京时间@vsdate日@vstime时在梦郎集团@storename消费@amount元，卡内余额为@icleftmoney元。【梦郎集团】"
transmscontent_times="尊贵的顾客：您好，您于北京时间@vsdate日@vstime时在梦郎集团@storename做@srvname一次，卡内还剩@icleftmoney次。【梦郎集团】"

金额卡售卡充值短信="尊贵的顾客：您好，您于北京时间@vsdate日@vstime时在梦郎集团@storename成功办理卡，金额@amount元。【梦郎集团】"
次数卡售卡充值短信="尊贵的顾客：您好，您于北京时间@vsdate日@vstime时在梦郎集团@storename成功办理@srvname，@icleftmoney。【梦郎集团】"
金额卡换卡短信='尊贵的顾客：您好，由于梦郎集团软件系统升级，今后您到店消费将实行刷卡制，您当前@cardname卡内余额为@icleftmoney元，感谢您的支持！'
次数卡换卡短信='尊贵的顾客：您好，由于梦郎集团软件系统升级，今后您到店消费将实行刷卡制，您的@cardname卡内剩余次数为@icleftmoney，感谢您的支持！'

emplsmsflag=N
emplsmscontent=

storesmsflag=Y
storesmscontent=

[invoicetype]
// usedriver :	Y	用WINDOWS驱动程序
//			invoice=xhz/else
//		N	直接输出打印机
// 			invoicetype = jiayi/zy/else
usedriver=Y
//printer=GP-80160(Cut) Series
printer=Microsoft Print to PDF
invoicetype=58
ecode1=pmcode
ecode2=asscode1
printport=LPT1
invoicecopys=1

//usertype : 	基础信息	base
//		管理信息	advance
//		采购		purchase
//		库房		warehouse
//		财务		finance

[dwcontrol]
functionmodule=ALL
usertype=ALL

[receiption]
windows=w_trans_edit_2013_jz

