# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-09-14 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0044_auto_20210711_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensehung',
            name='hunguuid',
            field=models.ForeignKey(blank=True, db_column='hunguuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adviser.ExpvstollHung'),
        ),
    ]
