# Generated by Django 3.2.18 on 2026-05-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0045_auto_20210914_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardblacklist',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='emplschedule',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='expensehung',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='expvstollhung',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='room',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='vipinfogroup1',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
    ]
