# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-04-24 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0154_auto_20210405_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='wharehouse',
            name='tiwhcodelist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('00', '总仓'), ('01', '01店仓库')], max_length=5, null=True, verbose_name='可用门店'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='comptype',
            field=models.CharField(blank=True, choices=[('amount', '计费'), ('times', '计次'), ('period', '计时')], default='amount', max_length=8, null=True, verbose_name='消费模式'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='displayclass2',
            field=models.CharField(blank=True, choices=[('010', '面部'), ('020', '身体'), ('030', '养发'), ('031', '养发')], default='', max_length=16, null=True, verbose_name='显示分类（方法二）'),
        ),
        migrations.AlterField(
            model_name='empl',
            name='team',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='业务组别'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='displayclass2',
            field=models.CharField(blank=True, choices=[('010', '面部'), ('020', '身体'), ('030', '养发'), ('031', '养发')], default='', max_length=16, null=True, verbose_name='显示分类（方法二）'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='unit',
            field=models.CharField(blank=True, choices=[('51', '个'), ('60', '斤'), ('67', '片'), ('63', '双'), ('54', '袋'), ('70', '份'), ('66', '副'), ('55', '张'), ('50', '套'), ('65', '本'), ('52', '台'), ('68', '条'), ('69', '桶'), ('30', '瓶'), ('40', '支'), ('61', '包'), ('10', 'ml'), ('62', '件'), ('64', '对'), ('53', '盒'), ('20', 'g'), ('71', '滴'), ('90', '元')], db_column='UNIT', default='10', max_length=10, null=True, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='item',
            name='displayclass2',
            field=models.CharField(blank=True, choices=[('010', '面部'), ('020', '身体'), ('030', '养发'), ('031', '养发')], default='', max_length=16, null=True, verbose_name='显示分类（方法二）'),
        ),
        migrations.AlterField(
            model_name='promotionsdetail',
            name='sgcode',
            field=models.CharField(blank=True, choices=[('3051800000', '即时护肤全套'), ('3051800001', '即时身体全套'), ('3051800002', '微电流面部'), ('3051900000', '脂肪专家'), ('3051900005', '淤滞通疗')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='displayclass2',
            field=models.CharField(blank=True, choices=[('010', '面部'), ('020', '身体'), ('030', '养发'), ('031', '养发')], default='', max_length=16, null=True, verbose_name='显示分类（方法二）'),
        ),
    ]
