# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-04-26 21:39
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0155_auto_20210424_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtype',
            name='storelist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('00', '总部'), ('88', '练习')], max_length=128, null=True, verbose_name='可用门店'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='storelist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('00', '总部'), ('88', '练习')], max_length=128, null=True, verbose_name='可用门店'),
        ),
        migrations.AlterField(
            model_name='item',
            name='storelist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('00', '总部'), ('88', '练习')], max_length=128, null=True, verbose_name='可用门店'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='storelist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('00', '总部'), ('88', '练习')], max_length=128, null=True, verbose_name='可用门店'),
        ),
        migrations.AlterField(
            model_name='wharehouse',
            name='saleatr',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('G', '销售'), ('TO', '转出'), ('TI', '转入'), ('I', '进货'), ('F', '出货'), ('ZT', '自提'), ('U', '领用'), ('C', '盘点'), ('M', '邮寄')], max_length=128, null=True, verbose_name='允许操作'),
        ),
        migrations.AlterField(
            model_name='wharehouse',
            name='tiwhcodelist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('00', '总仓'), ('01', '01店仓库')], max_length=128, null=True, verbose_name='可以转出的仓库'),
        ),
    ]
