# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-05-04 22:03
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0156_auto_20210426_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wharehouse',
            name='tiwhcodelist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('00', '总仓'), ('01', '01仓')], max_length=128, null=True, verbose_name='可以转出的仓库'),
        ),
    ]
