# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-07-12 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0159_auto_20210711_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serviecegoods',
            fields=[
                ('last_modified', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间')),
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('creater', models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者')),
                ('flag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除')),
                ('company', models.CharField(blank=True, default='yiren', editable=False, max_length=8, null=True, verbose_name='公司')),
                ('storecode', models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店')),
                ('srvcode', models.CharField(blank=True, max_length=32, null=True, verbose_name='服务项目编号')),
                ('gcode', models.CharField(blank=True, max_length=32, null=True, verbose_name='商品编号')),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='使用量')),
                ('goodsuuid', models.ForeignKey(blank=True, db_column='goodsuuid', max_length=16, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Goods', verbose_name='使用产品')),
                ('srvuuid', models.ForeignKey(blank=True, db_column='srvuuid', max_length=16, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Serviece', verbose_name='服务项目')),
            ],
            options={
                'db_table': 'serviecegoods',
                'managed': True,
            },
        ),
    ]
