# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-07-19 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0160_serviecegoods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviecegoods',
            options={'managed': True, 'verbose_name': '服务用料', 'verbose_name_plural': '服务用料'},
        ),
        migrations.AlterField(
            model_name='vip',
            name='status',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='当前状态'),
        ),
    ]
