# Generated by Django 3.2.18 on 2026-07-28 11:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0169_vip_lifecycle_appoption_seg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoption',
            name='seg',
            field=models.CharField(choices=[('vipstatus', '会员状态'), ('viplevel', '会员级别'), ('brand', '品牌'), ('tags', '标签'), ('viptags', '会员标签'), ('financeclass1', '财务分类（一）'), ('financeclass2', '财务分类（二）'), ('displayclass1', '显示分类(方法一)'), ('displayclass2', '显示分类(方法二)'), ('bodyparts1', '身体部位'), ('bodyparts2', '身体部位(二)'), ('marketclass1', '营销分类(一)'), ('marketclass2', '营销分类(二)'), ('marketclass3', '营销分类(三）'), ('marketclass4', '项目分类4'), ('source', '来店渠道'), ('archivementclass1', '业绩分类（一）'), ('archivementclass2', '业绩分类（二）'), ('casetype', '回访类型'), ('unit', '单位'), ('discountclass', '折扣分类'), ('vip_lifecycle', '客户生命周期'), ('srvdisplayclass1', '服务项目-显示分类(方法一)'), ('srvdisplayclass2', '服务项目-显示分类(方法二)'), ('srvmarketclass1', '服务项目-营销分类(一)'), ('srvmarketclass2', '服务项目-营销分类(二)'), ('srvmarketclass3', '服务项目-营销分类(三)'), ('srvmarketclass4', '服务项目-营销分类(四)'), ('srvfinanceclass1', '服务项目-财务分类(一)'), ('srvfinanceclass2', '服务项目-财务分类(二)'), ('srvarchivementclass1', '服务项目-业绩分类(一)'), ('srvarchivementclass2', '服务项目-业绩分类(二)'), ('srvbodyparts1', '服务项目-身体部位'), ('srvtags', '服务项目-标签'), ('srvbrand', '服务项目-品牌'), ('srvdiscountclass', '服务项目-折扣分类'), ('goodsdisplayclass1', '商品-显示分类(方法一)'), ('goodsdisplayclass2', '商品-显示分类(方法二)'), ('goodsmarketclass1', '商品-营销分类(一)'), ('goodsmarketclass2', '商品-营销分类(二)'), ('goodsmarketclass3', '商品-营销分类(三)'), ('goodsmarketclass4', '商品-营销分类(四)'), ('goodsfinanceclass1', '商品-财务分类(一)'), ('goodsfinanceclass2', '商品-财务分类(二)'), ('goodsarchivementclass1', '商品-业绩分类(一)'), ('goodsarchivementclass2', '商品-业绩分类(二)'), ('goodsbodyparts1', '商品-身体部位'), ('goodstags', '商品-标签'), ('goodsbrand', '商品-品牌'), ('goodsdiscountclass', '商品-折扣分类'), ('cardtypedisplayclass1', '卡类-显示分类(方法一)'), ('cardtypedisplayclass2', '卡类-显示分类(方法二)'), ('cardtypemarketclass1', '卡类-营销分类(一)'), ('cardtypemarketclass2', '卡类-营销分类(二)'), ('cardtypemarketclass3', '卡类-营销分类(三)'), ('cardtypemarketclass4', '卡类-营销分类(四)'), ('cardtypefinanceclass1', '卡类-财务分类(一)'), ('cardtypefinanceclass2', '卡类-财务分类(二)'), ('cardtypearchivementclass1', '卡类-业绩分类(一)'), ('cardtypearchivementclass2', '卡类-业绩分类(二)'), ('cardtypebodyparts1', '卡类-身体部位'), ('cardtypetags', '卡类-标签'), ('cardtypebrand', '卡类-品牌'), ('cardtypediscountclass', '卡类-折扣分类')], max_length=40, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('prefers_morning', '偏好上午'), ('vip_key', '核心VIP'), ('prefers_evening', '偏好晚间'), ('referral', '转介绍客户'), ('needs_followup', '需跟进'), ('frequent', '高频客户'), ('high_value', '高价值客户'), ('new_customer', '新客'), ('sensitive_skin', '敏感肌客户'), ('sleeping', '沉睡客户')], max_length=500, null=True, verbose_name='标签'),
        ),
    ]
