# Generated by Django 3.2.18 on 2026-07-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_assistantthread_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipLifecycleSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(db_index=True, max_length=16)),
                ('storecode', models.CharField(db_index=True, max_length=16)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('vipuuid', models.CharField(max_length=36)),
                ('segment', models.CharField(max_length=32)),
                ('sleeping_grade', models.CharField(blank=True, default='', max_length=32)),
                ('days_since_last_visit', models.IntegerField(blank=True, null=True)),
                ('vip_status', models.CharField(blank=True, default='', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vip_lifecycle_snapshot',
            },
        ),
        migrations.CreateModel(
            name='VipLifecycleSnapshotSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=16)),
                ('storecode', models.CharField(max_length=16)),
                ('snapshot_date', models.DateField()),
                ('segment_counts', models.JSONField(blank=True, default=dict)),
                ('total_vips', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vip_lifecycle_snapshot_summary',
                'unique_together': {('company', 'storecode', 'snapshot_date')},
            },
        ),
        migrations.AddIndex(
            model_name='viplifecyclesnapshot',
            index=models.Index(fields=['company', 'storecode', 'snapshot_date', 'segment'], name='vip_lifecyc_company_874b40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='viplifecyclesnapshot',
            unique_together={('company', 'storecode', 'snapshot_date', 'vipuuid')},
        ),
    ]
