# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-04 11:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20181204_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstranslog',
            name='company',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='goodstranslog',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 4, 11, 41, 11, 970208, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='goodstranslog',
            name='creater',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='goodstranslog',
            name='uuid',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
