# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-05 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20181204_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledtl',
            name='company',
        ),
        migrations.RemoveField(
            model_name='saledtl',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='saledtl',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='saledtl',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='saledtl',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='saledtl',
            name='storecode',
        ),
        migrations.RemoveField(
            model_name='saledtl',
            name='uuid',
        ),
        migrations.AddField(
            model_name='saledtl',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodstranslog',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
