# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-06 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20181216_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodstranslog',
            options={'get_latest_by': 'gtranukid', 'managed': True, 'verbose_name': '商品进出明细', 'verbose_name_plural': '商品进出明细'},
        ),
    ]
