# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-28 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0017_salehead_supplierid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstranslog',
            name='batch',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='进货批次'),
        ),
    ]
