# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-27 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0095_auto_20190927_1246'),
        ('goods', '0021_auto_20190917_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviecegoods',
            name='company',
            field=models.CharField(blank=True, default='yiren', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='serviecegoods',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='建立时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviecegoods',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='serviecegoods',
            name='flag',
            field=models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='serviecegoods',
            name='goodsuuid',
            field=models.ForeignKey(blank=True, db_column='goodsuuid', max_length=16, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Goods', verbose_name='使用产品'),
        ),
        migrations.AddField(
            model_name='serviecegoods',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间'),
        ),
        migrations.AddField(
            model_name='serviecegoods',
            name='srvcode',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='服务项目编号'),
        ),
        migrations.AddField(
            model_name='serviecegoods',
            name='srvuuid',
            field=models.ForeignKey(blank=True, db_column='srvuuid', max_length=16, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Serviece', verbose_name='服务项目'),
        ),
        migrations.AddField(
            model_name='serviecegoods',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.RemoveField(
            model_name='serviecegoods',
            name='id',
        ),
        migrations.RemoveField(
            model_name='serviecegoods',
            name='svrcode',
        ),
        migrations.AddField(
            model_name='serviecegoods',
            name='uuid',
            field=models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviecegoods',
            name='gcode',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='商品编号'),
        ),

        # migrations.RemoveField(
        #     model_name='serviecegoods',
        #     name='id',
        # ),
        # migrations.RemoveField(
        #     model_name='serviecegoods',
        #     name='svrcode',
        # ),
    ]
