# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-13 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0023_auto_20191009_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='gcode',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='stockmst',
            name='ecode',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='盘点员工'),
        ),
    ]
