# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-16 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0025_auto_20191013_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsTransProcess',
            fields=[
                ('last_modified', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间')),
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('creater', models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者')),
                ('flag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除')),
                ('company', models.CharField(blank=True, default='yfy', editable=False, max_length=8, null=True, verbose_name='公司')),
                ('storecode', models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店')),
                ('transstep', models.CharField(blank=True, max_length=16, null=True, verbose_name='处理流程')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='goodstransdetail',
            old_name='transid',
            new_name='transuuid',
        ),
        migrations.RemoveField(
            model_name='goodstranshead',
            name='inwhcode',
        ),
        migrations.AddField(
            model_name='goodstransdetail',
            name='sukid',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='流水单号'),
        ),
        migrations.AddField(
            model_name='goodstranshead',
            name='sukid',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='流水单号'),
        ),
        migrations.AddField(
            model_name='goodstranshead',
            name='totamount',
            field=models.DecimalField(blank=True, db_column='TMOUNT', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='goodstranshead',
            name='whcode',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='仓库'),
        ),
        migrations.AlterField(
            model_name='goodstransdetail',
            name='gcode',
            field=models.CharField(blank=True, db_column='gcode', max_length=16, null=True, verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='goodstranshead',
            name='ecode',
            field=models.CharField(blank=True, db_column='ECODE', max_length=16, null=True, verbose_name='第一流程人'),
        ),
        migrations.AlterField(
            model_name='goodstranshead',
            name='saleatr',
            field=models.CharField(choices=[('G', '销售'), ('I', '进货'), ('O', '出货'), ('F', '退货'), ('U', '领用'), ('C', '盘点'), ('TI', '转入'), ('TO', '转出'), ('SL', '申领单'), ('CG', '采购单')], db_column='saleatr', max_length=8, verbose_name='单号类型'),
        ),
        migrations.AlterField(
            model_name='goodstranshead',
            name='status',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='goodstransprocess',
            name='transuuid',
            field=models.ForeignKey(blank=True, db_column='transid', null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsTransHead'),
        ),
    ]
