# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-17 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0026_auto_20191016_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodstranshead',
            options={'managed': True, 'verbose_name': '商品流通单'},
        ),
        migrations.RemoveField(
            model_name='goodstransprocess',
            name='transstep',
        ),
        migrations.AddField(
            model_name='goodstranshead',
            name='otherstorecode',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='对应门店'),
        ),
        migrations.AddField(
            model_name='goodstranshead',
            name='otherwhcode',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='对应仓库'),
        ),
        migrations.AddField(
            model_name='goodstranshead',
            name='step1ecode',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='第一步批准人'),
        ),
        migrations.AddField(
            model_name='goodstranshead',
            name='step1flag',
            field=models.CharField(blank=True, choices=[('AGREE', '同意'), ('DISAGREE', '不同意')], max_length=16, null=True, verbose_name='第一步处理结果'),
        ),
        migrations.AddField(
            model_name='goodstranshead',
            name='step1note',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='第一步意见'),
        ),
        migrations.AddField(
            model_name='goodstranshead',
            name='step2ecode',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='第二步批准人'),
        ),
        migrations.AddField(
            model_name='goodstranshead',
            name='step2flag',
            field=models.CharField(blank=True, choices=[('AGREE', '同意'), ('DISAGREE', '不同意')], max_length=16, null=True, verbose_name='第二步处理结果'),
        ),
        migrations.AddField(
            model_name='goodstranshead',
            name='step2note',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='第二步意见'),
        ),
        migrations.AddField(
            model_name='goodstranshead',
            name='step3ecode',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='第三步批准人'),
        ),
        migrations.AddField(
            model_name='goodstranshead',
            name='step3flag',
            field=models.CharField(blank=True, choices=[('AGREE', '同意'), ('DISAGREE', '不同意')], max_length=16, null=True, verbose_name='第三步处理结果'),
        ),
        migrations.AddField(
            model_name='goodstranshead',
            name='step3note',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='第三步意见'),
        ),
        migrations.AddField(
            model_name='goodstranshead',
            name='step4ecode',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='第四步批准人'),
        ),
        migrations.AddField(
            model_name='goodstranshead',
            name='step4flag',
            field=models.CharField(blank=True, choices=[('AGREE', '同意'), ('DISAGREE', '不同意')], max_length=16, null=True, verbose_name='第四步处理结果'),
        ),
        migrations.AddField(
            model_name='goodstranshead',
            name='step4note',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='第四步意见'),
        ),
        migrations.AddField(
            model_name='goodstranshead',
            name='supplierid',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='goodstransprocess',
            name='step1ecode',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='第一步批准人'),
        ),
        migrations.AddField(
            model_name='goodstransprocess',
            name='step1flag',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='第一步处理结果'),
        ),
        migrations.AddField(
            model_name='goodstransprocess',
            name='step1note',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='第一步意见'),
        ),
        migrations.AddField(
            model_name='goodstransprocess',
            name='step2ecode',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='第二步批准人'),
        ),
        migrations.AddField(
            model_name='goodstransprocess',
            name='step2flag',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='第二步处理结果'),
        ),
        migrations.AddField(
            model_name='goodstransprocess',
            name='step2note',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='第二步意见'),
        ),
        migrations.AddField(
            model_name='goodstransprocess',
            name='step3ecode',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='第三步批准人'),
        ),
        migrations.AddField(
            model_name='goodstransprocess',
            name='step3flag',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='第三步处理结果'),
        ),
        migrations.AddField(
            model_name='goodstransprocess',
            name='step3note',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='第三步意见'),
        ),
        migrations.AddField(
            model_name='goodstransprocess',
            name='step4ecode',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='第四步批准人'),
        ),
        migrations.AddField(
            model_name='goodstransprocess',
            name='step4flag',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='第四步处理结果'),
        ),
        migrations.AddField(
            model_name='goodstransprocess',
            name='step4note',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='第四步意见'),
        ),
    ]
