# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-18 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0028_auto_20191017_0027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodstranshead',
            options={'managed': True, 'verbose_name': '商品流通单', 'verbose_name_plural': '商品流通单'},
        ),
        migrations.AddField(
            model_name='goodstranslog',
            name='transdesc',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='交易相关描述'),
        ),
        migrations.AddField(
            model_name='goodstranslog',
            name='transuuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='对应原始记录uuid'),
        ),
    ]
