# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-30 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0041_auto_20191129_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstransdetail',
            name='gcode',
            field=models.CharField(blank=True, db_column='gcode', max_length=16, null=True, verbose_name='商品'),
        ),
        # migrations.AlterUniqueTogether(
        #     name='serviecegoods',
        #     unique_together=set([]),
        # ),
    ]
