# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-30 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0042_auto_20191130_2127'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviecegoods',
            unique_together=set([]),
        ),
    ]
