# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-09-08 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0061_auto_20200908_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owelist',
            old_name='ownqty',
            new_name='oweqty',
        ),
    ]
