# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-02 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0002_cardtype_sguuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtype',
            name='brand',
        ),
    ]
