# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-03 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0004_cardtype_brand'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vip',
            unique_together=set([('company', 'storecode', 'vcode')]),
        ),
    ]
