# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-07 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0005_auto_20181203_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goodsct',
            field=models.CharField(blank=True, db_column='goodsct', max_length=16, null=True, verbose_name='商品折扣分类'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='supplierid',
            field=models.CharField(blank=True, db_column='supplierid', max_length=16, null=True, verbose_name='供应商'),
        ),
    ]
