# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-10 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0006_auto_20181207_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeinfo',
            old_name='companyid',
            new_name='company',
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='invoicealter',
            field=models.CharField(blank=True, db_column='invoicealter', default='N', max_length=8, null=True, verbose_name='直接打印提示'),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='invoicefoot1',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='发票页脚'),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='invoicefoot2',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='发票页脚'),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='invoicetitle1',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='发票抬头'),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='invoicetitle2',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='发票抬头'),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='salewhcode',
            field=models.CharField(blank=True, db_column='salewhcode', max_length=16, null=True, verbose_name='销售品仓库'),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='usewhcode',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='使用品仓库'),
        ),
    ]
