# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-18 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0007_auto_20181210_1711'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='serviece',
        #     name='srvrptypecode',
        #     field=models.CharField(blank=True, max_length=32, null=True, verbose_name='所属报表分类'),
        # ),
        # migrations.AlterField(
        #     model_name='serviece',
        #     name='topcode',
        #     field=models.CharField(blank=True, db_column='TOPCODE', max_length=32, null=True, verbose_name='大类'),
        # ),
    ]
