# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-27 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0008_auto_20181218_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviece',
            name='srvrptypecode',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='所属报表分类'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='topcode',
            field=models.CharField(blank=True, db_column='TOPCODE', max_length=32, null=True, verbose_name='大类'),
        ),
    ]
