# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-06 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0010_auto_20181227_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardvsdi',
            name='topcode',
            field=models.CharField(blank=True, db_column='TOPCODE', max_length=32, null=True, verbose_name='服务大类'),
        ),
    ]
