# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-16 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0011_auto_20190106_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('last_modified', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间')),
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('creater', models.CharField(blank=True, default='anonymous', max_length=16, null=True, verbose_name='创建者')),
                ('flag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除')),
                ('company', models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='02', max_length=8, null=True, verbose_name='公司')),
                ('storecode', models.CharField(blank=True, max_length=16, null=True, verbose_name='门店')),
                ('itemclass4', models.CharField(blank=True, choices=[('', ''), ('', '')], max_length=16, null=True)),
                ('itemcode', models.CharField(blank=True, max_length=16, null=True)),
                ('itemname', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='serviece',
            name='itemclass1',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='empl',
            name='positioncode',
            field=models.ForeignKey(blank=True, db_column='positioncode', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empls', to='baseinfo.Position', verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='topcode',
            field=models.CharField(blank=True, db_column='TOPCODE', max_length=16, null=True, verbose_name='服务销售折扣分类'),
        ),
    ]
