# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-18 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0013_auto_20190216_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemclass1',
            field=models.CharField(blank=True, choices=[('10', '拓客项目'), ('20', '留客项目'), ('30', '升客项目'), ('40', '挖客项目'), ('50', '深挖项目')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='itemclass2',
            field=models.CharField(blank=True, choices=[('10', '基础项目'), ('20', '大项目'), ('30', '循环类项目'), ('40', '其他')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='itemclass3',
            field=models.CharField(blank=True, choices=[('10', '无差别类项目'), ('20', '必备类项目'), ('30', '一维类项目'), ('40', '魅力类项目')], max_length=16, null=True),
        ),
    ]
