# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-18 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0015_auto_20190218_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='itemclass1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemclass2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemclass3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemclass4',
        ),
        migrations.RemoveField(
            model_name='serviece',
            name='itemclass1',
        ),
        migrations.AddField(
            model_name='item',
            name='after_sales_scheme',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='售后服务方案'),
        ),
        migrations.AddField(
            model_name='item',
            name='basenum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='顾问提成基数'),
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='品牌'),
        ),
        migrations.AddField(
            model_name='item',
            name='discountclass',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='折扣分类'),
        ),
        migrations.AddField(
            model_name='item',
            name='displayclass1',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='显示分类'),
        ),
        migrations.AddField(
            model_name='item',
            name='financeclass1',
            field=models.CharField(blank=True, choices=[('10', '正常'), ('20', '其他')], max_length=16, null=True, verbose_name='项目财务分类1'),
        ),
        migrations.AddField(
            model_name='item',
            name='financeclass2',
            field=models.CharField(blank=True, choices=[('10', '正常'), ('20', '其他')], max_length=16, null=True, verbose_name='项目财务分类2'),
        ),
        migrations.AddField(
            model_name='item',
            name='intervalday',
            field=models.IntegerField(blank=True, default=7, null=True, verbose_name='建议间隔天数'),
        ),
        migrations.AddField(
            model_name='item',
            name='marketclass1',
            field=models.CharField(blank=True, choices=[('10', '拓客项目'), ('20', '留客项目'), ('30', '升客项目'), ('40', '挖客项目'), ('50', '深挖项目'), ('90', '其他')], max_length=16, null=True, verbose_name='项目营销分类1'),
        ),
        migrations.AddField(
            model_name='item',
            name='marketclass2',
            field=models.CharField(blank=True, choices=[('10', '基础项目'), ('20', '大项目'), ('30', '循环类项目'), ('90', '其他')], max_length=16, null=True, verbose_name='项目营销分类2'),
        ),
        migrations.AddField(
            model_name='item',
            name='marketclass3',
            field=models.CharField(blank=True, choices=[('10', '无差别类项目'), ('20', '必备类项目'), ('30', '一维类项目'), ('40', '魅力类项目'), ('90', '其他')], max_length=16, null=True, verbose_name='项目营销分类3'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='价格'),
        ),
        migrations.AddField(
            model_name='item',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='第二价格'),
        ),
        migrations.AddField(
            model_name='item',
            name='price3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='第三价格'),
        ),
        migrations.AddField(
            model_name='item',
            name='price4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='第四价格'),
        ),
        migrations.AddField(
            model_name='item',
            name='pricechangeable',
            field=models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', max_length=8, null=True, verbose_name='可否修改价格'),
        ),
        migrations.AddField(
            model_name='item',
            name='pricecurrency',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='币别'),
        ),
        migrations.AddField(
            model_name='item',
            name='rptcode1',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='rptcode2',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='rptcode3',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='rptcode4',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='rptcode5',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='rptcode6',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='salesflag',
            field=models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', max_length=8, null=True, verbose_name='可否销售'),
        ),
        migrations.AddField(
            model_name='item',
            name='secbasenum',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='美容师提成基数'),
        ),
        migrations.AddField(
            model_name='item',
            name='srvrptypecode',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='报表分类'),
        ),
        migrations.AddField(
            model_name='item',
            name='thrbasenum',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='美容师2提成基数'),
        ),
        migrations.AddField(
            model_name='item',
            name='ttype',
            field=models.CharField(blank=True, choices=[('G', '商品'), ('S', '服务'), ('C', '售卡'), ('I', '充值')], max_length=16, null=True, verbose_name='商品/服务'),
        ),
        migrations.AddField(
            model_name='item',
            name='valiflag',
            field=models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', max_length=8, null=True, verbose_name='是否有效'),
        ),
    ]
