# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-18 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0018_auto_20190218_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviece',
            name='areacode',
        ),
        migrations.RemoveField(
            model_name='serviece',
            name='companyid',
        ),
        migrations.RemoveField(
            model_name='serviece',
            name='svrprccurrency',
        ),
        migrations.AlterField(
            model_name='serviece',
            name='srvrptypecode',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='报表分类'),
        ),
    ]
