# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-18 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0019_auto_20190218_1331'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='serviece',
        #     name='photofile',
        # ),
        # migrations.RemoveField(
        #     model_name='serviece',
        #     name='srvcost',
        # ),
        # migrations.RemoveField(
        #     model_name='serviece',
        #     name='srvcostperc',
        # ),
        # migrations.RemoveField(
        #     model_name='serviece',
        #     name='svrdesc',
        # ),
        # migrations.RemoveField(
        #     model_name='serviece',
        #     name='svrdisc',
        # ),
        # migrations.RemoveField(
        #     model_name='serviece',
        #     name='trueprc',
        # ),
        # migrations.AddField(
        #     model_name='item',
        #     name='achivementcost',
        #     field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='业绩固定成本扣除'),
        # ),
        # migrations.AddField(
        #     model_name='serviece',
        #     name='achivementcost',
        #     field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='业绩固定成本扣除'),
        # ),
    ]
