# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-19 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0021_auto_20190218_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='displayclass1',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='显示分类1'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='displayclass1',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='显示分类1'),
        ),
    ]
