# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-26 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0022_auto_20190219_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='vcode',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True, verbose_name='会员号'),
        ),
    ]
