# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-01 07:41
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0029_auto_20190301_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtype',
            name='storelist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', '青岛店'), ('2', '沈阳店'), ('3', '大连店'), ('5', '济南店')], max_length=7, null=True, verbose_name='可用门店'),
        ),
        migrations.AddField(
            model_name='goods',
            name='storelist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', '青岛店'), ('2', '沈阳店'), ('3', '大连店'), ('5', '济南店')], max_length=7, null=True, verbose_name='可用门店'),
        ),
        migrations.AddField(
            model_name='item',
            name='storelist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', '青岛店'), ('2', '沈阳店'), ('3', '大连店'), ('5', '济南店')], max_length=7, null=True, verbose_name='可用门店'),
        ),
        migrations.AddField(
            model_name='serviece',
            name='storelist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', '青岛店'), ('2', '沈阳店'), ('3', '大连店'), ('5', '济南店')], max_length=7, null=True, verbose_name='可用门店'),
        ),
    ]
