# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-12 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0031_auto_20190303_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vip',
            name='statuscode',
        ),
        migrations.AddField(
            model_name='vip',
            name='status',
            field=models.CharField(blank=True, choices=[('010', '有效会员'), ('020', '警示会员'), ('030', '流失会员'), ('110', '体验客户'), ('190', '体验失败客户')], max_length=8, null=True, verbose_name='当前状态'),
        ),
    ]
