# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-19 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0032_auto_20190312_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='pinying',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='拼音'),
        ),
    ]
