# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-19 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0033_vip_pinying'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vip',
            old_name='pinying',
            new_name='pinyin',
        ),
    ]
