# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-24 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0034_auto_20190319_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoption',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='cardsupertype',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='cardvsdi',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='empl',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='enactmen',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='goodsct',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='goodsprice',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='hdsysuser',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='item',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='objectvalue2',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='paymode',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='position',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='promotionsdetail',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='promotionsgroup',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='promotionsgroupdetail',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='servieceprice',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='srvrptype',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='srvtopty',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='team',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='useright',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='vcode',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='会员号'),
        ),
        migrations.AlterField(
            model_name='wharehouse',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan', max_length=8, null=True, verbose_name='公司'),
        ),
    ]
