# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-24 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0036_auto_20190324_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='source',
            field=models.CharField(blank=True, choices=[('朋友介绍', '朋友介绍'), ('网络媒体', '网络媒体'), ('户外媒体', '户外媒体'), ('合作伙伴', '合作伙伴'), ('朋友圈', '朋友圈'), ('路过', '路过'), ('其他', '其他')], max_length=32, null=True, verbose_name='来店渠道'),
        ),
    ]
