# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-10 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0037_auto_20190324_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtype',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='第二价格'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='price3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='第三价格'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='price4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='第四价格'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='pricecurrency',
            field=models.CharField(blank=True, default='RMB', max_length=8, null=True, verbose_name='币别'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='第二价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='第三价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='第四价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='pricecurrency',
            field=models.CharField(blank=True, default='RMB', max_length=8, null=True, verbose_name='币别'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='第二价格'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='第三价格'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='第四价格'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pricecurrency',
            field=models.CharField(blank=True, default='RMB', max_length=8, null=True, verbose_name='币别'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='第二价格'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='price3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='第三价格'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='price4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='第四价格'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='pricecurrency',
            field=models.CharField(blank=True, default='RMB', max_length=8, null=True, verbose_name='币别'),
        ),
    ]
