# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-26 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0040_auto_20190426_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='achivementcost',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='basenum',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='pmguideperc',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='pmperc',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='pmpoint',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='secbasenum',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='secguideperc',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='secperc',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='secpoint',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='thrbasenum',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='thrguideperc',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='thrperc',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='thrpoint',
        ),
    ]
