# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-05 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0042_auto_20190426_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'managed': True, 'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='viptags',
            options={'managed': True, 'verbose_name': '客户标签', 'verbose_name_plural': '客户标签'},
        ),
        migrations.RemoveField(
            model_name='tags',
            name='id',
        ),
        migrations.RemoveField(
            model_name='viptags',
            name='id',
        ),
        migrations.AddField(
            model_name='cardtype',
            name='itemtags',
            field=models.ManyToManyField(to='baseinfo.Tags', verbose_name='项目标签'),
        ),
        migrations.AddField(
            model_name='goods',
            name='itemtags',
            field=models.ManyToManyField(to='baseinfo.Tags', verbose_name='项目标签'),
        ),
        migrations.AddField(
            model_name='item',
            name='itemtags',
            field=models.ManyToManyField(to='baseinfo.Tags', verbose_name='项目标签'),
        ),
        migrations.AddField(
            model_name='serviece',
            name='itemtags',
            field=models.ManyToManyField(to='baseinfo.Tags', verbose_name='项目标签'),
        ),
        migrations.AddField(
            model_name='vip',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, max_length=64, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='storelist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('000', '总部'), ('001', '杭州大厦店'), ('002', '万象城店')], max_length=11, null=True, verbose_name='可用门店'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('补水', '补水'), ('去角质', '去角质'), ('美白', '美白'), ('柔滑', '柔滑'), ('亮肤', '亮肤'), ('均衡肤色', '均衡肤色'), ('舒缓放松', '舒缓放松'), ('紧致', '紧致'), ('减内脂', '减内脂'), ('塑形', '塑形'), ('美化', '美化'), ('循环', '循环'), ('淡斑', '淡斑'), ('脱毛', '脱毛'), ('抗皱', '抗皱'), ('抗敏', '抗敏'), ('修复', '修复'), ('修护', '修护'), ('抗衰', '抗衰'), ('抗老化', '抗老化'), ('免疫提升', '免疫提升'), ('排毒', '排毒'), ('010', '面部'), ('020', '身体'), ('030', '仪器'), ('040', '销售'), ('100', '拓客项目'), ('110', '留客项目'), ('120', '升客项目'), ('130', '挖客项目')], max_length=64, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='storelist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('000', '总部'), ('001', '杭州大厦店'), ('002', '万象城店')], max_length=11, null=True, verbose_name='可用门店'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('补水', '补水'), ('去角质', '去角质'), ('美白', '美白'), ('柔滑', '柔滑'), ('亮肤', '亮肤'), ('均衡肤色', '均衡肤色'), ('舒缓放松', '舒缓放松'), ('紧致', '紧致'), ('减内脂', '减内脂'), ('塑形', '塑形'), ('美化', '美化'), ('循环', '循环'), ('淡斑', '淡斑'), ('脱毛', '脱毛'), ('抗皱', '抗皱'), ('抗敏', '抗敏'), ('修复', '修复'), ('修护', '修护'), ('抗衰', '抗衰'), ('抗老化', '抗老化'), ('免疫提升', '免疫提升'), ('排毒', '排毒'), ('010', '面部'), ('020', '身体'), ('030', '仪器'), ('040', '销售'), ('100', '拓客项目'), ('110', '留客项目'), ('120', '升客项目'), ('130', '挖客项目')], max_length=64, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='item',
            name='storelist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('000', '总部'), ('001', '杭州大厦店'), ('002', '万象城店')], max_length=11, null=True, verbose_name='可用门店'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('补水', '补水'), ('去角质', '去角质'), ('美白', '美白'), ('柔滑', '柔滑'), ('亮肤', '亮肤'), ('均衡肤色', '均衡肤色'), ('舒缓放松', '舒缓放松'), ('紧致', '紧致'), ('减内脂', '减内脂'), ('塑形', '塑形'), ('美化', '美化'), ('循环', '循环'), ('淡斑', '淡斑'), ('脱毛', '脱毛'), ('抗皱', '抗皱'), ('抗敏', '抗敏'), ('修复', '修复'), ('修护', '修护'), ('抗衰', '抗衰'), ('抗老化', '抗老化'), ('免疫提升', '免疫提升'), ('排毒', '排毒'), ('010', '面部'), ('020', '身体'), ('030', '仪器'), ('040', '销售'), ('100', '拓客项目'), ('110', '留客项目'), ('120', '升客项目'), ('130', '挖客项目')], max_length=64, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='storelist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('000', '总部'), ('001', '杭州大厦店'), ('002', '万象城店')], max_length=11, null=True, verbose_name='可用门店'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('补水', '补水'), ('去角质', '去角质'), ('美白', '美白'), ('柔滑', '柔滑'), ('亮肤', '亮肤'), ('均衡肤色', '均衡肤色'), ('舒缓放松', '舒缓放松'), ('紧致', '紧致'), ('减内脂', '减内脂'), ('塑形', '塑形'), ('美化', '美化'), ('循环', '循环'), ('淡斑', '淡斑'), ('脱毛', '脱毛'), ('抗皱', '抗皱'), ('抗敏', '抗敏'), ('修复', '修复'), ('修护', '修护'), ('抗衰', '抗衰'), ('抗老化', '抗老化'), ('免疫提升', '免疫提升'), ('排毒', '排毒'), ('010', '面部'), ('020', '身体'), ('030', '仪器'), ('040', '销售'), ('100', '拓客项目'), ('110', '留客项目'), ('120', '升客项目'), ('130', '挖客项目')], max_length=64, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='status',
            field=models.CharField(blank=True, choices=[('010', '有效会员'), ('020', '警示会员'), ('030', '流失会员'), ('120', '潜在客户'), ('110', '体验客户'), ('190', '体验失败客户')], max_length=8, null=True, verbose_name='当前状态'),
        ),
        migrations.AlterField(
            model_name='viptags',
            name='tag',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='客户标签'),
        ),
        migrations.AlterModelTable(
            name='tags',
            table='tags',
        ),
        migrations.AlterModelTable(
            name='viptags',
            table='viptags',
        ),
    ]
