# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-14 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0044_auto_20190506_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoption',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='appoption',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='cardsupertype',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='cardsupertype',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='brand',
            field=models.CharField(blank=True, choices=[('1', '幽兰'), ('2', '安杰玛'), ('21', 'SPA'), ('22', '依娜'), ('23', '舒活特'), ('24', '蒋医生'), ('25', '美生美'), ('26', '黄教授'), ('27', '李正宇'), ('28', '惠秋'), ('29', '于教授'), ('30', '柏荟'), ('31', '米瑞可'), ('32', '海格'), ('33', '玉之光'), ('90', '其他')], max_length=16, null=True, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='marketclass1',
            field=models.CharField(blank=True, choices=[('1001', '拓客项目'), ('1002', '留客项目'), ('1003', '升客项目'), ('1004', '挖客项目'), ('1005', '深挖项目'), ('1090', '其他')], default='', max_length=16, null=True, verbose_name='项目营销分类1'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('2001', '补水'), ('2002', '去角质'), ('2003', '美白'), ('2004', '柔滑'), ('2005', '亮肤'), ('2006', '均衡肤色'), ('2007', '舒缓放松'), ('2008', '紧致'), ('2009', '减内脂'), ('2010', '塑形'), ('2011', '美化'), ('2012', '循环'), ('2013', '淡斑'), ('2014', '脱毛'), ('2015', '抗皱'), ('2016', '抗敏'), ('2017', '修复'), ('2018', '修护'), ('2019', '抗衰'), ('2020', '抗老化'), ('2021', '免疫提升'), ('2022', '排毒'), ('2023', '面部'), ('2024', '身体'), ('2025', '仪器'), ('2026', '销售'), ('2099', '其他')], max_length=64, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='cardvsdi',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='cardvsdi',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='empl',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='empl',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='enactmen',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='brand',
            field=models.CharField(blank=True, choices=[('1', '幽兰'), ('2', '安杰玛'), ('21', 'SPA'), ('22', '依娜'), ('23', '舒活特'), ('24', '蒋医生'), ('25', '美生美'), ('26', '黄教授'), ('27', '李正宇'), ('28', '惠秋'), ('29', '于教授'), ('30', '柏荟'), ('31', '米瑞可'), ('32', '海格'), ('33', '玉之光'), ('90', '其他')], max_length=16, null=True, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='marketclass1',
            field=models.CharField(blank=True, choices=[('1001', '拓客项目'), ('1002', '留客项目'), ('1003', '升客项目'), ('1004', '挖客项目'), ('1005', '深挖项目'), ('1090', '其他')], default='', max_length=16, null=True, verbose_name='项目营销分类1'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('2001', '补水'), ('2002', '去角质'), ('2003', '美白'), ('2004', '柔滑'), ('2005', '亮肤'), ('2006', '均衡肤色'), ('2007', '舒缓放松'), ('2008', '紧致'), ('2009', '减内脂'), ('2010', '塑形'), ('2011', '美化'), ('2012', '循环'), ('2013', '淡斑'), ('2014', '脱毛'), ('2015', '抗皱'), ('2016', '抗敏'), ('2017', '修复'), ('2018', '修护'), ('2019', '抗衰'), ('2020', '抗老化'), ('2021', '免疫提升'), ('2022', '排毒'), ('2023', '面部'), ('2024', '身体'), ('2025', '仪器'), ('2026', '销售'), ('2099', '其他')], max_length=64, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='goodsct',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='goodsct',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='goodsprice',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='goodsprice',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='hdsysuser',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='hdsysuser',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, choices=[('1', '幽兰'), ('2', '安杰玛'), ('21', 'SPA'), ('22', '依娜'), ('23', '舒活特'), ('24', '蒋医生'), ('25', '美生美'), ('26', '黄教授'), ('27', '李正宇'), ('28', '惠秋'), ('29', '于教授'), ('30', '柏荟'), ('31', '米瑞可'), ('32', '海格'), ('33', '玉之光'), ('90', '其他')], max_length=16, null=True, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='item',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='item',
            name='marketclass1',
            field=models.CharField(blank=True, choices=[('1001', '拓客项目'), ('1002', '留客项目'), ('1003', '升客项目'), ('1004', '挖客项目'), ('1005', '深挖项目'), ('1090', '其他')], default='', max_length=16, null=True, verbose_name='项目营销分类1'),
        ),
        migrations.AlterField(
            model_name='item',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('2001', '补水'), ('2002', '去角质'), ('2003', '美白'), ('2004', '柔滑'), ('2005', '亮肤'), ('2006', '均衡肤色'), ('2007', '舒缓放松'), ('2008', '紧致'), ('2009', '减内脂'), ('2010', '塑形'), ('2011', '美化'), ('2012', '循环'), ('2013', '淡斑'), ('2014', '脱毛'), ('2015', '抗皱'), ('2016', '抗敏'), ('2017', '修复'), ('2018', '修护'), ('2019', '抗衰'), ('2020', '抗老化'), ('2021', '免疫提升'), ('2022', '排毒'), ('2023', '面部'), ('2024', '身体'), ('2025', '仪器'), ('2026', '销售'), ('2099', '其他')], max_length=64, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='objectvalue2',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='objectvalue2',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='paymode',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='paymode',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='position',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='position',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='promotionsdetail',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='promotionsdetail',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='promotionsgroup',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='promotionsgroup',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='promotionsgroupdetail',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='promotionsgroupdetail',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='brand',
            field=models.CharField(blank=True, choices=[('1', '幽兰'), ('2', '安杰玛'), ('21', 'SPA'), ('22', '依娜'), ('23', '舒活特'), ('24', '蒋医生'), ('25', '美生美'), ('26', '黄教授'), ('27', '李正宇'), ('28', '惠秋'), ('29', '于教授'), ('30', '柏荟'), ('31', '米瑞可'), ('32', '海格'), ('33', '玉之光'), ('90', '其他')], max_length=16, null=True, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='marketclass1',
            field=models.CharField(blank=True, choices=[('1001', '拓客项目'), ('1002', '留客项目'), ('1003', '升客项目'), ('1004', '挖客项目'), ('1005', '深挖项目'), ('1090', '其他')], default='', max_length=16, null=True, verbose_name='项目营销分类1'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('2001', '补水'), ('2002', '去角质'), ('2003', '美白'), ('2004', '柔滑'), ('2005', '亮肤'), ('2006', '均衡肤色'), ('2007', '舒缓放松'), ('2008', '紧致'), ('2009', '减内脂'), ('2010', '塑形'), ('2011', '美化'), ('2012', '循环'), ('2013', '淡斑'), ('2014', '脱毛'), ('2015', '抗皱'), ('2016', '抗敏'), ('2017', '修复'), ('2018', '修护'), ('2019', '抗衰'), ('2020', '抗老化'), ('2021', '免疫提升'), ('2022', '排毒'), ('2023', '面部'), ('2024', '身体'), ('2025', '仪器'), ('2026', '销售'), ('2099', '其他')], max_length=64, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='servieceprice',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='servieceprice',
            name='srvcode',
            field=models.CharField(blank=True, db_column='srvcode', max_length=16, verbose_name='项目编号'),
        ),
        migrations.AlterField(
            model_name='servieceprice',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='srvrptype',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='srvrptype',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='srvtopty',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='srvtopty',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='team',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='team',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='useright',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='useright',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='storecode',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='wharehouse',
            name='company',
            field=models.CharField(blank=True, default='youlan', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
    ]
