# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-14 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0045_auto_20190514_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoption',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='cardsupertype',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='sguuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='服务商品UUID'),
        ),
        migrations.AlterField(
            model_name='cardvsdi',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='empl',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='enactmen',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='goodsct',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='goodsprice',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='hdsysuser',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='item',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='objectvalue2',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='paymode',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='position',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='promotionsdetail',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='promotionsgroup',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='promotionsgroupdetail',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='servieceprice',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='srvrptype',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='srvtopty',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='team',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='useright',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='wharehouse',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者'),
        ),
    ]
