# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-15 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0047_auto_20190514_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appoption',
            options={'managed': True, 'verbose_name': '系统配置', 'verbose_name_plural': '系统配置'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'managed': True, 'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AddField(
            model_name='cardtype',
            name='bodyparts1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, default='', max_length=128, null=True, verbose_name='身体部位'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='marketclass4',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, default='', max_length=128, null=True, verbose_name='项目营销分类4'),
        ),
        migrations.AddField(
            model_name='goods',
            name='bodyparts1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, default='', max_length=128, null=True, verbose_name='身体部位'),
        ),
        migrations.AddField(
            model_name='goods',
            name='marketclass4',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, default='', max_length=128, null=True, verbose_name='项目营销分类4'),
        ),
        migrations.AddField(
            model_name='item',
            name='bodyparts1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, default='', max_length=128, null=True, verbose_name='身体部位'),
        ),
        migrations.AddField(
            model_name='item',
            name='marketclass4',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, default='', max_length=128, null=True, verbose_name='项目营销分类4'),
        ),
        migrations.AddField(
            model_name='serviece',
            name='bodyparts1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, default='', max_length=128, null=True, verbose_name='身体部位'),
        ),
        migrations.AddField(
            model_name='serviece',
            name='marketclass4',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, default='', max_length=128, null=True, verbose_name='项目营销分类4'),
        ),
        migrations.AlterField(
            model_name='appoption',
            name='itemname',
            field=models.CharField(max_length=40, verbose_name='编码'),
        ),
        migrations.AlterField(
            model_name='appoption',
            name='itemvalues',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='appoption',
            name='seg',
            field=models.CharField(choices=[('brand', '品牌'), ('tags', '标签'), ('marketclass1', '营销分类1'), ('displayclass1', '显示分类')], max_length=40, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='brand',
            field=models.CharField(blank=True, choices=[('1', '幽兰'), ('2', '安杰玛'), ('90', '其他'), ('21', 'SPA'), ('22', '依娜'), ('23', '舒活特'), ('24', '蒋医生'), ('25', '美生美'), ('26', '黄教授'), ('27', '李正宇'), ('28', '惠秋'), ('29', '于教授'), ('30', '柏荟'), ('31', '米瑞可'), ('32', '海格'), ('33', '玉之光')], max_length=16, null=True, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='displayclass1',
            field=models.CharField(blank=True, choices=[('0', '正常'), ('1', '特价'), ('2', '活动')], default='', max_length=16, null=True, verbose_name='显示分类1'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='financeclass1',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='项目财务分类1'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='financeclass2',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='项目财务分类2'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='marketclass1',
            field=models.CharField(blank=True, choices=[('40', '挖客项目'), ('50', '深挖项目'), ('10', '拓客项目'), ('20', '留客项目')], default='', max_length=16, null=True, verbose_name='项目营销分类1'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='marketclass2',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='项目营销分类2'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='marketclass3',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='项目营销分类3'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('2010', '塑形'), ('2014', '脱毛'), ('2025', '仪器'), ('2020', '抗老化'), ('2021', '免疫提升'), ('2001', '补水'), ('2019', '抗衰'), ('2022', '排毒'), ('2004', '柔滑'), ('2016', '抗敏'), ('2008', '紧致'), ('2002', '去角质'), ('2011', '美化'), ('2007', '舒缓放松'), ('2015', '抗皱'), ('2024', '身体'), ('2018', '修护'), ('2003', '美白'), ('2026', '销售'), ('2013', '淡斑'), ('2005', '亮肤'), ('2099', '其他'), ('2023', '面部'), ('2017', '修复'), ('2009', '减内脂'), ('2012', '循环'), ('2006', '均衡肤色')], max_length=128, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='brand',
            field=models.CharField(blank=True, choices=[('1', '幽兰'), ('2', '安杰玛'), ('90', '其他'), ('21', 'SPA'), ('22', '依娜'), ('23', '舒活特'), ('24', '蒋医生'), ('25', '美生美'), ('26', '黄教授'), ('27', '李正宇'), ('28', '惠秋'), ('29', '于教授'), ('30', '柏荟'), ('31', '米瑞可'), ('32', '海格'), ('33', '玉之光')], max_length=16, null=True, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='displayclass1',
            field=models.CharField(blank=True, choices=[('0', '正常'), ('1', '特价'), ('2', '活动')], default='', max_length=16, null=True, verbose_name='显示分类1'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='financeclass1',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='项目财务分类1'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='financeclass2',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='项目财务分类2'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='marketclass1',
            field=models.CharField(blank=True, choices=[('40', '挖客项目'), ('50', '深挖项目'), ('10', '拓客项目'), ('20', '留客项目')], default='', max_length=16, null=True, verbose_name='项目营销分类1'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='marketclass2',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='项目营销分类2'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='marketclass3',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='项目营销分类3'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('2010', '塑形'), ('2014', '脱毛'), ('2025', '仪器'), ('2020', '抗老化'), ('2021', '免疫提升'), ('2001', '补水'), ('2019', '抗衰'), ('2022', '排毒'), ('2004', '柔滑'), ('2016', '抗敏'), ('2008', '紧致'), ('2002', '去角质'), ('2011', '美化'), ('2007', '舒缓放松'), ('2015', '抗皱'), ('2024', '身体'), ('2018', '修护'), ('2003', '美白'), ('2026', '销售'), ('2013', '淡斑'), ('2005', '亮肤'), ('2099', '其他'), ('2023', '面部'), ('2017', '修复'), ('2009', '减内脂'), ('2012', '循环'), ('2006', '均衡肤色')], max_length=128, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, choices=[('1', '幽兰'), ('2', '安杰玛'), ('90', '其他'), ('21', 'SPA'), ('22', '依娜'), ('23', '舒活特'), ('24', '蒋医生'), ('25', '美生美'), ('26', '黄教授'), ('27', '李正宇'), ('28', '惠秋'), ('29', '于教授'), ('30', '柏荟'), ('31', '米瑞可'), ('32', '海格'), ('33', '玉之光')], max_length=16, null=True, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='item',
            name='displayclass1',
            field=models.CharField(blank=True, choices=[('0', '正常'), ('1', '特价'), ('2', '活动')], default='', max_length=16, null=True, verbose_name='显示分类1'),
        ),
        migrations.AlterField(
            model_name='item',
            name='financeclass1',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='项目财务分类1'),
        ),
        migrations.AlterField(
            model_name='item',
            name='financeclass2',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='项目财务分类2'),
        ),
        migrations.AlterField(
            model_name='item',
            name='marketclass1',
            field=models.CharField(blank=True, choices=[('40', '挖客项目'), ('50', '深挖项目'), ('10', '拓客项目'), ('20', '留客项目')], default='', max_length=16, null=True, verbose_name='项目营销分类1'),
        ),
        migrations.AlterField(
            model_name='item',
            name='marketclass2',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='项目营销分类2'),
        ),
        migrations.AlterField(
            model_name='item',
            name='marketclass3',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='项目营销分类3'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('2010', '塑形'), ('2014', '脱毛'), ('2025', '仪器'), ('2020', '抗老化'), ('2021', '免疫提升'), ('2001', '补水'), ('2019', '抗衰'), ('2022', '排毒'), ('2004', '柔滑'), ('2016', '抗敏'), ('2008', '紧致'), ('2002', '去角质'), ('2011', '美化'), ('2007', '舒缓放松'), ('2015', '抗皱'), ('2024', '身体'), ('2018', '修护'), ('2003', '美白'), ('2026', '销售'), ('2013', '淡斑'), ('2005', '亮肤'), ('2099', '其他'), ('2023', '面部'), ('2017', '修复'), ('2009', '减内脂'), ('2012', '循环'), ('2006', '均衡肤色')], max_length=128, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='brand',
            field=models.CharField(blank=True, choices=[('1', '幽兰'), ('2', '安杰玛'), ('90', '其他'), ('21', 'SPA'), ('22', '依娜'), ('23', '舒活特'), ('24', '蒋医生'), ('25', '美生美'), ('26', '黄教授'), ('27', '李正宇'), ('28', '惠秋'), ('29', '于教授'), ('30', '柏荟'), ('31', '米瑞可'), ('32', '海格'), ('33', '玉之光')], max_length=16, null=True, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='displayclass1',
            field=models.CharField(blank=True, choices=[('0', '正常'), ('1', '特价'), ('2', '活动')], default='', max_length=16, null=True, verbose_name='显示分类1'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='financeclass1',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='项目财务分类1'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='financeclass2',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='项目财务分类2'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='marketclass1',
            field=models.CharField(blank=True, choices=[('40', '挖客项目'), ('50', '深挖项目'), ('10', '拓客项目'), ('20', '留客项目')], default='', max_length=16, null=True, verbose_name='项目营销分类1'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='marketclass2',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='项目营销分类2'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='marketclass3',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='项目营销分类3'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('2010', '塑形'), ('2014', '脱毛'), ('2025', '仪器'), ('2020', '抗老化'), ('2021', '免疫提升'), ('2001', '补水'), ('2019', '抗衰'), ('2022', '排毒'), ('2004', '柔滑'), ('2016', '抗敏'), ('2008', '紧致'), ('2002', '去角质'), ('2011', '美化'), ('2007', '舒缓放松'), ('2015', '抗皱'), ('2024', '身体'), ('2018', '修护'), ('2003', '美白'), ('2026', '销售'), ('2013', '淡斑'), ('2005', '亮肤'), ('2099', '其他'), ('2023', '面部'), ('2017', '修复'), ('2009', '减内脂'), ('2012', '循环'), ('2006', '均衡肤色')], max_length=128, null=True, verbose_name='标签'),
        ),
    ]
