# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-17 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0049_auto_20190517_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionsdetail',
            name='promotionsid',
            field=models.CharField(blank=True, db_column='promotionsid', max_length=16, null=True),
        ),
    ]
