# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-17 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0051_promotionsdetail_promotionsgroupid'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionsgroupdetail',
            name='pgroupuuid',
            field=models.ForeignKey(blank=True, db_column='pgroupuuid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.Promotionsgroup'),
        ),
    ]
