# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-18 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0053_auto_20190517_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionsdetail',
            name='promotionsgroupid',
        ),
        migrations.AddField(
            model_name='promotions',
            name='promotionsgroupid',
            field=models.ForeignKey(blank=True, db_column='Promotionsgroupuuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Promotionsgroup'),
        ),
    ]
