# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-22 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0055_auto_20190522_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empl',
            name='status',
            field=models.CharField(blank=True, choices=[set(['在职', 'Y']), ('N', '离职')], max_length=8, null=True, verbose_name='是否在职'),
        ),
    ]
