# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-22 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0056_auto_20190522_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empl',
            name='status',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='是否在职'),
        ),
    ]
