# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-26 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0060_auto_20190525_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='vipcode',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
