# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-03 03:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0063_auto_20190603_1125'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='empl',
        #     name='id',
        #     field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='empl',
            name='uuid',
            field=models.UUIDField(primary_key=True, auto_created=True, blank=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='empl',
            name='company',
            field=models.CharField(blank=True, default='yfy', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='empl',
            name='creater',
            field=models.CharField(blank=True, default='anonymous', max_length=16, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='empl',
            name='storecode',
            field=models.CharField(blank=True, choices=[('00', '总部'), ('01', '丽迪亚店'), ('02', '军闯店'), ('03', '国际城店'), ('04', '天蕴店'), ('05', '信诚店')], max_length=16, null=True, verbose_name='所属门店'),
        ),

    ]
