# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-03 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0064_auto_20190603_1151'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='empl',
        #     name='id',
        # ),
        migrations.AlterField(
            model_name='empl',
            name='uuid',
            field=models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
