# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-14 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0070_auto_20190610_0824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'managed': True, 'verbose_name': '往来客户', 'verbose_name_plural': '往来客户'},
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='brand',
            field=models.CharField(blank=True, choices=[('YP', '药品'), ('300', '仪器'), ('XFL', '欣菲聆'), ('EB', 'EB'), ('XM', '禧满'), ('FZC', '法姿纯'), ('YDM', '伊蒂美'), ('JSM', '简诗美'), ('FML', '菲蜜丽'), ('RCYP', '日常用品'), ('HXM', '海皙曼'), ('QZ', '奇致'), ('SS', '手术'), ('BNJSL', '伯纳佳诗丽'), ('SY', '舒颜'), ('SR', '丝柔'), ('YHP', '易耗品'), ('ACWE', '爱驰维尔'), ('JBJS', '吉备酵素'), ('MLTS', '美丽天使'), ('MFMY', '美芾美源'), ('XBYZ', '细胞因子'), ('YDN', '伊杜娜'), ('CD', 'PCD'), ('BOSS', 'BOSS'), ('PCL', 'PCL'), ('GL', '刚伦'), ('PLD', '普拉朵'), ('QSN', '轻奢尼'), ('SH', '赛涵'), ('NM', '南明'), ('SL', '丝丽'), ('XBE', '旭贝尔-精油'), ('ANS', '安娜苏'), ('AEB', '奥尔滨（奥戴尔、奥比虹、FX、傲之美）'), ('BLQ', '贝丽清'), ('BLY', '博兰雅'), ('FEM', '法儿曼'), ('KYY', '科优研'), ('CPQT', '产品其他'), ('XSC', '芯丝翠'), ('LD', '朗顿'), ('BIO', 'BIO'), ('ZP', '赠品'), ('BOTOX', 'BOTOX'), ('NB', 'NB悦碧施'), ('ALW', '艾莉薇'), ('ANBS', '爱努碧斯'), ('ARD', '爱芮达'), ('AGAQ', '安格安晴'), ('AT', '奥肽'), ('BLLBY', '宝龄丽碧雅'), ('RL', '瑞蓝'), ('FSL', '法思丽'), ('FLJ', '菲洛嘉'), ('HW', '海薇'), ('KHT', '坤和堂（和坤堂）'), ('HT', '嗨体'), ('HL', '衡力'), ('JN', '珈纳'), ('JL', '姣兰'), ('JSY', '今生缘（金生缘）'), ('JB', '巨邦'), ('LJ', '朗健'), ('ZCWZX', '乔雅登'), ('RES', '瑞恩诗'), ('RJA', '瑞嘉奥'), ('RSM', '瑞诗美'), ('RBY', '润百颜（润白颜）'), ('RZ', '润致'), ('SM', '双美'), ('SD', '思蒂'), ('TNTL', '肽能天露'), ('WG', '维观'), ('XLK', '修丽可'), ('YMY', '研美颜'), ('YFQ', '伊肤泉'), ('YW', '伊婉'), ('YZQ', '益之泉'), ('YN', '英诺'), ('SMTH', '圣美天合-俞博士'), ('XZY', '雪之莹'), ('RLSM', '蕊丽'), ('LA', 'LA'), ('HSPOW', '韩式POW'), ('ZFX', '泽芙雪'), ('QT', '其他'), ('YKM', '易可美'), ('JX', '金炫')], max_length=16, null=True, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='displayclass1',
            field=models.CharField(blank=True, choices=[('储值卡', '储值卡'), ('YP', '药品'), ('300', '仪器'), ('XFL', '欣菲聆'), ('EB', 'EB'), ('XM', '禧满'), ('FZC', '法姿纯'), ('YDM', '伊蒂美'), ('JSM', '简诗美'), ('FML', '菲蜜丽'), ('RCYP', '日常用品'), ('HXM', '海皙曼'), ('QZ', '奇致'), ('SS', '手术'), ('BNJSL', '伯纳佳诗丽'), ('SY', '舒颜'), ('SR', '丝柔'), ('YHP', '易耗品'), ('ACWE', '爱驰维尔'), ('JBJS', '吉备酵素'), ('MLTS', '美丽天使'), ('MFMY', '美芾美源'), ('XBYZ', '细胞因子'), ('YDN', '伊杜娜'), ('CD', 'PCD'), ('BOSS', 'BOSS'), ('PCL', 'PCL'), ('GL', '刚伦'), ('PLD', '普拉朵'), ('QSN', '轻奢尼'), ('SH', '赛涵'), ('NM', '南明'), ('SL', '丝丽'), ('XBE', '旭贝尔-精油'), ('ANS', '安娜苏'), ('AEB', '奥尔滨（奥戴尔、奥比虹、FX、傲之美）'), ('AT', '奥肽'), ('BLQ', '贝丽清'), ('BLY', '博兰雅'), ('FEM', '法儿曼'), ('KYY', '科优研'), ('CPQT', '产品其他'), ('XSC', '芯丝翠'), ('LD', '朗顿'), ('BIO', 'BIO'), ('ZP', '赠品'), ('BOTOX', 'BOTOX'), ('NB', 'NB悦碧施'), ('ALW', '艾莉薇'), ('ANBS', '爱努碧斯'), ('ARD', '爱芮达'), ('AGAQ', '安格安晴'), ('AT', '奥肽'), ('BLLBY', '宝龄丽碧雅'), ('RL', '瑞蓝'), ('FSL', '法思丽'), ('FLJ', '菲洛嘉'), ('HW', '海薇'), ('KHT', '坤和堂（和坤堂）'), ('HT', '嗨体'), ('HL', '衡力'), ('JN', '珈纳'), ('JL', '姣兰'), ('JSY', '今生缘（金生缘）'), ('JB', '巨邦'), ('LJ', '朗健'), ('ZCWZX', '乔雅登'), ('RES', '瑞恩诗'), ('RJA', '瑞嘉奥'), ('RSM', '瑞诗美'), ('RBY', '润百颜（润白颜）'), ('RZ', '润致'), ('SM', '双美'), ('SD', '思蒂'), ('TNTL', '肽能天露'), ('WG', '维观'), ('XLK', '修丽可'), ('YMY', '研美颜'), ('YFQ', '伊肤泉'), ('YW', '伊婉'), ('YZQ', '益之泉'), ('YN', '英诺'), ('SMTH', '圣美天合-俞博士'), ('XZY', '雪之莹'), ('RLSM', '蕊丽'), ('LA', 'LA'), ('HSPOW', '韩式POW'), ('ZFX', '泽芙雪'), ('QT', '其他'), ('YKM', '易可美'), ('JX', '金炫'), ('100', '面部'), ('200', '身体'), ('500', '手术'), ('080', '口腔科'), ('产品卡', '产品卡'), ('400', '纹绣'), ('300', '仪器')], default='', max_length=16, null=True, verbose_name='显示分类（方法一）'),
        ),
        migrations.AlterField(
            model_name='empl',
            name='position',
            field=models.CharField(blank=True, choices=[('20', '顾问'), ('80', '其他'), ('50', '行政'), ('30', '收银'), ('10', '美容师'), ('40', '库管')], db_column='POSITION', max_length=20, null=True, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='brand',
            field=models.CharField(blank=True, choices=[('YP', '药品'), ('300', '仪器'), ('XFL', '欣菲聆'), ('EB', 'EB'), ('XM', '禧满'), ('FZC', '法姿纯'), ('YDM', '伊蒂美'), ('JSM', '简诗美'), ('FML', '菲蜜丽'), ('RCYP', '日常用品'), ('HXM', '海皙曼'), ('QZ', '奇致'), ('SS', '手术'), ('BNJSL', '伯纳佳诗丽'), ('SY', '舒颜'), ('SR', '丝柔'), ('YHP', '易耗品'), ('ACWE', '爱驰维尔'), ('JBJS', '吉备酵素'), ('MLTS', '美丽天使'), ('MFMY', '美芾美源'), ('XBYZ', '细胞因子'), ('YDN', '伊杜娜'), ('CD', 'PCD'), ('BOSS', 'BOSS'), ('PCL', 'PCL'), ('GL', '刚伦'), ('PLD', '普拉朵'), ('QSN', '轻奢尼'), ('SH', '赛涵'), ('NM', '南明'), ('SL', '丝丽'), ('XBE', '旭贝尔-精油'), ('ANS', '安娜苏'), ('AEB', '奥尔滨（奥戴尔、奥比虹、FX、傲之美）'), ('BLQ', '贝丽清'), ('BLY', '博兰雅'), ('FEM', '法儿曼'), ('KYY', '科优研'), ('CPQT', '产品其他'), ('XSC', '芯丝翠'), ('LD', '朗顿'), ('BIO', 'BIO'), ('ZP', '赠品'), ('BOTOX', 'BOTOX'), ('NB', 'NB悦碧施'), ('ALW', '艾莉薇'), ('ANBS', '爱努碧斯'), ('ARD', '爱芮达'), ('AGAQ', '安格安晴'), ('AT', '奥肽'), ('BLLBY', '宝龄丽碧雅'), ('RL', '瑞蓝'), ('FSL', '法思丽'), ('FLJ', '菲洛嘉'), ('HW', '海薇'), ('KHT', '坤和堂（和坤堂）'), ('HT', '嗨体'), ('HL', '衡力'), ('JN', '珈纳'), ('JL', '姣兰'), ('JSY', '今生缘（金生缘）'), ('JB', '巨邦'), ('LJ', '朗健'), ('ZCWZX', '乔雅登'), ('RES', '瑞恩诗'), ('RJA', '瑞嘉奥'), ('RSM', '瑞诗美'), ('RBY', '润百颜（润白颜）'), ('RZ', '润致'), ('SM', '双美'), ('SD', '思蒂'), ('TNTL', '肽能天露'), ('WG', '维观'), ('XLK', '修丽可'), ('YMY', '研美颜'), ('YFQ', '伊肤泉'), ('YW', '伊婉'), ('YZQ', '益之泉'), ('YN', '英诺'), ('SMTH', '圣美天合-俞博士'), ('XZY', '雪之莹'), ('RLSM', '蕊丽'), ('LA', 'LA'), ('HSPOW', '韩式POW'), ('ZFX', '泽芙雪'), ('QT', '其他'), ('YKM', '易可美'), ('JX', '金炫')], max_length=16, null=True, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='displayclass1',
            field=models.CharField(blank=True, choices=[('储值卡', '储值卡'), ('YP', '药品'), ('300', '仪器'), ('XFL', '欣菲聆'), ('EB', 'EB'), ('XM', '禧满'), ('FZC', '法姿纯'), ('YDM', '伊蒂美'), ('JSM', '简诗美'), ('FML', '菲蜜丽'), ('RCYP', '日常用品'), ('HXM', '海皙曼'), ('QZ', '奇致'), ('SS', '手术'), ('BNJSL', '伯纳佳诗丽'), ('SY', '舒颜'), ('SR', '丝柔'), ('YHP', '易耗品'), ('ACWE', '爱驰维尔'), ('JBJS', '吉备酵素'), ('MLTS', '美丽天使'), ('MFMY', '美芾美源'), ('XBYZ', '细胞因子'), ('YDN', '伊杜娜'), ('CD', 'PCD'), ('BOSS', 'BOSS'), ('PCL', 'PCL'), ('GL', '刚伦'), ('PLD', '普拉朵'), ('QSN', '轻奢尼'), ('SH', '赛涵'), ('NM', '南明'), ('SL', '丝丽'), ('XBE', '旭贝尔-精油'), ('ANS', '安娜苏'), ('AEB', '奥尔滨（奥戴尔、奥比虹、FX、傲之美）'), ('AT', '奥肽'), ('BLQ', '贝丽清'), ('BLY', '博兰雅'), ('FEM', '法儿曼'), ('KYY', '科优研'), ('CPQT', '产品其他'), ('XSC', '芯丝翠'), ('LD', '朗顿'), ('BIO', 'BIO'), ('ZP', '赠品'), ('BOTOX', 'BOTOX'), ('NB', 'NB悦碧施'), ('ALW', '艾莉薇'), ('ANBS', '爱努碧斯'), ('ARD', '爱芮达'), ('AGAQ', '安格安晴'), ('AT', '奥肽'), ('BLLBY', '宝龄丽碧雅'), ('RL', '瑞蓝'), ('FSL', '法思丽'), ('FLJ', '菲洛嘉'), ('HW', '海薇'), ('KHT', '坤和堂（和坤堂）'), ('HT', '嗨体'), ('HL', '衡力'), ('JN', '珈纳'), ('JL', '姣兰'), ('JSY', '今生缘（金生缘）'), ('JB', '巨邦'), ('LJ', '朗健'), ('ZCWZX', '乔雅登'), ('RES', '瑞恩诗'), ('RJA', '瑞嘉奥'), ('RSM', '瑞诗美'), ('RBY', '润百颜（润白颜）'), ('RZ', '润致'), ('SM', '双美'), ('SD', '思蒂'), ('TNTL', '肽能天露'), ('WG', '维观'), ('XLK', '修丽可'), ('YMY', '研美颜'), ('YFQ', '伊肤泉'), ('YW', '伊婉'), ('YZQ', '益之泉'), ('YN', '英诺'), ('SMTH', '圣美天合-俞博士'), ('XZY', '雪之莹'), ('RLSM', '蕊丽'), ('LA', 'LA'), ('HSPOW', '韩式POW'), ('ZFX', '泽芙雪'), ('QT', '其他'), ('YKM', '易可美'), ('JX', '金炫'), ('100', '面部'), ('200', '身体'), ('500', '手术'), ('080', '口腔科'), ('产品卡', '产品卡'), ('400', '纹绣'), ('300', '仪器')], default='', max_length=16, null=True, verbose_name='显示分类（方法一）'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goodsct',
            field=models.CharField(blank=True, choices=[('10', '8折产品'), ('20', '原价不打折产品')], db_column='goodsct', max_length=16, null=True, verbose_name='商品折扣分类'),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, choices=[('YP', '药品'), ('300', '仪器'), ('XFL', '欣菲聆'), ('EB', 'EB'), ('XM', '禧满'), ('FZC', '法姿纯'), ('YDM', '伊蒂美'), ('JSM', '简诗美'), ('FML', '菲蜜丽'), ('RCYP', '日常用品'), ('HXM', '海皙曼'), ('QZ', '奇致'), ('SS', '手术'), ('BNJSL', '伯纳佳诗丽'), ('SY', '舒颜'), ('SR', '丝柔'), ('YHP', '易耗品'), ('ACWE', '爱驰维尔'), ('JBJS', '吉备酵素'), ('MLTS', '美丽天使'), ('MFMY', '美芾美源'), ('XBYZ', '细胞因子'), ('YDN', '伊杜娜'), ('CD', 'PCD'), ('BOSS', 'BOSS'), ('PCL', 'PCL'), ('GL', '刚伦'), ('PLD', '普拉朵'), ('QSN', '轻奢尼'), ('SH', '赛涵'), ('NM', '南明'), ('SL', '丝丽'), ('XBE', '旭贝尔-精油'), ('ANS', '安娜苏'), ('AEB', '奥尔滨（奥戴尔、奥比虹、FX、傲之美）'), ('BLQ', '贝丽清'), ('BLY', '博兰雅'), ('FEM', '法儿曼'), ('KYY', '科优研'), ('CPQT', '产品其他'), ('XSC', '芯丝翠'), ('LD', '朗顿'), ('BIO', 'BIO'), ('ZP', '赠品'), ('BOTOX', 'BOTOX'), ('NB', 'NB悦碧施'), ('ALW', '艾莉薇'), ('ANBS', '爱努碧斯'), ('ARD', '爱芮达'), ('AGAQ', '安格安晴'), ('AT', '奥肽'), ('BLLBY', '宝龄丽碧雅'), ('RL', '瑞蓝'), ('FSL', '法思丽'), ('FLJ', '菲洛嘉'), ('HW', '海薇'), ('KHT', '坤和堂（和坤堂）'), ('HT', '嗨体'), ('HL', '衡力'), ('JN', '珈纳'), ('JL', '姣兰'), ('JSY', '今生缘（金生缘）'), ('JB', '巨邦'), ('LJ', '朗健'), ('ZCWZX', '乔雅登'), ('RES', '瑞恩诗'), ('RJA', '瑞嘉奥'), ('RSM', '瑞诗美'), ('RBY', '润百颜（润白颜）'), ('RZ', '润致'), ('SM', '双美'), ('SD', '思蒂'), ('TNTL', '肽能天露'), ('WG', '维观'), ('XLK', '修丽可'), ('YMY', '研美颜'), ('YFQ', '伊肤泉'), ('YW', '伊婉'), ('YZQ', '益之泉'), ('YN', '英诺'), ('SMTH', '圣美天合-俞博士'), ('XZY', '雪之莹'), ('RLSM', '蕊丽'), ('LA', 'LA'), ('HSPOW', '韩式POW'), ('ZFX', '泽芙雪'), ('QT', '其他'), ('YKM', '易可美'), ('JX', '金炫')], max_length=16, null=True, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='item',
            name='displayclass1',
            field=models.CharField(blank=True, choices=[('储值卡', '储值卡'), ('YP', '药品'), ('300', '仪器'), ('XFL', '欣菲聆'), ('EB', 'EB'), ('XM', '禧满'), ('FZC', '法姿纯'), ('YDM', '伊蒂美'), ('JSM', '简诗美'), ('FML', '菲蜜丽'), ('RCYP', '日常用品'), ('HXM', '海皙曼'), ('QZ', '奇致'), ('SS', '手术'), ('BNJSL', '伯纳佳诗丽'), ('SY', '舒颜'), ('SR', '丝柔'), ('YHP', '易耗品'), ('ACWE', '爱驰维尔'), ('JBJS', '吉备酵素'), ('MLTS', '美丽天使'), ('MFMY', '美芾美源'), ('XBYZ', '细胞因子'), ('YDN', '伊杜娜'), ('CD', 'PCD'), ('BOSS', 'BOSS'), ('PCL', 'PCL'), ('GL', '刚伦'), ('PLD', '普拉朵'), ('QSN', '轻奢尼'), ('SH', '赛涵'), ('NM', '南明'), ('SL', '丝丽'), ('XBE', '旭贝尔-精油'), ('ANS', '安娜苏'), ('AEB', '奥尔滨（奥戴尔、奥比虹、FX、傲之美）'), ('AT', '奥肽'), ('BLQ', '贝丽清'), ('BLY', '博兰雅'), ('FEM', '法儿曼'), ('KYY', '科优研'), ('CPQT', '产品其他'), ('XSC', '芯丝翠'), ('LD', '朗顿'), ('BIO', 'BIO'), ('ZP', '赠品'), ('BOTOX', 'BOTOX'), ('NB', 'NB悦碧施'), ('ALW', '艾莉薇'), ('ANBS', '爱努碧斯'), ('ARD', '爱芮达'), ('AGAQ', '安格安晴'), ('AT', '奥肽'), ('BLLBY', '宝龄丽碧雅'), ('RL', '瑞蓝'), ('FSL', '法思丽'), ('FLJ', '菲洛嘉'), ('HW', '海薇'), ('KHT', '坤和堂（和坤堂）'), ('HT', '嗨体'), ('HL', '衡力'), ('JN', '珈纳'), ('JL', '姣兰'), ('JSY', '今生缘（金生缘）'), ('JB', '巨邦'), ('LJ', '朗健'), ('ZCWZX', '乔雅登'), ('RES', '瑞恩诗'), ('RJA', '瑞嘉奥'), ('RSM', '瑞诗美'), ('RBY', '润百颜（润白颜）'), ('RZ', '润致'), ('SM', '双美'), ('SD', '思蒂'), ('TNTL', '肽能天露'), ('WG', '维观'), ('XLK', '修丽可'), ('YMY', '研美颜'), ('YFQ', '伊肤泉'), ('YW', '伊婉'), ('YZQ', '益之泉'), ('YN', '英诺'), ('SMTH', '圣美天合-俞博士'), ('XZY', '雪之莹'), ('RLSM', '蕊丽'), ('LA', 'LA'), ('HSPOW', '韩式POW'), ('ZFX', '泽芙雪'), ('QT', '其他'), ('YKM', '易可美'), ('JX', '金炫'), ('100', '面部'), ('200', '身体'), ('500', '手术'), ('080', '口腔科'), ('产品卡', '产品卡'), ('400', '纹绣'), ('300', '仪器')], default='', max_length=16, null=True, verbose_name='显示分类（方法一）'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='brand',
            field=models.CharField(blank=True, choices=[('YP', '药品'), ('300', '仪器'), ('XFL', '欣菲聆'), ('EB', 'EB'), ('XM', '禧满'), ('FZC', '法姿纯'), ('YDM', '伊蒂美'), ('JSM', '简诗美'), ('FML', '菲蜜丽'), ('RCYP', '日常用品'), ('HXM', '海皙曼'), ('QZ', '奇致'), ('SS', '手术'), ('BNJSL', '伯纳佳诗丽'), ('SY', '舒颜'), ('SR', '丝柔'), ('YHP', '易耗品'), ('ACWE', '爱驰维尔'), ('JBJS', '吉备酵素'), ('MLTS', '美丽天使'), ('MFMY', '美芾美源'), ('XBYZ', '细胞因子'), ('YDN', '伊杜娜'), ('CD', 'PCD'), ('BOSS', 'BOSS'), ('PCL', 'PCL'), ('GL', '刚伦'), ('PLD', '普拉朵'), ('QSN', '轻奢尼'), ('SH', '赛涵'), ('NM', '南明'), ('SL', '丝丽'), ('XBE', '旭贝尔-精油'), ('ANS', '安娜苏'), ('AEB', '奥尔滨（奥戴尔、奥比虹、FX、傲之美）'), ('BLQ', '贝丽清'), ('BLY', '博兰雅'), ('FEM', '法儿曼'), ('KYY', '科优研'), ('CPQT', '产品其他'), ('XSC', '芯丝翠'), ('LD', '朗顿'), ('BIO', 'BIO'), ('ZP', '赠品'), ('BOTOX', 'BOTOX'), ('NB', 'NB悦碧施'), ('ALW', '艾莉薇'), ('ANBS', '爱努碧斯'), ('ARD', '爱芮达'), ('AGAQ', '安格安晴'), ('AT', '奥肽'), ('BLLBY', '宝龄丽碧雅'), ('RL', '瑞蓝'), ('FSL', '法思丽'), ('FLJ', '菲洛嘉'), ('HW', '海薇'), ('KHT', '坤和堂（和坤堂）'), ('HT', '嗨体'), ('HL', '衡力'), ('JN', '珈纳'), ('JL', '姣兰'), ('JSY', '今生缘（金生缘）'), ('JB', '巨邦'), ('LJ', '朗健'), ('ZCWZX', '乔雅登'), ('RES', '瑞恩诗'), ('RJA', '瑞嘉奥'), ('RSM', '瑞诗美'), ('RBY', '润百颜（润白颜）'), ('RZ', '润致'), ('SM', '双美'), ('SD', '思蒂'), ('TNTL', '肽能天露'), ('WG', '维观'), ('XLK', '修丽可'), ('YMY', '研美颜'), ('YFQ', '伊肤泉'), ('YW', '伊婉'), ('YZQ', '益之泉'), ('YN', '英诺'), ('SMTH', '圣美天合-俞博士'), ('XZY', '雪之莹'), ('RLSM', '蕊丽'), ('LA', 'LA'), ('HSPOW', '韩式POW'), ('ZFX', '泽芙雪'), ('QT', '其他'), ('YKM', '易可美'), ('JX', '金炫')], max_length=16, null=True, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='displayclass1',
            field=models.CharField(blank=True, choices=[('储值卡', '储值卡'), ('YP', '药品'), ('300', '仪器'), ('XFL', '欣菲聆'), ('EB', 'EB'), ('XM', '禧满'), ('FZC', '法姿纯'), ('YDM', '伊蒂美'), ('JSM', '简诗美'), ('FML', '菲蜜丽'), ('RCYP', '日常用品'), ('HXM', '海皙曼'), ('QZ', '奇致'), ('SS', '手术'), ('BNJSL', '伯纳佳诗丽'), ('SY', '舒颜'), ('SR', '丝柔'), ('YHP', '易耗品'), ('ACWE', '爱驰维尔'), ('JBJS', '吉备酵素'), ('MLTS', '美丽天使'), ('MFMY', '美芾美源'), ('XBYZ', '细胞因子'), ('YDN', '伊杜娜'), ('CD', 'PCD'), ('BOSS', 'BOSS'), ('PCL', 'PCL'), ('GL', '刚伦'), ('PLD', '普拉朵'), ('QSN', '轻奢尼'), ('SH', '赛涵'), ('NM', '南明'), ('SL', '丝丽'), ('XBE', '旭贝尔-精油'), ('ANS', '安娜苏'), ('AEB', '奥尔滨（奥戴尔、奥比虹、FX、傲之美）'), ('AT', '奥肽'), ('BLQ', '贝丽清'), ('BLY', '博兰雅'), ('FEM', '法儿曼'), ('KYY', '科优研'), ('CPQT', '产品其他'), ('XSC', '芯丝翠'), ('LD', '朗顿'), ('BIO', 'BIO'), ('ZP', '赠品'), ('BOTOX', 'BOTOX'), ('NB', 'NB悦碧施'), ('ALW', '艾莉薇'), ('ANBS', '爱努碧斯'), ('ARD', '爱芮达'), ('AGAQ', '安格安晴'), ('AT', '奥肽'), ('BLLBY', '宝龄丽碧雅'), ('RL', '瑞蓝'), ('FSL', '法思丽'), ('FLJ', '菲洛嘉'), ('HW', '海薇'), ('KHT', '坤和堂（和坤堂）'), ('HT', '嗨体'), ('HL', '衡力'), ('JN', '珈纳'), ('JL', '姣兰'), ('JSY', '今生缘（金生缘）'), ('JB', '巨邦'), ('LJ', '朗健'), ('ZCWZX', '乔雅登'), ('RES', '瑞恩诗'), ('RJA', '瑞嘉奥'), ('RSM', '瑞诗美'), ('RBY', '润百颜（润白颜）'), ('RZ', '润致'), ('SM', '双美'), ('SD', '思蒂'), ('TNTL', '肽能天露'), ('WG', '维观'), ('XLK', '修丽可'), ('YMY', '研美颜'), ('YFQ', '伊肤泉'), ('YW', '伊婉'), ('YZQ', '益之泉'), ('YN', '英诺'), ('SMTH', '圣美天合-俞博士'), ('XZY', '雪之莹'), ('RLSM', '蕊丽'), ('LA', 'LA'), ('HSPOW', '韩式POW'), ('ZFX', '泽芙雪'), ('QT', '其他'), ('YKM', '易可美'), ('JX', '金炫'), ('100', '面部'), ('200', '身体'), ('500', '手术'), ('080', '口腔科'), ('产品卡', '产品卡'), ('400', '纹绣'), ('300', '仪器')], default='', max_length=16, null=True, verbose_name='显示分类（方法一）'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplierid',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='往来客户编号'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='suppliername',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='往来客户名称'),
        ),
    ]
