# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-20 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0075_auto_20190712_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinfo',
            name='hdflag',
            field=models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='N', max_length=8, null=True,
                                   verbose_name='是否总部'),
        ),

        migrations.AlterUniqueTogether(
            name='serviece',
            unique_together=set([('company', 'svrcdoe')]),
        ),
    ]
