# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-26 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0077_auto_20190724_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtype',
            name='leftmoney',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name='可用金额'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='source',
            field=models.CharField(blank=True, choices=[('09', '活动'), ('07', '微博'), ('08', 'APP'), ('02', '网电'), ('06', '朋友介绍'), ('01', '自然'), ('03', '驻场'), ('05', '三方平台'), ('04', '美团')], max_length=32, null=True, verbose_name='来店渠道'),
        ),
    ]
