# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-04 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0083_auto_20190804_2004'),
    ]

    operations = [

    ]
