# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-10 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0088_auto_20190810_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empl',
            name='storecode',
            field=models.CharField(blank=True, choices=[('00', '总部'), ('01', '丽迪亚店'), ('02', '军创店'), ('03', '国际城店'), ('04', '天蕴店'), ('05', '信诚店'), ('88', '练习')], max_length=16, null=True, verbose_name='所属门店'),
        ),
        migrations.AlterField(
            model_name='hdsysuser',
            name='storelist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('00', '总部'), ('01', '丽迪亚店'), ('02', '军创店'), ('03', '国际城店'), ('04', '天蕴店'), ('05', '信诚店'), ('88', '练习')], max_length=128, null=True, verbose_name='可用门店'),
        ),
    ]
