# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-03 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0095_auto_20190927_1246'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='vip',
        #     old_name='referrername',
        #     new_name='referrervcode',
        # ),
    ]
