# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-04 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0096_auto_20191003_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vip',
            old_name='referrername',
            new_name='referrervcode',
        ),
        migrations.AddField(
            model_name='hdsysuser',
            name='sys_idtype',
            field=models.CharField(blank=True, choices=[('10', '员工登陆号'), ('80', '员工岗位')], default='10', max_length=32, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='cardsupertype',
            name='pcode',
            field=models.CharField(blank=True, choices=[('A', '现金'), ('A1', '银联'), ('A2', '支付宝'), ('A3', '微信'), ('A4', '美团'), ('A5', '大众点评'), ('A6', '盛付通'), ('B', '储值卡付'), ('B1', '疗程卡付'), ('Z', '免单/赠送'), ('Z1', '赠送储值卡付'), ('Z2', '赠送疗程卡付'), ('Z3', '入会礼金'), ('Z4', '生日礼金'), ('Z5', '金币支付'), ('Z9', '转卡')], max_length=16, null=True, verbose_name='对应付款方式'),
        ),
    ]
