# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-08 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0097_auto_20191004_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivementRuler',
            fields=[
                ('last_modified', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间')),
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('creater', models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者')),
                ('flag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除')),
                ('company', models.CharField(blank=True, default='yiren', editable=False, max_length=8, null=True, verbose_name='公司')),
                ('storecode', models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店')),
                ('archivementclass1', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='业绩分类1')),
                ('archivementclass2', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='业绩分类2')),
                ('basenumtype', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='提成计算基数类型')),
                ('frombasenum', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='提成计算基数起始金额')),
                ('tobasenum', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='提成计算基数截止金额')),
                ('tichengperc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='提成比例')),
                ('tichengbase', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='提成速算基数')),
            ],
            options={
                'verbose_name': '提成规则',
                'verbose_name_plural': '提成规则',
                'db_table': 'archivementruler',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cardtype',
            name='archivementclass1',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='业绩分类1'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='archivementclass2',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='业绩分类2'),
        ),
        migrations.AddField(
            model_name='goods',
            name='archivementclass1',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='业绩分类1'),
        ),
        migrations.AddField(
            model_name='goods',
            name='archivementclass2',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='业绩分类2'),
        ),
        migrations.AddField(
            model_name='item',
            name='archivementclass1',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='业绩分类1'),
        ),
        migrations.AddField(
            model_name='item',
            name='archivementclass2',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='业绩分类2'),
        ),
        migrations.AddField(
            model_name='serviece',
            name='archivementclass1',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='业绩分类1'),
        ),
        migrations.AddField(
            model_name='serviece',
            name='archivementclass2',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='业绩分类2'),
        ),
    ]
