# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-09 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0100_auto_20191009_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivementruler',
            name='basenumtype',
            field=models.CharField(blank=True, choices=[('10', '简易式'), ('20', '阶梯式')], default='10', max_length=16, null=True, verbose_name='提成计算基数类型'),
        ),
    ]
