# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-12 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0104_auto_20191009_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivementruler',
            name='archivementclass1',
            field=models.CharField(blank=True, choices=[('200', '身体'), ('610', '产品'), ('300', '仪器'), ('500', '手术'), ('400', '纹绣'), ('600', '保健品'), ('100', '面部')], default='', max_length=16, null=True, verbose_name='业绩分类1'),
        ),
        migrations.AlterField(
            model_name='archivementruler',
            name='basenumtype',
            field=models.CharField(blank=True, choices=[('10', '实操'), ('20', '业绩'), ('30', '积点')], default='10', max_length=16, null=True, verbose_name='提成计算基数类型'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='archivementclass1',
            field=models.CharField(blank=True, choices=[('200', '身体'), ('610', '产品'), ('300', '仪器'), ('500', '手术'), ('400', '纹绣'), ('600', '保健品'), ('100', '面部')], default='', max_length=16, null=True, verbose_name='业绩分类1'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='archivementclass1',
            field=models.CharField(blank=True, choices=[('200', '身体'), ('610', '产品'), ('300', '仪器'), ('500', '手术'), ('400', '纹绣'), ('600', '保健品'), ('100', '面部')], default='', max_length=16, null=True, verbose_name='业绩分类1'),
        ),
        migrations.AlterField(
            model_name='item',
            name='archivementclass1',
            field=models.CharField(blank=True, choices=[('200', '身体'), ('610', '产品'), ('300', '仪器'), ('500', '手术'), ('400', '纹绣'), ('600', '保健品'), ('100', '面部')], default='', max_length=16, null=True, verbose_name='业绩分类1'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='archivementclass1',
            field=models.CharField(blank=True, choices=[('200', '身体'), ('610', '产品'), ('300', '仪器'), ('500', '手术'), ('400', '纹绣'), ('600', '保健品'), ('100', '面部')], default='', max_length=16, null=True, verbose_name='业绩分类1'),
        ),
    ]
