# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-04 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0106_auto_20191101_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='empl',
            name='openid',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='微信openid'),
        ),
        migrations.AddField(
            model_name='empl',
            name='unionid',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='微信unionid'),
        ),
        migrations.AddField(
            model_name='vip',
            name='openid',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='微信openid'),
        ),
        migrations.AddField(
            model_name='vip',
            name='unionid',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='微信unionid'),
        ),
    ]
