# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-30 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0113_auto_20191130_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinfo',
            name='uuid',
            field=models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
