# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-14 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0115_auto_20191214_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinfo',
            name='measureofarea',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=16, null=True, verbose_name='经营面积'),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='pmcodes',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=8, null=True, verbose_name='顾问人数'),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='rooms',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=16, null=True, verbose_name='房间数'),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='seccodes',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=8, null=True, verbose_name='美疗师人数'),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='validyvipcnt',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=8, null=True, verbose_name='有效会员数'),
        ),
    ]
