# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-15 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0116_auto_20191214_2205'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cardtype',
            unique_together=set([('company', 'cardtype')]),
        ),
    ]
