# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-15 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0118_auto_20191215_0743'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymode',
            unique_together=set([('company', 'pcode')]),
        ),
        migrations.AlterUniqueTogether(
            name='wharehouse',
            unique_together=set([('company', 'wharehousecode')]),
        ),
    ]
