# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-01 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0124_remove_vipspecialdate_vipuuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipspecialdate',
            name='vipuuid',
            field=models.ForeignKey(blank=True, db_column='vipuuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Vip', verbose_name='会员'),
        ),
    ]
