# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-01 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0126_auto_20200201_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipSpecialDate',
            fields=[
                ('last_modified', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间')),
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('creater', models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者')),
                ('flag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除')),
                ('company', models.CharField(blank=True, default='yiren', editable=False, max_length=8, null=True, verbose_name='公司')),
                ('storecode', models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店')),
                ('vipuuid', models.ForeignKey(blank=True, db_column='vipuuid', null=True,
                                              on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Vip',
                                              verbose_name='会员')),
                ('vcode', models.CharField(blank=True, max_length=16, null=True, verbose_name='会员号')),
                ('specdatetype', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='日期类型')),
                ('lunarcalendarflag', models.CharField(blank=True, default='N', max_length=16, null=True, verbose_name='是否阴历')),
                ('specdate', models.CharField(blank=True, max_length=16, null=True, verbose_name='特殊日期')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
            ],
            options={
                'managed': True,
                'verbose_name_plural': '客人特别日',
                'verbose_name': '客人特别日',
                'db_table': 'vipspecicaldate',
            },
        ),
    ]
