# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-06 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0129_auto_20200401_0845'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='goods',
        #     name='large_image',
        #     field=models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='示例图片-大'),
        # ),
        migrations.AddField(
            model_name='goods',
            name='saleschannels',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('10', '线下门店销售'), ('20', '线上销售')], max_length=128, null=True, verbose_name='销售渠道'),
        ),
        migrations.AddField(
            model_name='goods',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='示例图片-小'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='desc1',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='商品描述1'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='desc2',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='商品描述2'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='desc3',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='商品描述3'),
        ),
    ]
