# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-02 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0130_auto_20200406_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='large_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='示例图片-大'),
        ),
    ]
