# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-02-02 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0142_auto_20210202_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardsupertype',
            old_name='presen_pcode',
            new_name='present_pcode',
        ),
    ]
