# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-03-07 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0146_auto_20210306_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
