# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-03-19 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0149_auto_20210319_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsupertype',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='cardsupertype',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='cardsupertype',
            name='normal_pcode',
            field=models.CharField(blank=True, choices=[('A', '现金'), ('A010', '银行卡'), ('A020', '支票'), ('A030', '店微信'), ('B', '储值卡付'), ('B010', '疗程卡付'), ('B020', '家居卡付'), ('B030', '即时卡付'), ('I', '储值积分卡赠送'), ('J', '活动积分卡赠送'), ('Z', '免单/赠送'), ('Z010', '管理卡赠送')], max_length=16, null=True, verbose_name='正常对应付款方式'),
        ),
        migrations.AlterField(
            model_name='cardsupertype',
            name='pcode',
            field=models.CharField(blank=True, choices=[('A', '现金'), ('A010', '银行卡'), ('A020', '支票'), ('A030', '店微信'), ('B', '储值卡付'), ('B010', '疗程卡付'), ('B020', '家居卡付'), ('B030', '即时卡付'), ('I', '储值积分卡赠送'), ('J', '活动积分卡赠送'), ('Z', '免单/赠送'), ('Z010', '管理卡赠送')], max_length=16, null=True, verbose_name='默认付款方式'),
        ),
        migrations.AlterField(
            model_name='cardsupertype',
            name='present_pcode',
            field=models.CharField(blank=True, choices=[('A', '现金'), ('A010', '银行卡'), ('A020', '支票'), ('A030', '店微信'), ('B', '储值卡付'), ('B010', '疗程卡付'), ('B020', '家居卡付'), ('B030', '即时卡付'), ('I', '储值积分卡赠送'), ('J', '活动积分卡赠送'), ('Z', '免单/赠送'), ('Z010', '管理卡赠送')], max_length=16, null=True, verbose_name='赠送对应付款方式'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='brand',
            field=models.CharField(blank=True, choices=[('001', '元馔'), ('003', '原液之谜'), ('001', '操作'), ('001', '即时副卡'), ('002', '养生')], max_length=16, null=True, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='displayclass1',
            field=models.CharField(blank=True, choices=[('006', '6'), ('003', '家居/商品'), ('001', '储值'), ('004', '即时'), ('002', '服务/疗程'), ('005', '5')], default='', max_length=16, null=True, verbose_name='显示分类（方法一）'),
        ),
        migrations.AlterField(
            model_name='empl',
            name='team',
            field=models.CharField(blank=True, choices=[('1', '滞销')], max_length=16, null=True, verbose_name='业务组别'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='brand',
            field=models.CharField(blank=True, choices=[('001', '元馔'), ('003', '原液之谜'), ('001', '操作'), ('001', '即时副卡'), ('002', '养生')], max_length=16, null=True, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='displayclass1',
            field=models.CharField(blank=True, choices=[('006', '6'), ('003', '家居/商品'), ('001', '储值'), ('004', '即时'), ('002', '服务/疗程'), ('005', '5')], default='', max_length=16, null=True, verbose_name='显示分类（方法一）'),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, choices=[('001', '元馔'), ('003', '原液之谜'), ('001', '操作'), ('001', '即时副卡'), ('002', '养生')], max_length=16, null=True, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='item',
            name='displayclass1',
            field=models.CharField(blank=True, choices=[('006', '6'), ('003', '家居/商品'), ('001', '储值'), ('004', '即时'), ('002', '服务/疗程'), ('005', '5')], default='', max_length=16, null=True, verbose_name='显示分类（方法一）'),
        ),
        migrations.AlterField(
            model_name='promotionsdetail',
            name='sgcode',
            field=models.CharField(blank=True, choices=[('2000000', '即时护肤全套'), ('2000003', '微电流面部'), ('2100000', '脂肪专家')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='brand',
            field=models.CharField(blank=True, choices=[('001', '元馔'), ('003', '原液之谜'), ('001', '操作'), ('001', '即时副卡'), ('002', '养生')], max_length=16, null=True, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='displayclass1',
            field=models.CharField(blank=True, choices=[('006', '6'), ('003', '家居/商品'), ('001', '储值'), ('004', '即时'), ('002', '服务/疗程'), ('005', '5')], default='', max_length=16, null=True, verbose_name='显示分类（方法一）'),
        ),
        migrations.AlterField(
            model_name='servieceprice',
            name='srvuuid',
            field=models.ForeignKey(blank=True, db_column='srvuuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Serviece', verbose_name='服务项目'),
        ),
        migrations.AlterField(
            model_name='wharehouse',
            name='storecode',
            field=models.CharField(blank=True, choices=[('00', '总部'), ('88', '练习')], max_length=16, null=True, verbose_name='所属店铺'),
        ),
    ]
