# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-03-28 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0151_auto_20210325_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsupertype',
            name='normal_pcode',
            field=models.CharField(blank=True, choices=[('6134000', '店微信'), ('6134101', '现金'), ('6134203', '银行卡'), ('6134304', '支票'), ('B', '储值卡付'), ('B010', '疗程卡付'), ('B020', '家居卡付'), ('B030', '即时卡付'), ('I', '储值积分卡赠送'), ('J', '活动积分卡赠送'), ('Z', '免单/赠送'), ('Z010', '管理卡赠送')], max_length=16, null=True, verbose_name='正常对应付款方式'),
        ),
        migrations.AlterField(
            model_name='cardsupertype',
            name='pcode',
            field=models.CharField(blank=True, choices=[('6134000', '店微信'), ('6134101', '现金'), ('6134203', '银行卡'), ('6134304', '支票'), ('B', '储值卡付'), ('B010', '疗程卡付'), ('B020', '家居卡付'), ('B030', '即时卡付'), ('I', '储值积分卡赠送'), ('J', '活动积分卡赠送'), ('Z', '免单/赠送'), ('Z010', '管理卡赠送')], max_length=16, null=True, verbose_name='默认付款方式'),
        ),
        migrations.AlterField(
            model_name='cardsupertype',
            name='present_pcode',
            field=models.CharField(blank=True, choices=[('6134000', '店微信'), ('6134101', '现金'), ('6134203', '银行卡'), ('6134304', '支票'), ('B', '储值卡付'), ('B010', '疗程卡付'), ('B020', '家居卡付'), ('B030', '即时卡付'), ('I', '储值积分卡赠送'), ('J', '活动积分卡赠送'), ('Z', '免单/赠送'), ('Z010', '管理卡赠送')], max_length=16, null=True, verbose_name='赠送对应付款方式'),
        ),
    ]
