# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-03-30 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0152_auto_20210328_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsupertype',
            name='code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='编号'),
        ),
    ]
