# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-04-05 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0153_auto_20210330_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='wharehouse',
            name='saleatr',
            field=models.CharField(blank=True, choices=[('G', '销售'), ('TO', '转出'), ('TI', '转入'), ('I', '进货'), ('F', '出货'), ('ZT', '自提'), ('U', '领用'), ('C', '盘点'), ('M', '邮寄')], max_length=16, null=True, verbose_name='允许操作'),
        ),
        migrations.AlterField(
            model_name='archivementruler',
            name='position',
            field=models.CharField(blank=True, choices=[('01', '运营主管'), ('02', '培训师'), ('020', '高级培训师'), ('021', '中级培训师'), ('022', '初级培训师'), ('03', '店长'), ('030', '高级店长'), ('031', '中级店长'), ('032', '初级店长'), ('04', '项目顾问'), ('040', '高级项目顾问'), ('041', '中级项目顾问'), ('042', '初级项目顾问'), ('05', '操作师'), ('06', '运营'), ('060', '运营店长'), ('061', '运营助理'), ('07', '服务'), ('070', '保洁主管'), ('071', '保洁'), ('08', '学员'), ('080', '运营助理学员'), ('081', '操作师学员'), ('10', '系统管理员'), ('12', '物流'), ('120', '物流调拨'), ('121', '物流库'), ('122', '采购'), ('13', '财务'), ('130', '财务调拨'), ('131', '财务库'), ('14', '人事'), ('140', '人事主管'), ('141', '人事助理'), ('15', '后台运营')], max_length=16, null=True, verbose_name='岗位'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('10003', '主推'), ('10001', '新品'), ('10002', '滞销')], max_length=128, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='empl',
            name='position',
            field=models.CharField(blank=True, choices=[('01', '运营主管'), ('02', '培训师'), ('020', '高级培训师'), ('021', '中级培训师'), ('022', '初级培训师'), ('03', '店长'), ('030', '高级店长'), ('031', '中级店长'), ('032', '初级店长'), ('04', '项目顾问'), ('040', '高级项目顾问'), ('041', '中级项目顾问'), ('042', '初级项目顾问'), ('05', '操作师'), ('06', '运营'), ('060', '运营店长'), ('061', '运营助理'), ('07', '服务'), ('070', '保洁主管'), ('071', '保洁'), ('08', '学员'), ('080', '运营助理学员'), ('081', '操作师学员'), ('10', '系统管理员'), ('12', '物流'), ('120', '物流调拨'), ('121', '物流库'), ('122', '采购'), ('13', '财务'), ('130', '财务调拨'), ('131', '财务库'), ('14', '人事'), ('140', '人事主管'), ('141', '人事助理'), ('15', '后台运营')], db_column='POSITION', max_length=20, null=True, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('10003', '主推'), ('10001', '新品'), ('10002', '滞销')], max_length=128, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='unit',
            field=models.CharField(blank=True, choices=[('51', '个'), ('60', '斤'), ('67', '片'), ('63', '双'), ('54', '袋'), ('70', '份'), ('66', '副'), ('55', '张'), ('50', '套'), ('65', '本'), ('52', '台'), ('68', '条'), ('69', '桶'), ('30', '瓶'), ('40', '支'), ('61', '包'), ('10', 'ml'), ('62', '件'), ('64', '对'), ('53', '盒'), ('20', 'g'), ('90', '元')], db_column='UNIT', default='10', max_length=10, null=True, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('10003', '主推'), ('10001', '新品'), ('10002', '滞销')], max_length=128, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='serviece',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('10003', '主推'), ('10001', '新品'), ('10002', '滞销')], max_length=128, null=True, verbose_name='标签'),
        ),
    ]
