# Generated by Django 3.2.18 on 2026-05-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_auto_20210711_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='wifilist',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
    ]
