# Generated by Django 3.2.18 on 2026-06-05 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0025_auto_20260501_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenesisUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, default='yiren', max_length=16, verbose_name='所属公司')),
                ('default_storecode', models.CharField(blank=True, max_length=16, null=True, verbose_name='默认门店')),
                ('storelist', models.CharField(blank=True, help_text='逗号分隔门店编号，如 88,01,02；公司管理员可留空（表示全部门店）', max_length=512, null=True, verbose_name='可用门店')),
                ('employee_code', models.CharField(blank=True, help_text='对应 hdsysuser.sys_userid / 小程序 ecode', max_length=16, null=True, verbose_name='员工工号')),
                ('display_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='显示姓名')),
                ('is_company_admin', models.BooleanField(default=False, help_text='等同 hdsysuser.sys_adm=Y，可登录公司下全部门店', verbose_name='公司管理员')),
                ('hdsysuser_uuid', models.UUIDField(blank=True, db_column='hdsysuser_uuid', help_text='可选；用于继承 useright 模块权限', null=True, verbose_name='关联 hdsysuser.uuid')),
                ('costpriceflag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='N', max_length=8, null=True, verbose_name='可查看成本价')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='genesis_profile', to=settings.AUTH_USER_MODEL, verbose_name='Django 用户')),
            ],
            options={
                'verbose_name': 'Genesis 用户扩展',
                'verbose_name_plural': 'Genesis 用户扩展',
                'db_table': 'genesis_user_profile',
                'managed': True,
            },
        ),
    ]
