# Generated by Django 3.2.18 on 2026-07-28 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_genesis_user_profile'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE genesis_user_profile CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
            reverse_sql="ALTER TABLE genesis_user_profile CONVERT TO CHARACTER SET cp852 COLLATE cp852_general_ci",
        ),
    ]
