# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-02 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmCase',
            fields=[
                ('last_modified', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间')),
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('creater', models.CharField(blank=True, default='anonymous', max_length=16, null=True, verbose_name='创建者')),
                ('flag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除')),
                ('company', models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='02', max_length=8, null=True, verbose_name='公司')),
                ('storecode', models.CharField(blank=True, max_length=16, null=True, verbose_name='门店')),
                ('casetype', models.CharField(blank=True, choices=[('10', '基础维护'), ('20', '拓客'), ('30', '客户投诉'), ('40', '到店服务回访'), ('45', '购买商品回访'), ('50', '预约客户到店')], max_length=8, null=True, verbose_name='类型')),
                ('viptype', models.CharField(blank=True, choices=[('10', '会员'), ('20', '散客')], default='10', max_length=8, null=True, verbose_name='会员/散客')),
                ('status', models.CharField(blank=True, choices=[('10', '未开始'), ('20', '进行中'), ('30', '已完成'), ('40', '暂停')], default='10', max_length=8, verbose_name='状态')),
                ('finishedate', models.DateField(blank=True, null=True, verbose_name='完成日期')),
                ('planbegindate', models.DateField(blank=True, null=True, verbose_name='计划日期')),
                ('casedesc', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述')),
                ('vsdate', models.DateField(blank=True, null=True, verbose_name='交易日期')),
                ('ecode', models.ForeignKey(blank=True, db_column='ecode', default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Empl', verbose_name='责任人')),
                ('vipuuid', models.ForeignKey(blank=True, db_column='vipuuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Vip', verbose_name='客户唯一号')),
            ],
            options={
                'verbose_name': '案例',
                'verbose_name_plural': '案例',
                'managed': True,
                'db_table': 'crmcase',
            },
        ),
        migrations.CreateModel(
            name='CrmCaseDetail',
            fields=[
                ('last_modified', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间')),
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('creater', models.CharField(blank=True, default='anonymous', max_length=16, null=True, verbose_name='创建者')),
                ('flag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除')),
                ('company', models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='02', max_length=8, null=True, verbose_name='公司')),
                ('storecode', models.CharField(blank=True, max_length=16, null=True, verbose_name='门店')),
                ('detaildescription', models.TextField(blank=True, null=True, verbose_name='沟通情况记录')),
                ('detail', models.CharField(blank=True, max_length=512, null=True, verbose_name='咨询记录')),
                ('caseid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.CrmCase', verbose_name='案例')),
                ('ecode', models.ForeignKey(blank=True, db_column='ecode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Empl', verbose_name='员工')),
            ],
            options={
                'verbose_name': '沟通记录',
                'verbose_name_plural': '沟通记录',
                'managed': True,
                'db_table': 'crmcasedetail',
            },
        ),
        migrations.CreateModel(
            name='VipCaseDetail',
            fields=[
                ('last_modified', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间')),
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('creater', models.CharField(blank=True, default='anonymous', max_length=16, null=True, verbose_name='创建者')),
                ('flag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除')),
                ('company', models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='02', max_length=8, null=True, verbose_name='公司')),
                ('storecode', models.CharField(blank=True, max_length=16, null=True, verbose_name='门店')),
                ('casetype', models.CharField(blank=True, choices=[('10', '基础维护'), ('20', '拓客'), ('30', '客户投诉'), ('40', '到店服务回访'), ('45', '购买商品回访'), ('50', '预约客户到店')], default='10', max_length=8, null=True, verbose_name='类型')),
                ('detaildescription', models.TextField(blank=True, null=True, verbose_name='沟通情况记录')),
                ('detail', models.CharField(blank=True, max_length=256, null=True, verbose_name='情况描述')),
                ('ecode', models.ForeignKey(blank=True, db_column='ecode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Empl', verbose_name='员工')),
                ('vipuuid', models.ForeignKey(blank=True, db_column='vipuuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Vip', verbose_name='客户唯一号')),
            ],
            options={
                'verbose_name': '客户沟通记录',
                'verbose_name_plural': '客户沟通记录',
                'managed': True,
                'db_table': 'vipcasedetail',
            },
        ),
    ]
