# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-16 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmcase',
            name='ecode',
            field=models.ForeignKey(blank=True, db_column='ecode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.Empl', verbose_name='责任人'),
        ),
    ]
