# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-01 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190216_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmcase',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan2', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='crmcasedetail',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan2', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='vipcasedetail',
            name='company',
            field=models.CharField(blank=True, choices=[('01', '新红妆'), ('02', '居明居')], default='youlan2', max_length=8, null=True, verbose_name='公司'),
        ),
    ]
