# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-12 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20190301_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRuler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=16, null=True, verbose_name='项目')),
            ],
        ),
    ]
