# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-19 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_caseruler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termtype', models.CharField(blank=True, max_length=8, null=True, verbose_name='术语类型')),
                ('term', models.CharField(blank=True, max_length=512, null=True, verbose_name='服务术语')),
            ],
        ),
        migrations.AlterModelOptions(
            name='caseruler',
            options={'managed': True, 'verbose_name': '客户服务规则', 'verbose_name_plural': '客户服务规则'},
        ),
        migrations.RemoveField(
            model_name='caseruler',
            name='item',
        ),
        migrations.AddField(
            model_name='caseruler',
            name='case_ruler_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='规则名称'),
        ),
        migrations.AddField(
            model_name='caseruler',
            name='valiflag',
            field=models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', max_length=8, null=True, verbose_name='是否有效'),
        ),
        migrations.AlterModelTable(
            name='caseruler',
            table='CaseRuler',
        ),
    ]
