# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-07 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20190602_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipcasedetail',
            name='ecode',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='员工'),
        ),
    ]
