# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-30 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_auto_20191115_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipcasedetail',
            name='casetype',
            field=models.CharField(blank=True, default='10', max_length=8, null=True, verbose_name='类型'),
        ),
    ]
