# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-16 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_auto_20191221_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipcasedetail',
            name='nextdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='下次回访日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vipcasedetail',
            name='nextecode',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='下次任务执行人工号'),
        ),
        migrations.AddField(
            model_name='vipcasedetail',
            name='status',
            field=models.CharField(blank=True, choices=[('10', '未开始'), ('20', '进行中'), ('30', '已完成'), ('40', '暂停')], default='10', max_length=8, verbose_name='状态'),
        ),
    ]
