# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-01 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_auto_20200216_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipcasedetail',
            name='nextdate',
            field=models.DateField(blank=True, null=True, verbose_name='下次回访日期'),
        ),
    ]
