# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-06-11 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_auto_20200401_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmInfoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('creater', models.CharField(blank=True, default='anonymous', max_length=16, null=True, verbose_name='创建者')),
                ('flag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除')),
                ('company', models.CharField(blank=True, default='yiren', max_length=8, null=True, verbose_name='公司')),
                ('itemid', models.CharField(blank=True, max_length=8, null=True, verbose_name='报表项序号')),
                ('itemname', models.CharField(blank=True, max_length=64, null=True, verbose_name='报表项名称')),
                ('itemtype', models.CharField(blank=True, choices=[('text', '文本'), ('decimal', '数值'), ('datetime', '日期'), ('radio', '单选'), ('check', '多选'), ('other', '其他')], max_length=16, null=True, verbose_name='报表项类型')),
                ('requireflag', models.CharField(blank=True, max_length=8, null=True, verbose_name='是否必填')),
                ('itemflag', models.CharField(blank=True, max_length=8, null=True, verbose_name='标志')),
            ],
            options={
                'managed': True,
                'db_table': 'crm_infoitem',
                'verbose_name_plural': '问题项目',
                'verbose_name': '问题项目',
            },
        ),
        migrations.CreateModel(
            name='CrmInfoItemChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('creater', models.CharField(blank=True, default='anonymous', max_length=16, null=True, verbose_name='创建者')),
                ('flag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除')),
                ('company', models.CharField(blank=True, default='yiren', max_length=8, null=True, verbose_name='公司')),
                ('orderno', models.CharField(blank=True, max_length=8, null=True, verbose_name='序号')),
                ('choiceitemname', models.CharField(blank=True, max_length=64, null=True, verbose_name='项次内容')),
                ('crminfoitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.CrmInfoItem', verbose_name='报表项次')),
            ],
            options={
                'managed': True,
                'db_table': 'crm_reportitem_choice',
                'verbose_name_plural': '问题选择项',
                'verbose_name': '问题选择项',
            },
        ),
        migrations.CreateModel(
            name='CrmSubReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('creater', models.CharField(blank=True, default='anonymous', max_length=16, null=True, verbose_name='创建者')),
                ('flag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除')),
                ('company', models.CharField(blank=True, default='yiren', max_length=8, null=True, verbose_name='公司')),
                ('crmsubreportName', models.CharField(blank=True, max_length=64, null=True, verbose_name='报表名称')),
            ],
            options={
                'managed': True,
                'db_table': 'crmsubreport',
                'verbose_name_plural': '客户关系报表',
                'verbose_name': '客户关系报表',
            },
        ),
        migrations.AddField(
            model_name='crminfoitem',
            name='crmsubreport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.CrmSubReport', verbose_name='报表'),
        ),
    ]
