# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-07-10 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_auto_20200710_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcase',
            name='ecode',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='员工'),
        ),
    ]
