# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-07-15 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_crmcase_ecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcase',
            name='planfinishdate',
            field=models.DateField(blank=True, null=True, verbose_name='计划完成日期'),
        ),
        migrations.AlterField(
            model_name='crmcase',
            name='finishedate',
            field=models.DateField(blank=True, null=True, verbose_name='实际完成日期'),
        ),
        migrations.AlterField(
            model_name='crmcase',
            name='planbegindate',
            field=models.DateField(blank=True, null=True, verbose_name='计划开始日期'),
        ),
    ]
