# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-03-19 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_auto_20210308_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmcase',
            name='company',
            field=models.CharField(blank=True, default='yfy', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='crmcase',
            name='ecodelist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('22013', '俞博士老师'), ('88002', '练习美容师'), ('22007', '张永芳B'), ('11009', '武军香-顾问'), ('admin', 'admin'), ('12017', '俞博士老师'), ('11010', '李红-顾问'), ('32014', '杨丽'), ('10000', '系统管理员'), ('ZB001', '梁振云'), ('ZB002', '郑红霞'), ('ZB003', '会计主管'), ('11002', '薛燕'), ('11003', '冯燕'), ('11004', '于梅'), ('11005', '徐春霞'), ('11006', '白秀丽'), ('11007', '孙洋洋'), ('11008', '常英'), ('12001', '蔺建萍'), ('12002', '史玉红'), ('12003', '张红梅'), ('12004', '姚玉梅'), ('12005', '时艳玲'), ('12006', '张晓燕'), ('12007', '李玲'), ('12008', '黄翠竹'), ('12009', '刘晓冉'), ('12010', '王丽红'), ('12011', '刘子霞'), ('12012', '何延敏'), ('13001', '成超瑜'), ('13002', '王红芳'), ('11001', '孙丽娜'), ('12013', '李红'), ('12014', '武军香'), ('13003', '于淑丽'), ('15001', '曹亚轩'), ('15002', '郄梦园'), ('12015', '张圣娜'), ('21002', '陈翠平'), ('23003', '董阿静'), ('23002', '吴谢荣'), ('23001', '马文惠'), ('22001', '李旭菁'), ('22002', '李潇鹏'), ('22003', '付秀梅'), ('22004', '韩若冰'), ('22005', '薛少菲'), ('22006', '刘艳'), ('21007', '张永芳A'), ('22008', '宫明'), ('22009', '张静洁'), ('22010', '于素娟'), ('22011', '任红然'), ('21001', '张关辉'), ('22012', '陈楚'), ('43002', '李春玲'), ('41001', '王红霞'), ('42001', '康燕'), ('42002', '付颜萍'), ('42003', '王增会'), ('42004', '朱章红'), ('41002', '常琳'), ('43001', '李素丽'), ('42005', '刘兰霞'), ('43003', '陈兰芝'), ('55001', '张洁'), ('52001', '解丽芳'), ('52002', '白云鹤'), ('52003', '张琦伟'), ('52004', '张晓莉'), ('51001', '王冬梅'), ('53001', '梁晓坤'), ('31001', '马红莉'), ('32001', '王晓敏'), ('32002', '梁艳'), ('31002', '王丽娅'), ('31003', '高春华'), ('32003', '张春颂'), ('32004', '原小丽'), ('32005', '张依娜'), ('32006', '董亚宁'), ('31004', '朱海青'), ('33001', '任凤燕'), ('33002', '王亚萍'), ('22012', '坤和堂老师'), ('ZB008', '医院医生'), ('42006', '坤和堂老师'), ('42007', '俞博士老师'), ('32008', '乔荣荣'), ('32010', '坤和堂老师'), ('admin', 'admin'), ('12019', '薛艳-美容师'), ('ZB004', '王娜'), ('admin', 'admin'), ('88dmin', 'admin'), ('882017', '俞博士老师'), ('881002', '薛燕'), ('881003', '冯燕'), ('881004', '于梅'), ('881005', '徐春霞'), ('881006', '白秀丽'), ('881007', '孙洋洋'), ('881008', '常英'), ('882001', '蔺建萍'), ('882002', '史玉红'), ('882003', '张红梅'), ('882004', '姚玉梅'), ('882005', '时艳玲'), ('882006', '张晓燕'), ('882007', '李玲'), ('882008', '黄翠竹'), ('882009', '刘晓冉'), ('882010', '王丽红'), ('882011', '刘子霞'), ('882012', '何延敏'), ('883001', '成超瑜'), ('883002', '王红芳'), ('881001', '孙丽娜'), ('882013', '李红'), ('882014', '武军香'), ('883003', '于淑丽'), ('885001', '曹亚轩'), ('885002', '郄梦园'), ('882015', '张圣娜'), ('882016', '坤和堂老师'), ('32009', '俞博士老师'), ('admin', 'admin'), ('52006', '俞博士老师'), ('admin', 'admin'), ('32007', '刘金丽'), ('admin', 'admin'), ('12018', '台湾专家'), ('52005', '坤和堂老师'), ('52007', '刘亚慧'), ('52008', '宋晓璐'), ('32011', '胡宁宁'), ('32012', '孙晓琳'), ('12016', '坤和堂老师'), ('88001', '练习-顾问'), ('888', '测试账户'), ('889', '测试账户美容师')], max_length=884, null=True, verbose_name='责任员工'),
        ),
        migrations.AlterField(
            model_name='crmcasedetail',
            name='company',
            field=models.CharField(blank=True, default='yfy', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='crminfoitem',
            name='company',
            field=models.CharField(blank=True, default='yfy', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='crminfoitemchoice',
            name='company',
            field=models.CharField(blank=True, default='yfy', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='crmsubreport',
            name='company',
            field=models.CharField(blank=True, default='yfy', max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='vipcasedetail',
            name='casetype',
            field=models.CharField(blank=True, choices=[('10', '初诊'), ('20', '复诊'), ('40', '再消费'), ('30', '复查')], default='10', max_length=8, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='vipcasedetail',
            name='company',
            field=models.CharField(blank=True, default='yfy', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
    ]
