# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-03-30 22:45
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_auto_20210325_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmcase',
            name='ecodelist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('44100002', '超级管理员'), ('32100003', '王红阳'), ('31310002', '孙丽荣'), ('32100004', '郭浩'), ('42100001', '荀玉洁'), ('97001', '何秀英'), ('32100005', '史晓蓉'), ('42100002', '赵霞'), ('33120005', '张晗'), ('44100001', '商佳男'), ('41100001', '蒋丽芳'), ('32100001', '陈晓菲'), ('42100001', '荀玉洁'), ('33120002', '李婷婷'), ('00005', '冯学英'), ('18065', '贺彩彩'), ('02', 'AI'), ('41130001', '齐红丽'), ('43100001', '杨芳'), ('33120004', '张琳')], max_length=164, null=True, verbose_name='责任员工'),
        ),
    ]
