# Generated by Django 3.2.18 on 2026-05-01 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0167_auto_20260501_0846'),
        ('report', '0035_auto_20220606_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportno1',
            name='storeuuid',
            field=models.ForeignKey(blank=True, db_column='storeuuid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.storeinfo', verbose_name='店铺'),
        ),
        migrations.AlterField(
            model_name='dailyreportvip',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='dailyreportvip',
            name='vipuuid',
            field=models.ForeignKey(blank=True, db_column='vipuuid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.vip', verbose_name='会员'),
        ),
        migrations.AlterField(
            model_name='monthlyreportno1',
            name='storeuuid',
            field=models.ForeignKey(blank=True, db_column='storeuuid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.storeinfo', verbose_name='店铺'),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='report_item_ruler',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='reportclassdata',
            name='empl',
            field=models.ForeignKey(blank=True, db_column='empluuid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.empl', verbose_name='员工'),
        ),
        migrations.AlterField(
            model_name='reportclassdata',
            name='report_class_type',
            field=models.CharField(blank=True, choices=[('200', '身体护理'), ('102', '060脸型管理2阶'), ('100', '面部护理'), ('MSK02', '美思科'), ('XSC1', '芯丝翠'), ('40', '挖客项目'), ('302', '交响组合A-0.38'), ('yfq', '产品伊肤泉'), ('50', '深挖项目'), ('080', '口腔'), ('201', '180形体管理1阶'), ('E', '面部强效项目'), ('700', '抗衰'), ('101', '050脸型管理1阶'), ('123', '130皮肤精细管理-清洁护理'), ('500', '微整形'), ('253', '240女性中段管理3阶'), ('LBY', '宝龄丽碧雅'), ('10', '基础项目'), ('20', '大项目'), ('222', '320身体精细管理-手足护理'), ('600', '客装产品'), ('A', 'A:基础项目'), ('400', '纹绣'), ('90', '其他项目'), ('NST01', 'N系统'), ('KYY', '科优研'), ('YBS1', '俞博士'), ('126', '150皮肤精细管理-面膜及营养补充'), ('MLTS', '美丽天使'), ('10', '美容'), ('212', '270舒压减痛2阶'), ('C', 'C:瘦狗项目'), ('HBX', '赫本线'), ('104', '080脸型管理4阶'), ('C', 'C:合作项目'), ('ZFX', '泽芙雪'), ('QT001', '其他'), ('144', '面部爱努碧斯'), ('XBYZ1', '细胞因子'), ('手工', '手工'), ('104', '100脸型管理 局部强化'), ('TYLMM', '童颜龄'), ('ZSF', '专家诊'), ('251', '220女性中段管理1阶'), ('ANBS', '爱努碧斯'), ('FLX', '面部富勒烯'), ('LGN', '拉古钠'), ('D', 'D:问题项目'), ('513', '030眉眼关系-无妆感丰睫'), ('BNS1', '玻尿酸'), ('122', '120皮肤精细管理-LPG机械手'), ('511', '010眉眼关系-无妆感丰眉'), ('泡澡', '泡澡'), ('JSY', '今生缘'), ('303', '交响组合B-0.60'), ('BLY', '博兰雅'), ('RBY', '润百颜'), ('AT001', '奥肽'), ('BD01', '半岛'), ('JBJS', '吉备'), ('JN', '珈纳'), ('121', '090皮肤精细管理-紧致塑型'), ('A', 'A:基础项目'), ('A', 'A:明星项目'), ('B', 'B：金牛项目'), ('512', '020眉眼关系-无妆感厘睫'), ('142', '面部珈纳'), ('D', 'D:医美'), ('510', '整形手术'), ('100', '店内项目'), ('YFQ1', '伊肤泉'), ('252', '230女性中段管理2阶'), ('AWL02', '艾维岚'), ('YN001', '英诺'), ('305', '自由节奏A-26'), ('301', '如歌组合B-0.68'), ('美团', '美团'), ('RZ01', '润致'), ('306', '创始卡'), ('ACWE', '爱驰卫尔'), ('B', 'B:金牛项目'), ('202', '190形体管理2阶'), ('232', '300体型管理-懒人运动'), ('B', 'B:大项目'), ('125', '140皮肤精细管理-眼部护理'), ('SMYQ1', '私密仪器'), ('D', 'D:医美'), ('LFL1', '面部罗肤籣'), ('PLLS1', '帕莉丽丝'), ('304', '交响组合C-10'), ('LD', '朗顿'), ('MBYFQ', '面部伊肤泉'), ('233', '310体型管理-身体LPG机械手'), ('23', '即时转账'), ('300', '如歌组合A-0.38'), ('20', '美体'), ('146', '面部修丽可'), ('213', '280舒压减痛3阶'), ('PCD', 'PCD'), ('CZ001', '痤疮'), ('15', '面部单加项'), ('C', 'C:合作项目'), ('ABS2', '艾贝诗'), ('B', 'B:大项目'), ('145', '面部法儿曼'), ('C', 'C：瘦狗项目'), ('231', '170体型管理-塑型 消耗'), ('GL', '刚伦'), ('610', '保健品'), ('500', '外包'), ('103', '070.脸型管理3阶'), ('仪器', '仪器'), ('101', '微整形'), ('102', '整形手术'), ('103', '面部思蒂'), ('104', 'NB悦碧施'), ('105', '面部奥尔滨'), ('106', '苹果干细胞'), ('107', '面部雪之莹'), ('108', '面部小分子'), ('109', '面部瑞嘉奥'), ('110', '面部其他'), ('111', '眼部安格安晴'), ('112', '身体巨邦'), ('113', '臀部'), ('114', '结肠'), ('115', '私密'), ('116', 'BIO'), ('117', '今生缘'), ('118', '身体其他'), ('119', '极限音波拉皮'), ('120', '射频'), ('121', '水光'), ('122', '脱毛'), ('123', '白瓷'), ('124', '光子'), ('125', '仪器'), ('126', '其他'), ('127', '纹绣'), ('128', '产品奥尔滨'), ('129', '产品NB悦碧施'), ('130', '产品思蒂'), ('131', '产品瑞嘉奥'), ('132', '产品修丽可'), ('133', '产品法儿曼'), ('134', '产品私密'), ('135', '荷尔蒙贴'), ('136', '产品其他'), ('137', '保健品'), ('138', '无象源'), ('139', '抗衰'), ('140', '口腔'), ('141', '其他'), ('124', '110皮肤精细管理-马步会员专享'), ('211', '260舒压减痛1阶'), ('YBWZ', '安格安晴'), ('A', 'A：特色项目'), ('RPS1', '芮派思'), ('JS', '吉适'), ('306', '自由节奏B-38'), ('254', '250女性中段管理4阶'), ('D', 'D：问题项目'), ('YMY', '研美颜'), ('204', '210形体管理4阶'), ('221', '290身体精细管理-女性胸部护理'), ('I01', '其它'), ('RT01', '瑞瑅'), ('10', '拓客项目'), ('127', '160皮肤精细管理-洁牙护理'), ('F', '身体强效项目'), ('223', '330身体精细管理-角质调理及泡浴'), ('300', '仪器治疗'), ('143', '面部科优研'), ('20', '留客项目'), ('SL002', '丝丽'), ('514', '040懒虫轻造型-美发'), ('203', '200形体管理3阶')], max_length=32, null=True, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='reportclassdata',
            name='storeuuid',
            field=models.ForeignKey(blank=True, db_column='storeuuid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.storeinfo', verbose_name='店铺'),
        ),
        migrations.AlterField(
            model_name='reportclassdata',
            name='vip',
            field=models.ForeignKey(blank=True, db_column='vipuuid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.vip', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='reportitem',
            name='report_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='report.report', verbose_name='报表'),
        ),
        migrations.AlterField(
            model_name='reportitemdata',
            name='report_item_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='report.reportitem', verbose_name='报表项次'),
        ),
    ]
