# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-12 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wechatappfuntion',
            options={'verbose_name': '微信小程序配置', 'verbose_name_plural': '微信小程序配置'},
        ),
        migrations.AlterModelTable(
            name='wechatappfuntion',
            table='WechatAppFuntion',
        ),
    ]
