# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-13 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20191012_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatappfuntion',
            name='valiflag',
            field=models.CharField(blank=True, default='Y', max_length=8, null=True, verbose_name='是否有效'),
        ),
    ]
