# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-16 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_wechatappfuntion_valiflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatappfuntion',
            name='appname',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='小程序名称'),
        ),
    ]
