# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-18 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0004_wechatappfuntion_appname'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatUser',
            fields=[
                ('last_modified', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间')),
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('creater', models.CharField(blank=True, default='anonymous', max_length=16, null=True, verbose_name='创建者')),
                ('flag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除')),
                ('company', models.CharField(blank=True, default='yfy', max_length=8, null=True, verbose_name='公司')),
                ('openid', models.CharField(db_index=True, max_length=128, unique=True)),
                ('unionid', models.CharField(blank=True, max_length=128, null=True)),
                ('nickname', models.CharField(blank=True, max_length=256, null=True)),
                ('sex', models.IntegerField(default=0)),
                ('province', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('language', models.CharField(blank=True, max_length=128, null=True)),
                ('avatarUrl', models.CharField(blank=True, max_length=256, null=True)),
                ('privilege', models.CharField(blank=True, max_length=128, null=True)),
                ('is_phantom', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('is_follow', models.BooleanField(default=False)),
                ('sign', models.CharField(blank=True, max_length=16, null=True)),
                ('sign_expire', models.BigIntegerField(default=0)),
                ('user_type', models.CharField(blank=True, choices=[('100', '商家员工'), ('200', '消费者')], max_length=8, null=True, verbose_name='用户类型')),
                ('useruuid', models.UUIDField(blank=True, verbose_name='用户UUID')),
                ('companylist', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('yfy', '石家庄雅芳亚'), ('yiren', '北京伊人'), ('JMJ', '居明居')], max_length=13, null=True, verbose_name='可用门店')),
            ],
            options={
                'db_table': 'Wechat_User',
            },
        ),
    ]
