# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-21 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0005_wechatuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatuser',
            name='useruuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='用户UUID'),
        ),
    ]
