# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-01 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0007_wechatuser_appcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatAppFunctions',
            fields=[
                ('last_modified', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='最后修改时间')),
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('creater', models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者')),
                ('flag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除')),
                ('company', models.CharField(blank=True, default='yfy', editable=False, max_length=8, null=True, verbose_name='公司')),
                ('storecode', models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店')),
                ('appcode', models.CharField(blank=True, choices=[('100', '帮小主'), ('200', '最小主'), ('300', '小主咖')], max_length=16, null=True, verbose_name='小程序代号')),
                ('functiontype', models.CharField(blank=True, max_length=16, null=True, verbose_name='功能类型')),
                ('functionid', models.CharField(blank=True, max_length=16, null=True, verbose_name='功能模块编号')),
                ('functionname', models.CharField(blank=True, max_length=32, null=True, verbose_name='功能名称')),
                ('wxusertype', models.CharField(blank=True, choices=[('100', '商家员工'), ('200', '消费者')], max_length=16, null=True, verbose_name='岗位')),
                ('id', models.IntegerField(blank=True, default=1, null=True, verbose_name='序号')),
                ('text', models.CharField(blank=True, max_length=32, null=True, verbose_name='描述')),
                ('url', models.CharField(blank=True, max_length=128, null=True, verbose_name='链接')),
                ('image', models.CharField(blank=True, max_length=128, null=True, verbose_name='图片')),
                ('parentfunction', models.CharField(blank=True, max_length=16, null=True, verbose_name='上级模块')),
                ('valiflag', models.CharField(blank=True, default='Y', max_length=8, null=True, verbose_name='是否有效')),
            ],
            options={
                'verbose_name': '微信小程序配置',
                'verbose_name_plural': '微信小程序配置',
                'db_table': 'WechatAppFunctions',
            },
        ),
        migrations.DeleteModel(
            name='WechatAppFuntion',
        ),
        migrations.RenameField(
            model_name='wechatuser',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='companylist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('salon', None), ('yfy', '石家庄雅芳亚'), ('yiren', '北京伊人'), ('JMJ', '居明居')], max_length=19, null=True, verbose_name='可用门店'),
        ),
    ]
