# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-30 21:27
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0009_auto_20191104_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatuser',
            name='companylist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, max_length=200, null=True, verbose_name='可用门店'),
        ),
    ]
