# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-03-01 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0013_auto_20200203_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatappfunctions',
            name='company',
            field=models.CharField(blank=True, default='yfy', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='company',
            field=models.CharField(blank=True, default='yfy', max_length=8, null=True, verbose_name='公司'),
        ),
    ]
