# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-04-05 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0017_auto_20210319_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatappfunctions',
            name='valiflag',
            field=models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', max_length=8, null=True, verbose_name='是否有效'),
        ),
    ]
