# Generated by Django 3.2.18 on 2026-08-02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_auto_20260727_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmRule',
            fields=[
                ('last_modified', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间')),
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('creater', models.CharField(blank=True, default='anonymous', editable=False, max_length=16, null=True, verbose_name='创建者')),
                ('flag', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', editable=False, max_length=8, null=True, verbose_name='是否删除')),
                ('company', models.CharField(blank=True, default='yiren', editable=False, max_length=8, null=True, verbose_name='公司')),
                ('storecode', models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='门店')),
                ('rule_name', models.CharField(max_length=64, verbose_name='规则名称')),
                ('rule_type', models.CharField(choices=[('birthday', '生日关怀'), ('anniversary', '入会周年'), ('transaction', '成交回访'), ('lifecycle', '生命周期预警'), ('custom', '自定义')], default='birthday', max_length=16, verbose_name='规则类型')),
                ('casetype', models.CharField(blank=True, choices=[('10', '基础维护'), ('20', '拓客'), ('30', '客户投诉'), ('40', '到店服务回访'), ('45', '购买商品回访'), ('50', '预约客户到店')], max_length=8, null=True, verbose_name='任务类型')),
                ('days_offset', models.IntegerField(blank=True, default=0, null=True, verbose_name='天数偏移')),
                ('month_offset', models.IntegerField(blank=True, default=1, null=True, verbose_name='月份偏移')),
                ('ttype', models.CharField(blank=True, max_length=8, null=True, verbose_name='交易类型(S/G/C/I)')),
                ('lifecycle_segment', models.CharField(blank=True, max_length=16, null=True, verbose_name='生命周期分段')),
                ('casedesc_template', models.CharField(blank=True, max_length=256, null=True, verbose_name='任务描述模板')),
                ('assignee_policy', models.CharField(choices=[('vip_ecode', '客户顾问'), ('vip_ecode2', '指定美疗师'), ('fixed', '固定员工'), ('store_manager', '店长')], default='vip_ecode', max_length=16, verbose_name='派单策略')),
                ('fixed_ecode', models.CharField(blank=True, max_length=16, null=True, verbose_name='固定员工工号')),
                ('enabled', models.CharField(blank=True, choices=[('Y', '有效'), ('N', '无效')], default='Y', max_length=8, null=True, verbose_name='是否启用')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间')),
                ('last_run_summary', models.CharField(blank=True, max_length=256, null=True, verbose_name='上次执行结果')),
            ],
            options={
                'verbose_name': '关怀规则',
                'verbose_name_plural': '关怀规则',
                'db_table': 'crm_rule',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='crmcase',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='crm.crmrule', verbose_name='来源规则'),
        ),
        migrations.AddField(
            model_name='crmcasedetail',
            name='channel',
            field=models.CharField(blank=True, choices=[('10', '电话'), ('20', '微信'), ('30', '短信'), ('40', '到店'), ('90', '其他')], max_length=8, null=True, verbose_name='触达渠道'),
        ),
        migrations.AddField(
            model_name='crmcasedetail',
            name='outcome',
            field=models.CharField(blank=True, choices=[('10', '已联系'), ('20', '未接通'), ('30', '待跟进'), ('40', '已拒绝'), ('50', '已预约')], max_length=8, null=True, verbose_name='触达结果'),
        ),
        migrations.AddField(
            model_name='crmcasedetail',
            name='contact_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='触达时间'),
        ),
        migrations.AddField(
            model_name='crmcasedetail',
            name='nextdate',
            field=models.DateField(blank=True, null=True, verbose_name='下次回访日期'),
        ),
        migrations.AddField(
            model_name='crmcasedetail',
            name='nextecode',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='下次任务员工'),
        ),
    ]
