# Generated by Django 3.2.18 on 2026-08-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_crm_workbench'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipcasedetail',
            name='caseid',
            field=models.UUIDField(blank=True, null=True, verbose_name='关联回访任务'),
        ),
    ]
