# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-07-11 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0018_auto_20210405_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatappfunctions',
            name='company',
            field=models.CharField(blank=True, default='yiren', editable=False, max_length=8, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='company',
            field=models.CharField(blank=True, default='yiren', max_length=8, null=True, verbose_name='公司'),
        ),
    ]
