# Generated by Django 3.2.18 on 2026-05-01 08:46

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0019_auto_20210711_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatappfunctions',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='companylist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('salon', None), ('xhz', None), ('yfy', '石家庄雅芳亚'), ('yiren', '北京伊人'), ('JMJ', '居明居')], max_length=23, null=True, verbose_name='可用公司'),
        ),
    ]
